### PR TITLE
Classic Mode - Add ribbon to both pokemon species when there is fusion

### PR DESCRIPTION
**Pull request by ReneGV**
Implementing this issue: https://github.com/pagefaultgames/pokerogue/issues/1072

Add a ribon to both pokemon species whenever a pokemon is a fussion.

### CODE REVIEW

**Comment by j-diefenbach** [comment]
This isn't a bug it's intended behaviour. Otherwise you would expect to get two tickets, one for each pokemon in the fusion so if you win classic with a full party of fusions you get twice the tickets.

**Comment by ReneGV** [comment]
> This isn't a bug it's intended behaviour. Otherwise you would expect to get two tickets, one for each pokemon in the fusion so if you win classic with a full party of fusions you get twice the tickets.
@j-diefenbach 
Yep I agree, however the `awardRibbon` method I used also awards ticket rewards.
So if you beat the game with a party full of fussions you would indeed get the double annount of tickets.

If you fuse pokemon A and B, both texts:
`A beat classic for first time, you received ...`
`B beat classic for first time, you received ...`

**Comment by j-diefenbach** [comment]
> So if you beat the game with a party full of fussions you would indeed get the double amount of tickets.

Yeah my opinion is that this is sorta unbalanced. Obviously it's not game breaking but I think it makes sense you only get the ribbon and ticket for the base pokemon. This has most likely been considered before and I'm sure the devs originally decided not to do it that way.

**Comment by jaimefd** [comment]
I may be missing some strat to get lots of DNA splicers in classic but i rarely ever get one, never even got more than 2 in a single run, I dont think this is unbalanced

**Comment by TempsRay** [comment]
Originally the main reason to prevent this was we didn't want a case where a player would have Pokemon A fused with Pokemon B but be missing Pokemon B's starter dex entry which would result in a weird case of missing a dex entry but having a ribbon. However, since this only applies to classic mode, the only way to own a fusion is to have both component starters owned and DNA splicers are super rare, I'm not completely opposed to this change.

**Comment by ReneGV** [comment]
Thanks for your feedback @TempsRay. It looks there is consensus that this change is not unbalanced 
Please let me know if there is work remaining to do in order to get approval,

**Comment by bennybroseph** [comment]
I don't think this is something that should be added. My reasoning is actually because I don't think capturing a Pokemon mid-run should count either. I know that's way too much of a hot take, but I feel like the ribbon is intended to be a "Hey I started with this Pokemon at floor 1 and beat classic with it!" but really it's kinda just a "Hey I took this Pokemon to Eternatus" and that's it. It doesn't even need to participate in a single battle. 

Again, it's a hot take and too late to really change now, but I'd make it to where the Pokemon must be selected in the starter selection screen. Then you could fuse it or do whatever you want and it'd count so long as it stayed on your team til the final floor.

So yeah, this change moves even further from that so I don't really like it even though it rarely happens anyway.

**Comment by Tempo-anon** [comment]
> Again, it's a hot take and too late to really change now, but I'd make it to where the Pokemon must be selected in the starter selection screen. Then you could fuse it or do whatever you want and it'd count so long as it stayed on your team til the final floor.

Heavily disagree with this since that would make gathering ribbons even more tedious than it currently is for legendary, paradox, and expensive Pokemon, and there's already an in game precedent for how the champion's ribbon works.

As for the PR itself, while this would be a nice QOL change that would not have giant impact, we are planning on adding spliced classic in the future and in such a case it would not make sense for fused pokemon to give double ribbons as that would make spliced classic a much more efficient ribbon/egg farming method. The alternative workaround of only allowing non-spliced classic fusions give double ribbons is quite hacky.

**Pull request closed without merging**
