### PR TITLE
Update modifier-type.ts [Localization(it)]

### PR DESCRIPTION
**Pull request by NicusPulcis**
## What are the changes?
Lots of translations have beenr reworked and some have been added.

## Why am I doing these changes?
To complete the full translation of Pokerogue in italian. 

### Screenshots/Videos
Screenshot 2024-06-16 12 13 21
Screenshot 2024-06-16 12 13 29
Screenshot 2024-06-16 12 13 36
Screenshot 2024-06-16 12 13 45
Screenshot 2024-06-16 12 13 52

## How to test the changes?
Play the game in italian.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by bennybroseph** [comment]
Do you have a source on these translations? This should come from official sources, not a translation of English.

**Review by Tempo-anon — DISMISSED** [review]

**Review by EnochG1 — COMMENTED** [review]
Should these tab character be removed?
If not, skip my suggestion.
If it should, you can get my suggestion with this way.

suggestion을 바로 commit하는법

**Comment by EnochG1** [comment]
@Tempo-anon 
This PR is what you approved before.
I and Nicus resolved conflict so ready to be merged.

**Review by Tempo-anon — APPROVED** [review]
Approved by the wiki/tl team

**Pull request merged**
