### PR TITLE
[Refactor] rewrite applyAbAttrsInternal to use an iterator.

### PR DESCRIPTION
**Pull request by OrangeRed**
## What are the changes?
Unspaghettify how we currently apply ability attributes

## Why am I doing these changes?
Pain

## What did change?
1) Rewrite `applyAbAttrsInternal` so its clearer what is happening

## How to test the changes?
Test if the application of abilities follows the same order as on live.
This change has been merged #2829 onto https://beta.pokerouge.net so manual testing can be done there.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
~~- [ ] Are the changes visual?~~
~~- [ ] Have I provided screenshots/videos of the changes?~~

### CODE REVIEW

**Comment by OrangeRed** [comment]
#1839 potentially blocks this PR

**Comment by DustinLin** [comment]
Not sure if this is a bug this PR, it seems to happen in `main` as well

The intimidate from biome change doesn't activate properly, though the drizzle does. The timing of the ability visual is also a bit off

PR:

https://github.com/pagefaultgames/pokerogue/assets/39450497/30510834-f073-49b3-857f-7f81cde6f66f


Main:

https://github.com/pagefaultgames/pokerogue/assets/39450497/6043e0df-1d0f-45fe-8bc0-f1e4f6b3902d

**Comment by OrangeRed** [comment]
@DustinLin can you check on main if drizzle triggers before or after the switch in dialogue because that is the difference in the two videos that you posted. (the first asks you to switch, the second doesn't)

**Comment by DustinLin** [comment]
the first video is from this pr, the second is from main

**Comment by DustinLin** [comment]
Alternative setup, seems the same, the intimidate bug happens on both:

pr

https://github.com/pagefaultgames/pokerogue/assets/39450497/f6b245c4-10a9-4226-980b-5571fa564133



`main`


https://github.com/pagefaultgames/pokerogue/assets/39450497/49352d55-d9cf-41cd-abb7-dbfa7d5df728

---
pr:


https://github.com/pagefaultgames/pokerogue/assets/39450497/d773fa4d-5507-4cbb-81f9-566286997dad


`main`:

https://github.com/pagefaultgames/pokerogue/assets/39450497/bb432841-2d8a-4bff-b74a-321e7d9874f3

**Comment by OrangeRed** [comment]
@DustinLin the intimidate bug is a known issue and fixing it is beyond the scope of this PR.

Also from the videos that you sent, namely the third and fourth, drizzle seems to be triggering at the same time as on main which is a good thing.

**Comment by blakethorne5112** [comment]
Tested by overriding ability and passives:

Case 1: Ability: Drizzle, Passive: Intimidate
Main: Throw out Pokemon -> Drizzle -> Intimidate
PR: Throw out Pokemon -> Drizzle -> Intimidate
Consistent

Case 2: Ability: Sharpness, Passive: Tough Claws, Move: Behemoth Blade (Fits both criteria)
Main: Use Behemoth Blade -> Sharpness activates -> Tough Claws activates
PR: Use Behemoth Blade -> Sharpness activates -> Tough Claws activates
Consistent

Case 3: Ability: Tough Claws, Passive: Sharpness, Move: Behemoth Blade
Main: Use Behemoth Blade -> Tough Claws activates -> Sharpness activates
PR: Use Behemoth Blade -> Tough Claws activates -> Sharpness activates
Consistent

Case 4: Ability: Pickup, Opponent Ability: Iron Barbs, Move: Ceaseless Edge
Main: Ceaseless Edge kills -> Opponent faints -> EXP Gain -> Spikes scattered -> Iron Barbs activates -> Pickup activates
PR: Ceaseless Edge kills -> Opponent faints -> EXP Gain -> Spikes scattered -> Iron Barbs activates -> Pickup activates
Consistent

Should now be tested for:
Pre battle: Drizzle/Intimidate
On hit/during turn: Tough Claws/Sharpness
After hit/post turn: Ceaseless Edge/Iron Barbs
Post battle: Pickup

**Review by blakethorne5112 — APPROVED** [review]

**Comment by flx-sta** [comment]
@OrangeRed bump for conflicts resolve

**Review by flx-sta — APPROVED** [review]
✅ code review
🔲  play-test
✅ tests image

**Pull request merged**
