### PR TITLE
[Misc] Make `OPP_MOVESET_OVERRIDE` fully override the enemy's moveset

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
N/A

## Why am I making these changes?
To get rid of the annoying need to use `Array(4).fill(Moves.MOVENAME)` when overriding the enemy's moveset.

## What are the changes from a developer perspective?
The enemy's moveset array will be exactly set to the moveset passed to the override, rather than only modifying the existing moveset array (which could potentially leave some of the Pokémon's regular moves in the array).

### Screenshots/Videos
No override (opposing Pokémon has 2 default moves in its moveset array):
image

With override set to `[Moves.SPLASH]` (opposing Pokémon only has 1 move in its moveset array):
image

## How to test the changes?
Modify `overrides.ts` as follows and enter any battle.
```ts
const overrides = {
  OPP_MOVESET_OVERRIDE: [Moves.SPLASH]
} satisfies Partial<InstanceType<typeof DefaultOverrides>>;
```

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- ~[ ] Have I considered writing automated tests for the issue?~
- ~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

### CODE REVIEW

**Review by torranx — COMMENTED** [review]
looks good but I would prefer it to accept `Moves` or `Moves[]`

**Comment by DayKev** [comment]
Both the player and enemy moveset overrides are now optionally arrays.

**Comment by innerthunder** [comment]
The `SPLASH_ONLY` util isn't needed anymore after this, right? I suppose you can get rid of it with this PR...

**Comment by DayKev** [comment]
Good point.

**Review by innerthunder — APPROVED** [review]

**Review by torranx — COMMENTED** [review]
minor nit: there are movesets set to single item arrays, otherwise looks good

**Pull request merged**
