### PR TITLE
Issue #523 Facade should now ignore the attack reduction of beeing bu…

### PR DESCRIPTION
**Pull request by CodeTappert**
…rned

Fixes: https://github.com/pagefaultgames/pokerogue/issues/523

### CODE REVIEW

**Comment by happinyz** [comment]
Seems like a PR was already opened for this: https://github.com/pagefaultgames/pokerogue/pull/530

**Comment by CodeTappert** [comment]
@happinyz But those fix two different places in the code. 

Did i do the wrong place? Or should we combine both?

**Comment by happinyz** [comment]
I think your implementation also works fine. I'd tend to use @mattrossdev's implementation just because we can exit the if block earlier and avoid having to do unnecessary calculations

**Comment by CodeTappert** [comment]
Okay well then i will close this. It is a duplicate of #530

**Pull request closed without merging**
