### PR TITLE
[QoL] Gender-Inclusive Wording for Trainer-related Terms 

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes?
I noticed that many variable names for trainers were sex-based and non-inclusive to the point of treating male trainers as the default. The current status quo stems from societal bias that considers cis men as the default. By changing the language from 'female' to 'alternate', this opens the door to having trainer variants that are not limited by gender. This should not have any effect on gameplay and is meant to encourage a more-inclusive developer mindset.  

Link: https://www.nybooks.com/articles/2021/02/11/medicine-is-made-for-men/?lp_txn_id=1016278 
Link 2: https://web.stanford.edu/~hazelm/publications/2020%20Cheryan%20Markus%20Masculine%20defaults.pdf 

## Why am I doing these changes?
I thought it would be right to do so. I do have personal investment as a non-binary individual but that's why I acted. 

## What did change?
nameFemale --> nameAlt
femaleEncounterBGM --> altEncounterBGM
femaleDefeatMessages --> altDefeatMessages

## How to test the changes?
Just run the code as normal and see if anything breaks. 

## Checklist
- [ x ] There is no overlap with another PR?
- [ x ] The PR is self-contained and cannot be split into smaller PRs?
- [ x ] Have I provided a clear explanation of the changes?
- [ x ] Have I tested the changes (manually)?
    - [ x ] Are all unit tests still passing? (`npm run test`)

### CODE REVIEW

**Comment by CodeTappert** [comment]
Dont know if this is needed at all. But if it is this will need a LOT of testing. 

I think some points in the code literally check if it is "female". So those places need to be tested if they still work.

**Comment by frutescens** [comment]
The condition hasGenders (trainer-config.ts) which is responsible for those differences, has not been changed.

**Comment by roberika** [comment]
I'd second these changes. Changing it to default and alternate could give future development more flexibility. From what I see as well it only changes our variable names, not the game itself.

**Comment by CodeTappert** [comment]
I would love to see some unit tests on this. Or at least some screenshots/videos to see if everything like female spawn and doubles etc still work.

Also resolve your merge requests please

**Comment by brain-frog** [comment]
Male and Female as gendered terms help with localization, I do not want "alternate" to confuse translators.

**Pull request closed without merging**
