### PR TITLE
Serene Grace, Shield Dust and Sheer Force partially implemented.

### PR DESCRIPTION
**Pull request by NxKarim**
- Added `MoveEffectChanceMultiplierAbAttr` to modify additional effect chances with multipliers.
- Added `IgnoreMoveEffectsAbAttr`; this sets to zero the chance of foe's moves additional effects.
- Changed `AddArenaTrapTagAttr`, `AddBattlerTagAttr`, and `StatusEffectAttr` to allow for modified additional effect chance.
- Added `getSheerForceHitDisableAbCondition` applied to abilities that get disable when hit by a Sheer Force boosted move.
- Added conditions to Poison Touch, Toxic Chain and Stench to be ignored by Shield Dust.
- Changed the additional effect chance of certain moves to make them immune or susceptible to chance modification as according to the main games.
Moves not affected by chance modification were changed to -1 because their effects will always apply.
Moves that are affected by chance modification were changed to 100, this allows for chance to be modified.
Most of these changes are because of Sheer Force.

Implemented:
- Serene Grace: Boosts moves additional effect chance by x2.
- Sheer Force: Boosts power of moves with additional effect by ~1.3. Disables additional effects on own moves. After boosted hit disables Color Change, PickPocket, Wimp Out, Emergency Exit, Berserk and Anger Shell.
- Shield Dust: Disables foe's moves additional effects and the effects of Poison Touch, Toxic Chain and Stench.
- Serene Grace doubles the chances of King's Rock
- Sheer Force negates King's Rock if the move has a secondary effect
- King's Rock won't applied if the target has Shield Dust

Not yet implemented:
- Sheer Force: Disable Meloetta form change. Disable Eerie Spell and Secret Power effect (Since they all are partially implemented).

Edit:
-Comments added as requested.
-Some new implementations added.

Edit 2:
- More moves set to not be affected by chance modification. 
- Added Order Up interaction with chance modification.

Edit 3:
- King's Rock interaction by Okimin

### CODE REVIEW

**Review by bennybroseph — APPROVED** [review]

**Comment by Blitz425** [comment]
Hoping more work can be done on this, I'm really looking forward to Sheer Force functioning!

**Comment by okimin** [comment]
### Test on the  Current Changes

1. Serene Grace 
Insert  `console.log("%s has a chance of %O", [move.name](http://move.name/), moveChance.value);`  above 
`return moveChance.value;` into getMoveChance method in move.ts.

Override ability with serene grace or use a pokemon with Serene Grace as first ability or passive ( Dunsparce or Jirachi) . Compare chance values with a pokemon that doesnt have serene grace. Chance should be double or 100%.

https://github.com/pagefaultgames/pokerogue/assets/33844732/5a0009af-5c98-4d7b-9e6f-8af1525221a8

2. Sheer Force

Similar to Serene Grace except value should be 0 except for specific moves ( should have -1 instead). 

I override bonsly with color change which should be disabled by sheer force. Testing with normal nidoran ability.
https://github.com/pagefaultgames/pokerogue/assets/33844732/bac7791c-85be-45c5-9603-752dd5d42d8f

I then override with sheer force. Can see the added power as well on console.

https://github.com/pagefaultgames/pokerogue/assets/33844732/a17710c6-c25b-48f3-87d5-d07599559e05

Testing that Whirlpool and other exceptions still works.

https://github.com/pagefaultgames/pokerogue/assets/33844732/6fea0f41-311e-4367-b1dc-956e1bb280b8

3. Shield Dust

Similar testing to Serene Grace and Sheer Force.

https://github.com/pagefaultgames/pokerogue/assets/33844732/9c60ce9e-6a0b-4879-a50e-fb6fad205c63


I also tried override with toxic chain and poison touch and while the ability was not shown, the pokemon was not poisoned due to the logic seen in the commit. Will discuss on discord for further discussions on tests and also on the conflicts that needs to be resolved.

**Comment by Tempo-anon** [comment]
Merge conflicts in ability.ts, move.ts, and phases.ts

**Comment by okimin** [comment]
https://discord.com/channels/1125469663833370665/1237649590207909919/1251744047794622535

**Review by Tempo-anon — APPROVED** [review]

**Comment by Smewkie** [comment]
can we make sure to get comments next to the .partial() in the future as to why something is still partial, just so future reviewers of the code don't have to hunt down a PR to find out what's up? <3

**Pull request merged**
