### PR TITLE
Added A Toggle For The IV Scanner In The Style Of Lock Capsule

### PR DESCRIPTION
**Pull request by Simplyfenton**
Fairly certain this is a feature that a lot of players want (myself included)

Added the toggle to the shop on the bottom right hand side, to mirror that of the Lock Capsule.

It's certainly not the prettiest implementation, and the logic could likely be compacted from what I've got, but in fairness to me, I did start making this at 8am.

(Any feedback and stuff would be great, first time contributing to a public project like this)

### CODE REVIEW

**Comment by CodeTappert** [comment]
Please add images showing it.

**Comment by karl-police** [comment]
conflicts with https://github.com/pagefaultgames/pokerogue/pull/1074

**Comment by Simplyfenton** [comment]
> Please add images showing it.

The text being red indicates that the IV Scanner is currently disabled.



Demo


> When I first, got the idea to add that. I realized that adding a Toggle simply isn't enough. What's the point of being able to toggle it. You don't know what Pokemon you encounter next. But giving the ability to Force Scan as well. Now that one, is a pog.

I think a "force scan" is something that would likely be useful, but as it stands, I don't think there's anywhere that it would go within the battle UI that would "fit", and it certainly wouldn't belong in the standard menu. Since neither the Lock Capsule or this IV Scanner setting are saved, refreshing the page would re-enable the IV Scanner at the start of the current battle which, while not ideal, is an option before a wider discussion about the "force scan"'s implementation. I don't know how many people I speak for, but I personally wouldn't mind not having the force scan option - the upside of not having the dialogue boxes at the beggining of every non-trainer battle is then balanced by the downside of not having that information to hand readily.

**Comment by CodeTappert** [comment]
Definitly it can not be that color. 
It is really hard to read that way. (But maybe its my red color deficency). There is not.enough contrast between the text and the Background

**Comment by karl-police** [comment]
> > Please add images showing it.
> 
> The text being red indicates that the IV Scanner is currently disabled.
> 
> Demo
> 
> > When I first, got the idea to add that. I realized that adding a Toggle simply isn't enough. What's the point of being able to toggle it. You don't know what Pokemon you encounter next. But giving the ability to Force Scan as well. Now that one, is a pog.
> 
> I think a "force scan" is something that would likely be useful, but as it stands, I don't think there's anywhere that it would go within the battle UI that would "fit", and it certainly wouldn't belong in the standard menu. Since neither the Lock Capsule or this IV Scanner setting are saved, refreshing the page would re-enable the IV Scanner at the start of the current battle which, while not ideal, is an option before a wider discussion about the "force scan"'s implementation. I don't know how many people I speak for, but I personally wouldn't mind not having the force scan option - the upside of not having the dialogue boxes at the beggining of every non-trainer battle is then balanced by the downside of not having that information to hand readily.

I believe that with additions that allow flexibility in the code itself, to quickly change how it is implemented, shouldn't bring a worry on where it is currently put at.


The IV-Scanner is just one of current things. If I'd toggle the IV-Scanner off, and I encounter a Pokemon that I do want to scan, then one is simply just screwed. But you can re-open the game and then just scan it, that's true.

Then there is the issue at where to put it. I could ask myself, HOW many players, would toggle it off, and never toggle it on again? 🤔 But the toggle button will still show up there.

What if there's other things in the future, other than the IV-Scanner.

**Comment by Simplyfenton** [comment]
> Definitly it can not be that color. It is really hard to read that way. (But maybe its my red color deficency). There is not.enough contrast between the text and the Background

Yeah, I largely just picked the colour so that it'd be obvious that it's off, it's the same white as the rest of the text when the IV Scanner is enabled. Realistically, a dulled grey might work well, wasn't something I particularly looked into though.

**Comment by Simplyfenton** [comment]
Updated the toggled colour so that it now displays in Grey rather than Red, quite a bit more readable now.

Demo2

**Comment by CodeTappert** [comment]
> Updated the toggled colour so that it now displays in Grey rather than Red, quite a bit more readable now.
> 
> Demo2

Way better! :)

**Comment by Simplyfenton** [comment]
I _Believe_ this is following the new linting stuff, wasn't seeing anything wrong on my end as far as I could tell

**Comment by Simplyfenton** [comment]
Just bumping this for any potential feedback/thoughts

**Comment by Simplyfenton** [comment]
Resolved Conflicts in Phases.ts

**Comment by Simplyfenton** [comment]
Fixed linting issues that I evidently didn't fix previously

**Comment by flx-sta** [comment]
No action within more than a month. 
Considered stale.

Feel free to re-open it when you are still working on it/want to work on it again

**Pull request closed without merging**
