### PR TITLE
Update menu-ui-handler.ts [Localization(it)]

### PR DESCRIPTION
**Pull request by NicusPulcis**
## What are the changes?
A couple of translations regarding the menu have been slightly modified to be more "italian".

## Why am I doing these changes?
So that the menu is translated properly.

### Screenshots/Videos
Screenshot 2024-06-16 12 18 51

## How to test the changes?
Open the menu after setting the game on italian.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by bennybroseph** [comment]
what's up with the capitalization here?

**Comment by NicusPulcis** [comment]
@bennybroseph didn't make much sense to me, i can get it back if it's better tho

**Review by Tempo-anon — DISMISSED** [review]

**Review by EnochG1 — APPROVED** [review]

**Comment by EnochG1** [comment]
@Tempo-anon 
This PR is what you approved before.
I and Nicus resolved conflict so ready to be merged.

**Review by Tempo-anon — APPROVED** [review]
Approved by the wiki/tl team

**Pull request merged**
