### PR TITLE
[Bug] Dragon Tail now properly respects abilities like Suction Cups

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
Moves like Dragon Tail now more accurately respect abilities like Suction Cups.

## Why am I making these changes?
Came across a bug in unrelated testing and ran into this massive bunch of 🍝.

## What are the changes from a developer perspective?
Moves with `ForceSwitchOutAttr` properly parse the target's abilities to see if they should switch out the target.
Additional tests added for Dragon Tail.
Also fixed the indentation while I was here.

## How to test the changes?
`npm run test dragon_tail`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- ~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

### CODE REVIEW

**Comment by DayKev** [comment]
Btw you can use https://github.com/pagefaultgames/pokerogue/pull/4252/files?diff=unified&w=1 to have GitHub show the diff while ignoring whitespace-only changes.

**Review by flx-sta — APPROVED** [review]
lgtm

**Comment by innerthunder** [comment]
There's some overlap with #4382 here, as that includes a major rewrite of `ForceSwitchOutAttr`

**Comment by DayKev** [comment]
The only change you made to `ForceSwitchOutAttr` was to change the second param (and remove the promise, I left that alone because I didn't know the reason for it).

**Review by innerthunder — APPROVED** [review]

**Pull request merged**
