### PR TITLE
[Enhancement] Slightly improve the challenge selection UI, achievement UI, and achievement message window.

### PR DESCRIPTION
**Pull request by KimJeongSun**
## What are the changes the user will see?

challenge selection UI
- Adjust the size of the description window to be appropriate.
- Reduce the font size of the description from `96`px to `84`px.
- Center-align the start button label.

achievement UI
- Add font size options per language for achievement titles. For DE: `80`px
  - if you want to change your language font size of challenge description, let me know!
- Center-align the achievement title label.

achievement message window
- Increase the width of the basic achievement message window from `160` to `200`.

## Why am I making these changes?

During the update for working on the inverse battle challenge #3525 , these issues were found, necessitating the updates.

### Screenshots/Videos

- challenge select UI - before 
Screenshot 2024-08-25 at 1 42 51 AM

- challenge select UI - after
Screenshot 2024-08-25 at 1 47 52 AM

- achievement UI - before
Screenshot 2024-08-25 at 1 42 24 AM

- achievement UI - after
Screenshot 2024-08-25 at 1 48 33 AM

- achievement message window - before
Screenshot 2024-08-25 at 1 45 42 AM

- achievement message window - after
Screenshot 2024-08-25 at 1 47 26 AM

## example
- en
Screenshot 2024-08-25 at 2 33 26 AM

- es
Screenshot 2024-08-25 at 2 34 20 AM

- it
Screenshot 2024-08-25 at 2 36 35 AM

- fr
Screenshot 2024-08-25 at 2 37 12 AM

- pt_BR
Screenshot 2024-08-25 at 2 37 55 AM

- zh_CN
Screenshot 2024-08-25 at 2 38 51 AM

- zh_TW
Screenshot 2024-08-25 at 2 39 28 AM

- ko
Screenshot 2024-08-25 at 2 39 57 AM

- jp
Screenshot 2024-08-25 at 2 41 02 AM

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I add placeholders for them in locales?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Xavion3** [comment]
Should these be German exclusive? We should probably poll the rest of the language translation teams and see if they want font size changes done too.

And does the smaller selection options for challenges impact them negatively in any language? What are our longest text strings across every language and every challenge for a challenge mode?

**Comment by KimJeongSun** [comment]
> Should these be German exclusive? We should probably poll the rest of the language translation teams and see if they want font size changes done too.
> 
> And does the smaller selection options for challenges impact them negatively in any language? What are our longest text strings across every language and every challenge for a challenge mode?

I'll ask. Of course, if we proceed with the update, we'll probably need screenshots for all languages. (Please wait a moment.)
When I tested in all languages last time, there weren't any issues with options being hidden or the spacing being too small. Anyway, we can show these while we do the work above.

**Comment by Xavion3** [comment]
By longest text I meant for example, Fighting in english. What is the longest challenge value text in any language? Because that's what we need to look at to figure out if it fits.

**Comment by KimJeongSun** [comment]
> By longest text I meant for example, Fighting in english. What is the longest challenge value text in any language? Because that's what we need to look at to figure out if it fits.

in challenge option, Desactivado in ES

**Review by CodeTappert — APPROVED** [review]

**Review by DayKev — APPROVED** [review]

**Review by frutescens — APPROVED** [review]

**Pull request merged**
