### PR TITLE
Issue #1282: Fixed some Pokemon names in zh_TW

### PR DESCRIPTION
**Pull request by zjl88858**
https://github.com/pagefaultgames/pokerogue/issues/1282
Fixed typo and restore sensitive words (sinse SW&SH) to their original words.

### CODE REVIEW

**Review by Greenlamp2 — APPROVED** [review]
i trust you on this one :D

**Comment by zjl88858** [comment]
> i trust you on this one :D

Thx.
https://wiki.52poke.com/zh-hant/%E5%AE%9D%E5%8F%AF%E6%A2%A6%E5%88%97%E8%A1%A8%EF%BC%88%E6%8C%89%E5%85%A8%E5%9B%BD%E5%9B%BE%E9%89%B4%E7%BC%96%E5%8F%B7%EF%BC%89/%E7%AE%80%E5%8D%95%E7%89%88
I modified it against this public wiki. This wiki is very famous and credible among Chinese players.

**Review by TempsRay — APPROVED** [review]
Please change the title to be more descriptive. "Fixed some Pokemon names in zh_TW"

**Comment by zjl88858** [comment]
> Please change the title to be more descriptive. "Fixed some Pokemon names in zh_TW"

Done. THX.

**Review by Madmadness65 — APPROVED** [review]

**Pull request merged**
