### PR TITLE
[Bug] Female variant Rhyhorn line missing .json palette 

### PR DESCRIPTION
**Pull request by chaosgrimmon**
## What are the changes?
When variant palettes (rare and epic shiny colours) were added for Rhyhorn's line (Rhyhorn: 111, Rhydon: 112, Rhyperior: 464), the female variants were not implemented. This PR adds them into the game, so that it doesn't default all female shinys to the basic common shiny.

## Why am I doing these changes?
The changes allows the game to map the right colours onto the right shiny levels.

## What did change?
Previously, the necessary .jsons were missing, so they are added here. Each of the three Pokemon have a palette for their front and back. They do not have exp animations, so only two .jsons were needed, making six total.
_masterlist.json, which tells the game which variants are in the game, has also been updated, since those palettes do now in fact exist.

### Screenshots/Videos
Before:
image
image
After:
image
image
image

## How to test the changes?
Female variants will show up as the right colour wherever their front or back sprites would be present.
Use of overrides.ts made this significantly likelier than would have otherwise occurred.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by flx-sta** [comment]
@chaosgrimmon would you mind sharing your overrides and/or a session export.
Makes testing much much easier

**Comment by chaosgrimmon** [comment]
github doesn't seem to support uploading session data. do you have a discord handle?
otherwise the way i did it was setting opponent overrides.
 - export const OPP_SPECIES_OVERRIDE: Species | integer = 464; // either the pokedex number or Species.RHYPERIOR works
 - export const OPP_GENDER_OVERRIDE: Gender = Gender.FEMALE; // not *necessary*, default 0 to test both genders
 - export const OPP_SHINY_OVERRIDE: boolean = true; // required for shinies
 - export const OPP_VARIANT_OVERRIDE: Variant = 1; // 1 for rare, 2 for epic, 0 for common if shiny true

**Comment by flx-sta** [comment]
Just upload it on discord and post the link here l. But the override should be good too

**Comment by chaosgrimmon** [comment]
image
chat i messed up

**Comment by flx-sta** [comment]
> [image]chat i messed up

No reason to close. You can force push the branch to reset it and push all the changes a-new into it in a clean way

**Comment by chaosgrimmon** [comment]
i mean, sure, maybe, but the bigger concern is that it's going to *keep* happening because—
> [chaosgrimmon](https://github.com/chaosgrimmon) wants to merge 12 commits into [pagefaultgames:main](https://github.com/pagefaultgames/pokerogue/tree/main) from [chaosgrimmon:main](https://github.com/chaosgrimmon/pokerogue/tree/main)

—i obviously wasn't merging from the isolated branch made specifically for this set of changes

**Comment by flx-sta** [comment]
@chaosgrimmon just extract your changes manually, reset the branch (or create a new one with new PR) and off you go. I think you are overthinking it.

**Comment by chaosgrimmon** [comment]
>(or create a new one with new PR)

right, see i thought that i *did* do that (technically i used the branch that i had already made and was supposed to use, but still...)
is there some distinction that i'm missing/didn't do?

**Comment by flx-sta** [comment]
- Did you sync you main branch with the upstream before ? 
- Does it say your main branch is “behind” or “ahead” ?
- after syncing make sure to pull those changes into your local clone (on main)
- branch off that branch

**Pull request closed without merging**
