### PR TITLE
fix Roar

### PR DESCRIPTION
**Pull request by cywk99**
## What are the changes?

Prevent enemy from using ROAR on ally. 
Fix the sprite render bug after enemy use ROAR.

## Why am I doing these changes?

#1614 

## What did change?

In moves.ts, for the ROAR move, removed `.hidesTarget()` and added `.target(MoveTarget.ALL_ENEMIES)`
### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/60039008/ace3269f-b5bc-4b20-bd49-e8a92b69b14e

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by cywk99** [comment]
Hi @Tempo-anon Can I have someone review this PR? Thanks!

**Comment by EvasiveAce** [comment]
I've been working on Roar, and the `hidesTarget()` is not the issue. As you can see in your video, as well as the one I am going to post, Roar moves the pokemon out, but after the animation, you can briefly see it return to the middle. I think this is entirely from `Roar.json` breaking `hidesTarget()`

As for `.target(Movetarget.ALL_ENEMIES)` I was under the impression that it would hit both, but it seems that is not the case with your video. If that works as a single targeting move, then it's fine.

Easier to see animation flash after Roar (OBS would not pick it up, seems to be a frame broken?):

[Video](https://github.com/pagefaultgames/pokerogue/assets/71776311/f4cdf040-8985-42da-92d1-75b1d94d1e4c)

**Comment by cywk99** [comment]
Hi @EvasiveAce 

Not really sure about `hideTarget()`, but by removing it, roar seems to work fine?

I believe roar should be a single target move, and yeah I have updated to `.target(MoveTarget.NEAR_ENEMY)` , it makes the `multiple` variable false and the player's pokemon are able to select a single enemy as roar target now.

**Comment by Tempo-anon** [comment]
Going to close this since this changes the functionality of roar while it looks like there are still some issues with it

**Pull request closed without merging**
