### PR TITLE
[Bug] Clicking Right from Lock Rarities moves to transfer or check team

### PR DESCRIPTION
**Pull request by ifzeroequalsone**
## What are the changes?
Clicking Right from Lock Rarities currently doesn't move the cursor. This should fix that and move it to Transfer or Check Team

## Why am I doing these changes?
I got annoyed having to go up and to the right. And I'm guessing I'm not the only one.

## What did change?
Mapping of navigation from cursor state 3

## Checklist
- [ X] There is no overlap with another PR?
- [X ] The PR is self-contained and cannot be split into smaller PRs?
- [X ] Have I provided a clear explanation of the changes?
- [ X] Have I tested the changes (manually)?
    - [X ] Are all unit tests still passing? (`npm run test`)
- [ X] Are the changes visual?
  - [ X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by bennybroseph** [comment]
what's preventing this from being tested and tests passing?

**Comment by ifzeroequalsone** [comment]
Tests are passing 👍 

https://github.com/pagefaultgames/pokerogue/assets/2279696/a40d9419-c636-45b0-9a9e-11e86cfabdcd

@bennybroseph

**Comment by bennybroseph** [comment]
how about when you don't have a Lock Capsule

**Comment by ifzeroequalsone** [comment]
> how about when you don't have a Lock Capsule


https://github.com/pagefaultgames/pokerogue/assets/2279696/e49606cf-ebdb-4566-870c-0f40d1c83ad6

**Comment by Opaque02** [comment]
Out of curiosity, how would we feel about it if, when moving from the check team/transfer button, if you have a lock capsule it went to that instead of back to "Reroll"?

**Review by KimJeongSun — APPROVED** [review]
LGTM! ( and i want it )

**Comment by KimJeongSun** [comment]
> Out of curiosity, how would we feel about it if, when moving from the check team/transfer button, if you have a lock capsule it went to that instead of back to "Reroll"?

if you want it and other reviewers are prefer that way, then i will make PR for that in next

**Review by DayKev — APPROVED** [review]

**Comment by DayKev** [comment]
> Out of curiosity, how would we feel about it if, when moving from the check team/transfer button, if you have a lock capsule it went to that instead of back to "Reroll"?

On one hand, that makes more sense because they're on the same line. On the other hand, is that more useful?
Arguably it should go back to whichever you came from, but that's more effort lol.

**Comment by ifzeroequalsone** [comment]
@DayKev @KimJeongSun y'all know one more that can approve this so we can ship it out?

**Review by flx-sta — APPROVED** [review]
lgtm!
To make it feel more natural I've also made sure to move the cursor onto `Lock rarities` when moving to the left

https://github.com/user-attachments/assets/1d61a28a-a071-4fa0-97e4-75cba8f48136


https://github.com/user-attachments/assets/965e5d47-1e71-4e77-8ad4-cbc4004ff6f1

**Comment by DayKev** [comment]
> I have to say I got a heart attack seeing the leader-board on the left again when play-testing... over 800 commits behind yet no conflicts. Amazing

It helps when you barely changed anything lmao.

**Review by DayKev — APPROVED** [review]

**Pull request merged**
