### PR TITLE
[Beta][QoL] Run History Feature

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes?
Please see this PR for more details : https://github.com/pagefaultgames/pokerogue/pull/1815
Server-Side Code here: https://github.com/pagefaultgames/rogueserver/pull/33  

image

### CODE REVIEW

**Comment by EnochG1** [comment]
Could you please add config and locale files for other languages, too?

**Comment by shuqi0516** [comment]
[bug]Error in image display and feature display of Fusion Pok é mon after victory

**Comment by shuqi0516** [comment]
Screenshot_2024-07-05-09-30-49-513_com pokeroguecs helloworld

**Comment by shuqi0516** [comment]
![1]

**Comment by frutescens** [comment]
Hi, shuuqi - could you send me your game data?
manage data > export data 

I do not understand Chinese. What is the issue with the red circles? thank you.

**Comment by shuqi0516** [comment]
I'm sorry, the software I used for translation may result in inaccurate expression
Screenshot_2024-07-07-09-17-52-260_com pokeroguecs helloworld

The Ability of Trecate Fusion Raticate should be to escape, but what is displayed here is natural Cure
IMG_20240707_091912

**Comment by frutescens** [comment]
I realized what was going on - didn't know that fusion species had their own ability index somewhere else. Thank you! It should be fixed.

**Comment by shuqi0516** [comment]
You're welcome, I really like this feature and hope it becomes perfect



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 7, 2024 09:24 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pagefaultgames/pokerogue] [Beta][QoL] Run History Feature (PR#2823)




 
I realized what was going on - didn't know that fusion species had their own ability index somewhere else. Thank you! It should be fixed.

**Pull request closed without merging**
