### PR TITLE
[BUG] Fix Tidy-Up boosting stats multiple times right now

### LINKED ISSUE #2629: [BUG] "Tidy Up" stat raise is influenced by saving & loading sessions
## Describe the bug

The power of `Tidy Up` can exponentially increase by using it, saving the session, loading the same sesion and using it again. Basically leading to a `+6 +6` boost on a single use.
*Quite the buff...*

## To Reproduce

1. Start a New Game with [Furfrou](https://bulbapedia.bulbagarden.net/wiki/Furfrou_(Pok%C3%A9mon))
    - 
2. Use [Tidy Up](https://bulbapedia.bulbagarden.net/wiki/Tidy_Up_(move)) and check the stats (e.g. by pressing `Shift`)
3. Open the Menu (`Esc`) and select `Save & Quit`
5. Load Session (same one as before)
6. Use [Tidy Up](https://bulbapedia.bulbagarden.net/wiki/Tidy_Up_(move)) again -> `+4 | +4`
7. Rinse and repeat as much as you like.

I think the max is `+6 | +6` on a single use

## Expected behavior

It shouldn't do that. It should be consistent in it's stat boost

### Screenshots / Videos

https://github.com/pagefaultgames/pokerogue/assets/50131232/42c34e2d-3023-44c1-9d41-d6aab7d6f1d9

---

**Device**

All of them

**Additional context**

- [Discord Thread](https://discord.com/channels/1125469663833370665/1255630955935305748)
- [reddit post 01](https://www.reddit.com/r/pokerogue/comments/1dpf7c9/tidy_up_gives_my_bunnelby_6_atkspd_after_one_proc/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

### PR DESCRIPTION
**Pull request by flx-sta**
## What are the changes?

Tidy up is broken right now.
This should close #2629.
Eventually close #2649 since either of these PRs are a duplicate

## Why am I doing these changes?

Tidy up is being applied to both sides due to the arena-trap clearing but it's also boosting the stats more times then necessary making it extremely strong right now

## What did change?

I've added a condition to the `StatusChangeAttr` to only apply when `user.id === target.id` (since the target is the enemy pkm on the second apply)

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/50131232/af54beb5-83fe-4267-ab82-2e93d809b3d1

### Overrides Used

```ts
export const MOVESET_OVERRIDE: Array<Moves> = [ Moves.STEALTH_ROCK, Moves.TOXIC_SPIKES, Moves.DRAGON_DANCE, Moves.TIDY_UP ];
```
```ts
export const OPP_SPECIES_OVERRIDE: Species | integer = Species.MAGIKARP;
```
```ts
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [Moves.STEALTH_ROCK, Moves.TOXIC_SPIKES, Moves.SPIKES];
```

- Start a new game
- Set up some arena traps (enemy should be doing the same)
- Press `V` to check the traps
- Use `Tidy Up`
- All arena traps should be cleared and the stats should be +1 ATK +1 SPD
- Use `Tidy Up` again
- +2 ATK +2 SPD 
- and so on

no more +6 ATK +6 SPD on the 2nd use already (hopefully)

## Checklist
- [ ] There is no overlap with another PR?
   -  There is #2649. But it's the wrong approach unfortunately
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- ~~[ ] Are the changes visual?~~
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by DayKev** [comment]
I created tests for Tidy Up (using this PR as a base). Do you want to add them to this PR or should I make a separate PR for it once this is merged?

https://github.com/DayKev/pokerogue/tree/tidy-up-tests

**Review by Tempo-anon — APPROVED** [review]

**Comment by flx-sta** [comment]
> The MoveTarget.BOTH_SIDES isn't the relevant code that cleans the trap from both sides. That's in the ctor of the Arena Trap attribute which accepts a bool param. Defog uses this param to do the same effect and does not use MoveTarget.BOTH_SIDES. Either there wasn't anything wrong with my pr's approach or there's something wrong with how Defog is implemented.

Good to know. Yeah one of them must be wrong then... We should create a follow up issue for that

**Comment by flx-sta** [comment]
@Nohbody well you caught me. I was blind:
```ts
export class RemoveArenaTrapAttr extends MoveEffectAttr {

  private targetBothSides: boolean;

  constructor(targetBothSides: boolean = false) {
    super(true, MoveEffectTrigger.PRE_APPLY);
    this.targetBothSides = targetBothSides;
  }
  //...
}
```

**Comment by flx-sta** [comment]
> I created tests for Tidy Up (using this PR as a base). Do you want to add them to this PR or should I make a separate PR for it once this is merged?
> 
> https://github.com/DayKev/pokerogue/tree/tidy-up-tests

You will need to create a PR

**Pull request merged**
