### PR TITLE
[Move] Implement Lunar Dance

### PR DESCRIPTION
**Pull request by PrabbyDD**
## What are the changes the user will see?
Lunar Dance works as intended

## Why am I making these changes?
build da game

## What are the changes from a developer perspective?
Added variable and some code that allows similar move attr to healing wish to also allow restore of PP 

## Screenshots/Videos

Pokemon has its status, hp and pp returned

https://github.com/user-attachments/assets/2b7da390-f088-4d3e-be9a-0d363eac54d5

No more pokemon in party

https://github.com/user-attachments/assets/ae08d9b0-95cf-4e5f-bd40-11271c382e7f

## How to test the changes?
override and future unit tests

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [x] Have I made sure that any UI change works for both UI themes (default and legacy)?

Are there any localization additions or changes? If so:
- [ ] Has a locales PR been created on the [locales](https://github.com/pagefaultgames/pokerogue-locales) repo?
  - [ ] If so, please leave a link to it here: 
- [ ] Has the translation team been contacted for proofreading/translation?

### CODE REVIEW

**Comment by PrabbyDD** [comment]
For some reason I cant add the change I made in public/locales/en/move-trigger.json - I added a message that is the same in the base games for when lunar dance triggers.

**Comment by PrabbyDD** [comment]
ahh i see its a submodule, so I am not sure what to do then - do I need to contact localization team to have them add the message?

**Comment by PrabbyDD** [comment]
It was just this in public/locales/en/move-trigger.json 

"lunarDanceRestore" : "{{pokemonName}}'s became cloaked in mystical moonlight!",

**Review by DayKev — COMMENTED** [review]
Made some suggestions here https://github.com/PrabbyDD/pokerogue/pull/2

**Comment by DayKev** [comment]
> It was just this in public/locales/en/move-trigger.json
> 
> "lunarDanceRestore" : "{{pokemonName}}'s became cloaked in mystical moonlight!",

Locales PR created/merged. 👍

**Comment by PrabbyDD** [comment]
Should be ready for merge now

**Review by Madmadness65 — APPROVED** [review]

**Pull request merged**
