### PR TITLE
Issue-503: Explosions target all to self-ko

### PR DESCRIPTION
**Pull request by ArminOsvath**
Fix for: https://github.com/pagefaultgames/pokerogue/issues/503 

Don't know the ramifications of them hitting ALL vs ALL_NEAR_OTHERS

Changed: Explosion, selfdistruct and misty explosion

### CODE REVIEW

**Comment by Flashfyre** [comment]
This isn't a proper solution. Self-KO always hits your full HP. This will just hit for high damage, which won't necessarily work.

**Comment by ArminOsvath** [comment]
@Flashfyre I see, i thought that if you hit yourself, then you'd still die because it'll take effect. Which still happens even if you use gengar or steelix at level 100000

**Comment by Flashfyre** [comment]
If this damage isn't responsible for the faint, why do we need it to target yourself then?

**Comment by bennybroseph** [comment]
Closing this out based on the above conversation.

**Pull request closed without merging**
