### PR TITLE
[Bug] Make EXP boosting items stack additively and not multiplicatively

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes?
EXP boosting items are changed to stack additively instead of multiplicatively.

## Why am I doing these changes?
#2040

## What did change?
The modifier increments a `modifierBonusExp` variable instead of acting on the gained EXP variable directly, and then after all the bonus modifiers are added to the bonus multiplier variable it's applied to the gained EXP.

## How to test the changes?
`npm run test exp_booster`
Alternatively, defeat a lv5 Gyarados with a lv5 Mewtwo that's holding 1 Lucky Egg and 1 Golden Egg and observe the gained EXP being 456 (2.4x) and not 532 (2.8x) as it is now on main.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

### CODE REVIEW

**Comment by Tempo-anon** [comment]
Gonna wait to see if this is a bug or a feature

**Comment by Tempo-anon** [comment]
Let's test this in beta

**Comment by star-krieg** [comment]
Changing how EXP boosting items work would great impact the level progression in Endless. Compared here is the same save across the live and beta versions:

50 exp charms (25%), 17 super exp charms (60%), 14 golden egg (100%), 85 lucky eggs (40%)

Live version: 
image
Beta version:
image

EXP in live goes from 3 billion EXP and drops to 300 million EXP in beta for the same loadout.

Difference in levels become noticeable even just from doing a few waves.
image

Lowered EXP because of this change would probably even more compounded for a longer run (I've only checked for difference for a few waves)
Live:
image
Beta:
image

**Comment by damocleas** [comment]
I'm going to list my thoughts in the order I had them
- This needs to be tested
- IF this is a bug, it is a pretty major one (likely is, but no one has noticed/didn't affect much having it, removing it affects more)
- Testing current runs just for a few waves won't work as well with how it's designed

I'm going to try to get decently far into an endless run with this on and see if it affects anything major, average classic run shouldn't have affected, but I'd rather be safe than sorry and test that as well since this would affect both modes and you're given exp charms automatically.

**Comment by DayKev** [comment]
If it turns out to be a problem in endless then waiting to revisit the issue until the endless rework seems fine.

> I'm going to try to get decently far into an endless run with this on and see if it affects anything major, average classic run shouldn't have affected, but I'd rather be safe than sorry and test that as well since this would affect both modes and you're given exp charms automatically.

It should only change the behavior of specifically the interaction of stacking Lucky Eggs and Golden Eggs together on the same pokemon, the EXP Charm items use a different modifier class that I didn't touch.

**Pull request merged**
