### PR TITLE
Add Form Text to Starter UI

### PR DESCRIPTION
**Pull request by bennybroseph**
Adds text to the starter screen UI which indicates which Form you are currently selecting. This helps with Pokémon who don't have a sprite change for their form because it doesn't affect them until later.

https://github.com/pagefaultgames/pokerogue/assets/13838608/6c87c9dd-6ef5-4e60-bfe6-18d88f68c685

### CODE REVIEW

**Comment by Flashfyre** [comment]
The all-caps aesthetic doesn't work with this game I'm afraid. Can we do normal title casing?

**Comment by bennybroseph** [comment]
Yeah, gimmie a bit will have to code something for it since there's no easy function like the others

**Comment by bennybroseph** [comment]
Updated:

https://github.com/pagefaultgames/pokerogue/assets/13838608/10bb0fe6-f469-44ed-9f93-e2686aca138e

**Review by Flashfyre — APPROVED** [review]

**Comment by bennybroseph** [comment]
Fixes https://github.com/pagefaultgames/pokerogue/issues/444

**Pull request merged**
