### PR TITLE
Implemented "Forest's Curse"

### PR DESCRIPTION
**Pull request by AFGRocha**
Implemented "Forest's Curse".

The opposing Pokémon gets the additional Grass Type.

This currently doesn't update the UI next to the health that displays types.

### CODE REVIEW

**Review by molker — CHANGES_REQUESTED** [review]
please sync with recent changes to main 
move.ts format changed a bit

**Comment by AFGRocha** [comment]
> please sync with recent changes to main move.ts format changed a bit

Done

**Comment by Xavion3** [comment]
So, this lacks some quirks with trick or treat but those are actually quite complicated. That said this could also stand to be a bit more generic so it can support any type and thus work with trick or treat too, but I'm also just doing that myself currently as I'm tackling soak and these came up.

**Comment by Flashfyre** [comment]
Implemented in another PR

**Pull request closed without merging**
