### PR TITLE
Implement starters overrides

### PR DESCRIPTION
**Pull request by Kiriox94**
## What are the changes?
Addition of 3 new overrides to manage available starters

## Why am I doing these changes?
I'm currently working on the localization of pokemon forms, so I've added these overrides to make it easier to check that the form name is displayed in the starters menu.

## How to test the changes?
Go to `src/overrides.ts` and change `STARTERS_OVERRIDE` or `STARTERS_FORMS_OVERRIDE` or `STARTERS_ALL_FORMS_OVERRIDE` to `true`.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

### CODE REVIEW

**Review by Tempo-anon — CHANGES_REQUESTED** [review]
I don't know about this. This seems pretty dangerous to include as an override. Wouldn't it be better just to have a full psrv save file to be used for debugging? 

Also linter fails.

**Comment by Kiriox94** [comment]
> I don't know about this. This seems pretty dangerous to include as an override. Wouldn't it be better just to have a full psrv save > file to be used for debugging?
>Also linter fails.

I don't see what's more dangerous in this than in the other overrides. If you're worried that it won't be deactivated before a pull request, you should know that `overrides.ts` is in .gitignore, so there's no risk there.

**Comment by bennybroseph** [comment]
> > I don't know about this. This seems pretty dangerous to include as an override. Wouldn't it be better just to have a full psrv save > file to be used for debugging?
> > Also linter fails.
> 
> I don't see what's more dangerous in this than in the other overrides. If you're worried that it won't be deactivated before a pull request, you should know that `overrides.ts` is in .gitignore, so there's no risk there.

Unfortunately that's not how .gitignore works

**Comment by bennybroseph** [comment]
I'm with Temp, this is way too dangerous. If somebody is not paying attention and merges this it completely corrupts every single user in the DB's save file irreversibly. We need some better debugging tools tbh. This is just asking for trouble.

**Comment by Kiriox94** [comment]
> I'm with Temp, this is way too dangerous. If somebody is not paying attention and merges this it completely corrupts every single user in the DB's save file irreversibly. We need some better debugging tools tbh. This is just asking for trouble.

I don't understand how my code can corrupt saves or database since my code doesn't touch it, it just falsifies the conditions of `starters-ui-handler.ts`

**Comment by Kiriox94** [comment]
> > > I don't know about this. This seems pretty dangerous to include as an override. Wouldn't it be better just to have a full psrv save > file to be used for debugging?
> > > Also linter fails.
> > 
> > I don't see what's more dangerous in this than in the other overrides. If you're worried that it won't be deactivated before a pull request, you should know that `overrides.ts` is in .gitignore, so there's no risk there.
> 
> Unfortunately that's not how .gitignoreHowever, it seemed to me that its operation was to make gît ignore the files that are in it, am I wrong?

**Pull request closed without merging**
