### PR TITLE
Spanish translations

### PR DESCRIPTION
**Pull request by nedpfeiffer**
This MR includes some Spanish translations for the IV Judge, berries, the menu UI, and types. If I goofed anything up please let me know, my Spanish is good but I'm not entirely fluent.

For reference I found the IV judge translations here: https://www.wikidex.net/wiki/Juez_de_genes

For the type translations I consulted Bulbapedia. I chose the Iberian Spanish translations, although it could make more sense to use the Latin American Spanish translations because their population and player base is way larger. Has the project decided on which dialect of Spanish it wants to adopt?

Thanks!

### CODE REVIEW

**Comment by CodeTappert** [comment]
Please add screenshots that proof that the next isnt too long

**Comment by nedpfeiffer** [comment]
> Please add screenshots that proof that the next isnt too long

Screenshot 2024-05-18 112300
Screenshot 2024-05-18 114726
Screenshot 2024-05-18 115634

**Comment by CodeTappert** [comment]
Looks good. Well not the IV thing... Cant you change the text to be at least one letter shorter somehow?

There should be a visible space

**Comment by nedpfeiffer** [comment]
Screenshot 2024-05-18 134005

Shortened the translation, it should look better now.

**Comment by CodeTappert** [comment]
Inmejorable is longer then Fantástico

Can you show a pokemon with Fantástico at velocidad?

**Comment by nedpfeiffer** [comment]
Screenshot 2024-05-18 135717

Let me know if that's enough space between the stat and the IV judgement.

**Comment by CodeTappert** [comment]
Yes that looks good enough!

**Review by bennybroseph — APPROVED** [review]

**Comment by nedpfeiffer** [comment]
Hi all, this PR has been approved and all checks have passed. There are no conflicts with the base branch. Could someone with write access please merge the changes at their earliest convenience?

Thank you!

**Pull request merged**
