### PR TITLE
Implemented Bug Bite, Pluck, Teatime

### PR DESCRIPTION
**Pull request by lucfd**
- Implemented Bug Bite, Pluck, Stuff Cheeks, and Teatime using two new move effect attributes:
  - `EatBerryAttr`: Makes the target eat a specified berry. If none is specified, a random berry is chosen from the ones the Pokemon is holding.
  - `StealEatBerryAttr`: Attempts to steal & eat a berry from the target of your attack.
- Stealing berries with `StealEatBerryAttr` (Pluck & Bug Bite) is blocked by `BlockItemTheftAbAttr` (Sticky Hold)
- Moves using these attributes are unaffected by Unnerve
- `EatBerryAttr` and `StealEatBerryAttr` benefit from Berry Pouch

### CODE REVIEW

**Review by bennybroseph — APPROVED** [review]

**Comment by bennybroseph** [comment]
UI doesn't seem to like the berry being taken in this way. Count goes to 0 and stays there.

https://github.com/pagefaultgames/pokerogue/assets/13838608/9b3dc60d-4632-4571-8732-edf593d4e97f

**Comment by lucfd** [comment]
Good catch, turns out this bug was specific to the opponent's side of the field. Fixed by adding a secondary argument to the `removeModifier()` calls to check for the correct list of modifiers.
https://github.com/pagefaultgames/pokerogue/assets/83493765/dc9121db-0347-4e7b-9fde-21d1e0c1d28a

**Comment by lucfd** [comment]
Added new logic to prevent leppa berries from throwing an error when you don't have a move with 0 PP. Now, if no move with 0 PP is found, leppa berries will try to restore PP to one of your other moves that is missing PP.

**Comment by bennybroseph** [comment]
Things that I tested that worked as written in bulbapedia

Teatime:
- Both pokemon eat a random berry
- Cannot eat a berry in a two turn move
- Able to eat a berry through Unnerve

Stuff Cheeks:
- Gain defense
- Eat a random berry
- Able to eat a berry through Unnerve

What didn't work?

Stuff Cheeks:
- Can still be selected if you don't have a berry.

Keep in mind that Stuff Cheeks should still fail if it's used but loses the berry mid turn for some reason, so that code should stay. Needs a new exception when trying to select it though similar to disabled moves since you struggle when it's your only option.

**Comment by lucfd** [comment]
Removed Stuff Cheeks as the necessary logic to prevent the move from being selected exceeds the scope of this PR. Will spin it off into a new PR later

**Review by bennybroseph — APPROVED** [review]

**Comment by OrangeRed** [comment]
> * Implemented Bug Bite, Pluck, Stuff Cheeks, and Teatime using two new move effect attributes:

@lucfd Has Stuff Cheeks been implemented, I still see it as `.unimplemented()` in `src/data/move.ts:6840`

I added the trigger for Cheek Pouch to `EatBerryAttr` in #987 since that ability was waiting for these moves to get implemented.

Also a sidenote are we sure we want to implement the berry steal moves with a 100% activation rate? 
I personally feel like that amount of item hate is a little too strong

**Pull request merged**
