### PR TITLE
Rework - Inputs management to include all gamepad mapping

### PR DESCRIPTION
**Pull request by Greenlamp2**
Rework of the input handling, to allow different gamepad.

It's food for @EmoUsedHM01 and @Flashfyre . I tried to do something readable and "clean" but i think it can be better.
Let me know if i did something wrong, this is my first PR here, and hopefully not the last one.

Based on a discussion we had on discord, for the context:
image
image
image

### CODE REVIEW

**Comment by Greenlamp2** [comment]
(it's also fixing the issue of the C/Shift not working anymore when a gamepad is used.)

**Review by Flashfyre — CHANGES_REQUESTED** [review]
Can we move all the buttons to an inputHandler class/object and change the button functions to use lowerCamelCase? I think that might be cleaner.

**Comment by Greenlamp2** [comment]
I've extracted all the input detection logic into an InputsController, but i've let the Ui logic based on inputs in the battle-scene.ts.
Would you like me to takle that out too ?

**Review by Flashfyre — COMMENTED** [review]
As much input logic as you can get in there, yeah. Too much is in battle-scene already.

**Comment by Greenlamp2** [comment]
For me, everything is okay, xbox controller, generic controller, keyboard and touch. Just need someone to test the dualschock controller.

**Pull request merged**
