### PR TITLE
feat: added italian translation for the biomes

### PR DESCRIPTION
**Pull request by SavGRY**
## What are the changes?
I saw that the biomes weren't localized in Italian, so here they are.  
Feel free to comment if you find a translation not accurate.

## Why am I doing these changes?
This PR aims to translate the selecatable biomes in Italian.
Also added some JSDoc to better identify and documenting the code.

### Screenshots/Videos
City:  
Screenshot from 2024-05-29 23-23-48  

Meadow:  
Screenshot from 2024-05-29 23-25-19  

Desert:  
Screenshot from 2024-05-29 23-25-47  

Power Plant:  
Screenshot from 2024-05-29 23-26-24

## How to test the changes?
Set the language in Italian and go through the gameplay, get a map and you can see the translations  

## Checklist
- [ ] There is no overlap with another PR?
  - #1573 
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

Author: SavGRY - @SavGRY

### CODE REVIEW

**Comment by flx-sta** [comment]
I'm curious how you bypassed the PR template.
Or did you just remove all the content that was given when creating it?

**Comment by SavGRY** [comment]
> I'm curious how you bypassed the PR template. Or did you just remove all the content that was given when creating it?

Yeah, i deleted it, but surely i can put it back. Sorry if it was mandatory, if needed i'll correct it

**Comment by flx-sta** [comment]
> > I'm curious how you bypassed the PR template. Or did you just remove all the content that was given when creating it?
> 
> Yeah, i deleted it, but surely i can put it back. Sorry if it was mandatory, if needed I'll correct it. Yup, just my fault

I'm not the police. Not even a (main) dev. I was just confused as it's there for a reason.

**Comment by Madmadness65** [comment]
Comparing this PR to #1573 , there seems to be a few biomes that got translated differently, just want to know which ones are more accurate location names.

**Comment by SavGRY** [comment]
> Comparing this PR to #1573 , there seems to be a few biomes that got translated differently, just want to know which ones are more accurate location names.

I'm gonna review it and I can give you my POV

**Pull request closed without merging**
