### PR TITLE
Drop Shadow Adjustments

### PR DESCRIPTION
**Pull request by zaccie**
Adding support for x,y axis on dropshadow and adjusting the values to be less bad
and renamed the constants to actually make sense

dropshadow

### CODE REVIEW

**Comment by bennybroseph** [comment]
I'm not convinced a blanket 3, 4 value for distance is correct. The defaults for each text style wasn't 6, 6 nor 4, 4. Some were closer than that. I'd need a unique value for each style and an accompanying screenshot for what the new text looks like vs. the old one.

**Comment by zaccie** [comment]
> I'm not convinced a blanket 3, 4 value for distance is correct. The defaults for each text style wasn't 6, 6 nor 4, 4. Some were closer than that. I'd need a unique value for each style and an accompanying screenshot for what the new text looks like vs. the old one.

Sure, the others were close enough I assumed it'd translate over well enough but I'll modify values for those specifics and compile some before/after images

**Comment by zaccie** [comment]
left old right new
any other examples (like moveinfo content) is the same as on main
RegularText
TooltipContent

**Comment by zaccie** [comment]
I haven't entirely convinced myself it's a meaningful change to be honest, but maybe others think its a much bigger improvement than I can see

**Review by bennybroseph — APPROVED** [review]

**Comment by TempsRay** [comment]
Some are a lot worse now.
Before:

After:

**Comment by zaccie** [comment]
> Some are a lot worse now. Before:  After: 

I didn't increase any numbers so this seems odd but I'll take a look and try fix it

**Comment by zaccie** [comment]
Made some changes to fix above here: https://github.com/pagefaultgames/pokerogue/pull/1220

**Pull request merged**
