### PR TITLE
Update Frisk description in most languages

### PR DESCRIPTION
**Pull request by jaimefd**
Changed the description of Frisk ability to reflect its new effect for Pokerogue, as mentioned by the issue https://github.com/pagefaultgames/pokerogue/issues/778

I changed all languages except Chinese since I don't really know it well, so if anyone can give me the translation I'll gladly add it to the PR.

I also kept the german one in english as the other abilities also seem to be in english.

### CODE REVIEW

**Comment by CodeTappert** [comment]
Hey if you want to add the actual german text. 

Here is the correct ability text:

```
Kann bei Kampfantritt Auskunft über das vom Gegner getragene Item geben.
```


and here the Ability Name:

````
Schnüffler
```

**Comment by CodeTappert** [comment]
The german abillitys are btw solved in another pr...We still waiting for a merge on that

**Review by CodeTappert — APPROVED** [review]

**Comment by CodeTappert** [comment]
Btw. this seems to be a duplicate of #784

**Comment by TempsRay** [comment]
The other PR is missing German while this one is missing Chinese

**Comment by happinyz** [comment]
> The other PR is missing German while this one is missing Chinese

German is implemented already: https://github.com/pagefaultgames/pokerogue/commit/7b7df5b245f8b3ac2bfef0b2c7f20210a772f165

**Comment by CodeTappert** [comment]
Since german is now in main anyways. And the other has chinese i would just close this one tbh

**Pull request closed without merging**
