### PR TITLE
Implemented barrier-breaking moves

### PR DESCRIPTION
**Pull request by lucfd**
- Created a new attribute `RemoveScreensAttr` that removes Reflect, Light Screen and Aurora Veil from the target's side of the field.
- Applied this attribute to Brick Break, Psychic Fangs and Raging Bull.
- Created new function `removeTagOnSide` in `arena.ts` as `removeTag` does not take sides into account.
- MoveEffectTrigger.PRE_APPLY doesn't seem to be working properly?

### CODE REVIEW

**Review by Flashfyre — CHANGES_REQUESTED** [review]
Remove (P) if the move is fully implemented

**Comment by Madmadness65** [comment]
Since it's within scope, Defog should also be clearing screens too.

**Comment by lucfd** [comment]
Removed (P) from the moves and updated `RemoveScreensAttr` to support clearing both sides of the field using an optional argument.

**Review by Madmadness65 — APPROVED** [review]
Seems to work correctly on my local game, so this LGTM.

**Review by Flashfyre — APPROVED** [review]

**Pull request merged**
