### PR TITLE
Partially Implemented Flower Veil & Finished Sweet Veil and Pastel Veil

### PR DESCRIPTION
**Pull request by Brandon-Rodgers**
- Blocks status conditions on self and allies that are grass type
- Blocks stat lowering by other Pokémon on self and allies that are grass type

There is some overlap with PR #753 for the ally implementation

### CODE REVIEW

**Comment by Brandon-Rodgers** [comment]
Merged changes from PR #753 to this since they both add the same classes and main changes to get ally checks included

**Comment by Brandon-Rodgers** [comment]
Flower Veil triggers 3 times for some reason. Please ignore PR for now.

**Comment by Brandon-Rodgers** [comment]
https://github.com/pagefaultgames/pokerogue/assets/9848614/7f5b2809-4bad-47c9-8103-3bf39337a998

Sing - Cottonee blocks themselves with Flower Veil
Growl - Cottonee blocks themselves with Flower Veil, Hoppip blocks themselves with Flower Veil
Yawn - Cottonee blocks themselves with Flower Veil
Skill Swap - Remove Flower Veil from Cottonee
Sing - Hoppip blocks Cottonee with Flower Veil
Growl - Hoppip blocks themselves and Cottonee with Flower Veil
Yawn - Hoppip blocks Cottonee with Flower Veil

**Comment by Tempo-anon** [comment]
Closing due to inactivity and merge conflicts. https://github.com/pagefaultgames/pokerogue/pull/2626 is a more recent implementation

**Pull request closed without merging**
