### PR TITLE
Type localization instead of TeraType

### PR DESCRIPTION
**Pull request by josericardo-fo**
Before:

image

After:

image

(I didn't translate the rest of the description to ptBR yet lol, but you get it)

Now the type name in the description is translated too. Changed TeraType to Type and where it was used since they are essentially the same.

### CODE REVIEW

**Comment by bennybroseph** [comment]
there's a ton of changes to imports in this. Why?

**Comment by bennybroseph** [comment]
Yeah, if we wanna update formatting we should do it in a separate commit. 

With that said though, these shouldn't be different than regular pokemon types. can we just update this so that it pulls from the regular pokemon types instead of creating a whole new section? i.e. delete the teratypes and update the function to grab types from our existing localization

**Comment by josericardo-fo** [comment]
I did this because I didn't find any "type" localization. Where is it?

**Comment by bennybroseph** [comment]
if not, let's put them in `pokemon-stat.ts` and rename the file to `pokemon-info.ts`

**Comment by josericardo-fo** [comment]
Sure. Working on that

**Comment by josericardo-fo** [comment]
Made the changes tou requested @bennybroseph

**Comment by bennybroseph** [comment]
Nice, final thing can we get some screenshots showing this was tested?

**Comment by josericardo-fo** [comment]
**Stats**
ptBR
image
en
image

**Types**
ptBR
image
en
image

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
