### PR TITLE
[Feature] Updates to shop phase to allow custom tier and item overrides

### PR DESCRIPTION
**Pull request by ben-lear**
## What are the changes?
Adds an optional parameter to SelectModifierPhase to allow for overriding randomly generated rewards.
There are 3 settings that can be passed: 
- `guaranteedModifierTiers`: When set, will generate a random item of a specific tier in the shop, guaranteed. These items can be upgraded by luck effects.
- `guaranteedModifiers`: When set, will always add the specified item to the shop. These items will not be upgraded by luck on the initial shop roll (but can be rerolled as normal later on).
- `fillRemaining`: When set, will fill all remaining item slots with random items as normal. Otherwise, only items specified by the above two options will appear in the shop.

## Why am I doing these changes?
Splitting these changes out from https://github.com/pagefaultgames/pokerogue/pull/1690 to keep the size of that PR down and because this functionality is useful for more than just Mystery Encounters.

## What did change?
Nothing is functionally changed at all with current shops, this is just an optional parameter.

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/110984302/0db2ff27-f189-4904-824d-044aaa1abf01

## How to test the changes?
- pull branch
- `npm run start:dev`
- modify the two instances where `new SelectModifierPhase()` is called and pass some custom settings (e.g. `new SelectModifierPhase(scene, 0, null, customShopRewards)`)
- Example objects you can pass:
testing to override standard item count in shop:
```
{
  guaranteedModifiers: [modifierTypes.MEMORY_MUSHROOM, modifierTypes.MEMORY_MUSHROOM, modifierTypes.MEMORY_MUSHROOM, modifierTypes.MEMORY_MUSHROOM, modifierTypes.MEMORY_MUSHROOM]
}
```
testing tier and item overrides together, without filling remaining:
```
{
  guaranteedModifiers: [modifierTypes.TM_COMMON],
  guaranteedModifierTiers: [ModifierTier.ULTRA]
}
```
testing fillRemaining with a single override:
```
{
  guaranteedModifierTiers: [ModifierTier.ULTRA],
  fillRemaining: true
}
```

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by ben-lear** [comment]
I split out `SelectModifierPhase` to its own file as part of this enhancement, which also required splitting out `BattlePhase` for circular dependency reasons. Other individual phase files were all moved into the `phases` directory for organizational purposes.

**Comment by ben-lear** [comment]
Video evidence that the game still compiles and runs without issue after the refactors:

https://github.com/pagefaultgames/pokerogue/assets/110984302/8dba1858-4ed3-477b-b3bc-9971739664ff

**Review by OrangeRed — COMMENTED** [review]
I think this PR isn't the place for moving phases around. Lets save that for its own PR and keep that open for discussion

**Comment by ben-lear** [comment]
> I think this PR isn't the place for moving phase files around. Lets save that for its own PR and keep that open for discussion

resolved

**Comment by OrangeRed** [comment]
Doesn't PR #2320 do the same thing as this PR when it comes to setting reward items?

**Comment by ben-lear** [comment]
> Doesn't PR #2320 do the same thing as this PR when it comes to setting reward items?

That is specifically for development overrides. This is a feature enhancement that exposes reward override logic to specific use cases, such as improved rewards from a boss battle, etc.

**Comment by ben-lear** [comment]
Closed, consolidating changes with other PR.

**Pull request closed without merging**
