### PR TITLE
QOL - added settings to set battle style, SHIFT or SET

### PR DESCRIPTION
**Pull request by Greenlamp2**
image

I've added a setting to let the player the opportunity to stop asking if he wants to change pokemon at the beginning of each fight, like in the legacy games.

chrome_xfTWtrXCTg

### CODE REVIEW

**Comment by Flashfyre** [comment]
Doesn't this make the game harder?

**Comment by Greenlamp2** [comment]
The shift battle style is the exact same behaviour as today on prod.
The set option is just to disable the prompt like on a battle fight.
And yes, it may be harder on a classic playthrough if the battle style is on Set, but it's the choice of the player, and he can change it at any time.

It's mostly a QOS for endless when we don't swap pokemon that many time, in the contrary, we always end up spamming A, then by accident we chose to change pokemon, only to press B to cancel.

**Comment by MonsieurDMA** [comment]
Wouldn't it be better to set the action of pokemon swap as the first action of a combat a "free" move ?

**Comment by Flashfyre** [comment]
> Wouldn't it be better to set the action of pokemon swap as the first action of a combat a "free" move ?

Yes, I think this would remove any increase of difficulty while increasing the convenience. I think once you switch on one party member in a double battle, you either have to also switch the other one or somehow skip that turn. I'm not sure how this would look, because if you take a fight action with the second one it would count as a normal switch, but there is no way to just skip.

**Comment by Greenlamp2** [comment]
ok, here is my idea on how to implement this.
- at the first turn, i put an indicator near the "pokemon" menu to tell it's a free switch.
- if he did not use his free switch and choose to attack, use an item, or flee, his free switch is lost.

On double battle:
- Still on the first turn, still an indicator to tell there is a free switch.
- if he uses it on the first pokemon, he is forced to choose on the second pokemon if he want to switch or not.
- if he attacks, use an item or flee, the free switch is lost.

**Comment by Greenlamp2** [comment]
Something like that (Not set in stone, just an idea):
image

**Comment by Greenlamp2** [comment]
Something like that (Not set in stone, just a proposal)
image

**Comment by Greenlamp2** [comment]
I've found an issue with the "free switch": how do we manage ability like intimidate...

**Comment by Greenlamp2** [comment]
I've reverted everything to the initial proprosal. if @Flashfyre  you do not like the idea of "Set" and "Shift", you can close the PR without any issues 👍

**Comment by MonsieurDMA** [comment]
> I've found an issue with the "free switch": how do we manage ability like intimidate...

Right now, when does these abilities trigger ? After we switch pokemon or say no to the free pokemon switch, right ?
If so, maybe we can just trigger it when we disable the freeswitch because of an action

**Comment by Greenlamp2** [comment]
the ability is trigerred once we answered yes/no to switch pokemon.

with the wanted implementation, if we trigger it when an action is done, it could be messy because the action can be an attack, so, for example, we select an attack, and for some reason, your ability is triggered then your attack is shown.
It's not good.

And how to manage pokemon switch from trainer ? in a normal situation, you say no to switch pokemon, your ability is triggered, than you attack, but the trainer change his pokemon, your attack is on his new pokemon.

with the "free switch", it would look like: attack - ability triggered - trainer switch - his ability trigger on your pokemon your ability re-triggered on the new pokemon - attack on the new pokemon.

I really think it would be messy, and it's reinventing a new battle system and inducing a lot of bug and issues, because you'll have to manage attack like Outrage and many others.

**Comment by bennybroseph** [comment]
Closing this due to inactivity. Feel free to make a new request if interest is reignited

**Pull request closed without merging**
