### PR TITLE
[Test] Temporarily disable broken ME test

### PR DESCRIPTION
**Pull request by DayKev**
## What are the changes the user will see?
N/A

## Why am I making these changes?
The test is broken.

## What are the changes from a developer perspective?
Disable the broken test for now.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- ~[ ] Have I considered writing automated tests for the issue?~
- ~[ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- ~[ ] Are the changes visual?~
  - ~[ ] Have I provided screenshots/videos of the changes?~

### CODE REVIEW

**Review by torranx — APPROVED** [review]

**Comment by PigeonBar** [comment]
Personally, I would prefer to not disable the test and to instead find a different workaround. For example, I think it is possible to mock the Soothe Bell's item tier:

      // Workaround to Soothe Bell being treated as a Great tier item due to the event
      const originalSootheBell = modifierTypes.SOOTHE_BELL;
      vi.spyOn(modifierTypes, "SOOTHE_BELL").mockImplementation(() => {
        const newSootheBell = originalSootheBell();
        newSootheBell.withTierFromPool = (poolType) => {
          newSootheBell.tier = ModifierTier.ROGUE;
          return newSootheBell;
        }
        return newSootheBell;
      })

**Comment by innerthunder** [comment]
#4775 overlaps with this (and seems to be the better solution imo)

**Comment by DayKev** [comment]
Superseded by #4775

**Comment by DayKev** [comment]
> #4775 overlaps with this (and seems to be the better solution imo)

Yeah this was just supposed to be temporary until a proper solution was found.

**Pull request closed without merging**
