### PR TITLE
[Localization] Some French corrections + new dialogues translations

### PR DESCRIPTION
**Pull request by Adri1**
(Former #3699)

## What are the changes the user will see?
Translations in French locale files

## Why am I making these changes?
More accuracy / more text in French

## What are the changes from a developer perspective?
None

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?

### CODE REVIEW

**Review by CodeTappert — APPROVED** [review]
Approved since they are supposed to be tested in beta now...

**Comment by AsdarDevelops** [comment]
This PR seems fine to be merged. I checked every line for length and for the one I wasn't sure about I went ahead and took a screenshot:

**Review by AsdarDevelops — APPROVED** [review]
LGTM

**Review by KimJeongSun — DISMISSED** [review]

**Review by AsdarDevelops — APPROVED** [review]

**Review by flx-sta — DISMISSED** [review]

**Review by CodeTappert — DISMISSED** [review]

**Review by CodeTappert — DISMISSED** [review]

**Review by SangaraSorama — APPROVED** [review]

**Review by CodeTappert — APPROVED** [review]

**Comment by MokaStitcher** [comment]
I noticed while playing that the rival_2 victory dialogs still reference the last event, seems like a good opportunity to fix it

**Review by AsdarDevelops — APPROVED** [review]
The Candy Jar change is tested. Everything else should fit but I'd keep an eye on Gacha machine just in case.

Like @MokaStitcher said, rival Event text could be removed, but ig it can also be done in another PR (from GitLocalize)

**Review by torranx — APPROVED** [review]

**Pull request merged**
