### PR TITLE
[Feature] Move touch controls configuration (Reopened)

### PR DESCRIPTION
**Pull request by TimPerdok**
Reopened [#1569](https://github.com/pagefaultgames/pokerogue/pull/1569)

## What are the changes?

I've added a setting that opens a configuration panel to move the touch controls around the screen. This setting is only visible when the client has a touch screen. This setting does not use option values like the other settings, but instead opens the configuration panel using the action button. Both landscape mode and portrait mode have their own control positions saved separately.

## Why am I doing these changes?

I implemented these changes to improve the user experience by offering greater flexibility in the placement of the touch controls. This way the game is more comfortable to play on mobile devices and more accessible for people with disabilities, among others.

## What did change?

Most changes are inside a new singleton class (MoveTouchControlsHandler). This class is responsible for maintaining the configuration panel for the touch controls. Aside from this the CSS styling and HTML structure of the touch controls had to be changed to allow for these configuration options. Finally a new setting is added that can be activated using the action button that opens up the configuration panel.

### Screenshots/Videos
<details>
  <summary>Old video </summary> 

  https://github.com/user-attachments/assets/9e458f10-1abe-4ae7-8c48-0c9f632d0929

</details>

https://github.com/user-attachments/assets/2e11a4c7-b8bd-4462-a755-604d1a637980 

## How to test the changes?

Open the branch on a mobile device or a simulated mobile device using browser dev tools. Then navigate to the new setting on the bottom. This setting only appears when the client has a touch screen. By using the action button on the setting, a new panel opens up where you can drag the touch controls around the screen to reconfigure their position.

### CODE REVIEW

**Comment by torranx** [comment]
Please fix your branch first - remove changes carried from other branches.

**Comment by flx-sta** [comment]
@TimPerdok I think you should refactor your move-touch-controls handler in a way that the necessary HTML elements are only inserted when the user activates it rather than having the HTML element present in the code the whole time

**Comment by torranx** [comment]
I noticed in the first part of the video, it says the orientation is landscape- which should've been portrait.

**Comment by TimPerdok** [comment]
You're right. Fixed

**Comment by f-fsantos** [comment]
You have a couple of issues, please take a look here https://github.com/pagefaultgames/pokerogue/actions/runs/10290047686/job/28542081414?pr=3256

**Comment by TimPerdok** [comment]
Issues are fixed!

**Pull request merged**
