### PR TITLE
Added support for Pro Controller mapping

### PR DESCRIPTION
**Pull request by Odizinne**
Added mapping for switch pro controller (Inverted A/B - X/Y)

I tested this on my side and this is working as intended, but i have low experience and i don't know this project well. 

Please test thoroughly

### CODE REVIEW

**Comment by flx-sta** [comment]
How to test this, if I don't have a pro-controller?

**Comment by Odizinne** [comment]
> How to test this, if I don't have a pro-controller?


You can create a virtual pro controller with [this](https://gitlab.com/mguimard/Qt-USBIP-Virtual-USB-Device) VID=0x057E PID=0x2009 to validate detection.

As for testing button mapping, as said only A/B X/Y are inverted. If you do not have a Pro controller, well i have no idea how you can test this properly.

**Review by Greenlamp2 — APPROVED** [review]

**Comment by OreoCupcakes** [comment]
The d pad doesn't seem to work. My Pro Controller is connected via Bluetooth and the game detects the 057e-2009 controller, but the d pad buttons are completely grayed out and don't have any input what so ever

**Comment by Odizinne** [comment]
Was working when I made the PR. Will check when at home

**Comment by Odizinne** [comment]
Could you try with steam closed if you have it installed?

**Comment by Odizinne** [comment]
Nvm, looks like there is a detection problem if the controller was powered on BEFORE loading Pokérogue.

**Comment by OreoCupcakes** [comment]
> Could you try with steam closed if you have it installed?

It's on Windows 10 22H2, Firefox, I tried it with Steam closed, Steam input for Pro Controller off, Xbox extended driver uninstalled, connected via Windows bluetooth settings, and the controller powered on AFTER loading Pokerogue. The A/B/X/Y/etc. buttons work, its just the joystick and D pad that has no input what so ever.

**Pull request merged**
