### PR TITLE
Natures langs with new config

### PR DESCRIPTION
**Pull request by ArceUseless**

### CODE REVIEW

**Comment by rnicar245** [comment]
@Flashfyre  this PR should be OK

**Comment by Adri1** [comment]
Adding confing.ts and nature.ts for the Simplified Chinese added in the meantime

**Comment by CodeTappert** [comment]
For german:

```
export const nature: SimpleTranslationEntries = {
  "Hardy": "Robust",
  "Lonely": "Solo",
  "Brave": "Mutig",
  "Adamant": "Hart",
  "Naughty": "Frech",
  "Bold": "Kühn",
  "Docile": "Sanft",
  "Relaxed": "Locker",
  "Impish": "Pfiffig",
  "Lax": "Lasch",
  "Timid": "Scheu",
  "Hasty": "Hastig",
  "Serious": "Ernst",
  "Jolly": "Froh",
  "Naive": "Naiv",
  "Modest": "Mäßig",
  "Mild": "Mild",
  "Quiet": "Ruhig",
  "Bashful": "Zaghaft",
  "Rash": "Hitzig",
  "Calm": "Still",
  "Gentle": "Zart",
  "Sassy": "Forsch",
  "Careful": "Sacht",
  "Quirky": "Kauzig"
} as const;
```


Maybe you could just add the other languages as well. They are listed here:
https://bulbapedia.bulbagarden.net/wiki/Nature

**Comment by rnicar245** [comment]
@CodeTappert added the german translation
@Adri1 added nature.ts and nature to config.ts of chinese

**Comment by Adri1** [comment]
I also made a pull request to your fork with the French translation of Natures

**Review by Madmadness65 — APPROVED** [review]

**Pull request merged**
