### PR TITLE
[Balance] December Starter Balance Changes

### PR DESCRIPTION
**Pull request by damocleas**
## What are the changes the user will see?
Egg Moves, Passives, Starter costs, and Species Tiers
- Egg Move Changes
- Passive Changes
- Starter Cost Changes
- Legendary UP Gacha Calendar Additions
- ^ Some Egg Move Tiers changed
All changes should be [comparable here ](https://docs.google.com/spreadsheets/d/1KwUnV5xbKSi7af3l4MJPEkQb4AaB3dOphBdXsk72p_4/edit?usp=sharing)

## Why am I making these changes?
- Reduce TM redundancy in Egg Moves where it made sense to
- Cut down on overdistributed or mislabeled (rare vs common) moves
- Bring more pokemon in line with the desired power level of the game, this is hard to tell with so many pokemon with just one patch though

## What are the changes from a developer perspective?
Nothing specific

## How to test the changes?
Merge to a local, or play on beta when they are on there.

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [ ] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)

### CODE REVIEW

**Comment by PigeonBar** [comment]
The legendary gacha unit tests are failing because adding two species to the legendary egg pool shifted around the legendary gacha. So, we need to update those tests to the new species (ID 382 = Kyogre) as well.

**Comment by PigeonBar** [comment]
Some quick notes on how the starter cost changes could impact ME's:

- Increasing a non-legendary Pokemon's cost to 6 (e.g., Duraludon) makes it spawnable in Dark Deal.
- Decreasing a Paradox Pokemon's cost to 5 makes it catchable in Safari Zone and maybe Pokemon Salesman. Is this intended?

20241116 Safari Zone Paradox

**Comment by damocleas** [comment]
> Some quick notes on how the starter cost changes could impact ME's:
> 
> * Increasing a non-legendary Pokemon's cost to 6 (e.g., Duraludon) makes it spawnable in Dark Deal.
> * Decreasing a Paradox Pokemon's cost to 5 makes it catchable in Safari Zone and maybe Pokemon Salesman. Is this intended?
> 
> 20241116 Safari Zone Paradox

appreciate the check up, hence why this was a draft since we haven't done this before ✌️ - do these ME's not have filters to prevent properly labelled mons? Seems like a huge oversight in futureproofing

**Comment by PigeonBar** [comment]
> appreciate the check up, hence why this was a draft since we haven't done this before ✌️ - do these ME's not have filters to prevent properly labelled mons? Seems like a huge oversight in futureproofing

There are checks to prevent legendary, pseudo-legendary, and mythical spawns, but no checks for Paradox because they have always been at least 6 cost. Should we add in checks for that as well?

**Comment by damocleas** [comment]
> > appreciate the check up, hence why this was a draft since we haven't done this before ✌️ - do these ME's not have filters to prevent properly labelled mons? Seems like a huge oversight in futureproofing
> 
> There are checks to prevent legendary, pseudo-legendary, and mythical spawns, but no checks for Paradox because they have always been at least 6 cost. Should we add in checks for that as well?

yes, probably just placing them in their own category, I'd do the same with ultra beasts but leave that one unused for now imo

**Review by innerthunder — APPROVED** [review]

**Review by MokaStitcher — APPROVED** [review]
lgtm

**Review by xsn34kzx — APPROVED** [review]

**Pull request merged**
