### PR TITLE
Add option to skip IV scanner prompt

### PR DESCRIPTION
**Pull request by IceFire03**
One pet peeve of a couple players I've talked to is having to run through the IV scanner dialogue _every single wave_. This is a simple implementation of a setting such that the IV scanner dialogue is skipped if set to "never"; or, by default, it still will scan "every wave".

### CODE REVIEW

**Comment by bennybroseph** [comment]
May be better to call the "Every Wave" option "Always"

**Comment by PaulBeslin** [comment]
> May be better to call the "Every Wave" option "Always"

I'd say On/Off for consistency

**Comment by bennybroseph** [comment]
True, that matches the other options near it

**Comment by IceFire03** [comment]
I originally had the option as "Disable IV scanner" on/off, but feedback said it was too confusing if on or off meant disabled, so I changed it to the current text. I'm totally open for it to get tweaked before merge though!

**Pull request closed without merging**
