### PR TITLE
feat: added localisation for eggs and french translations

### PR DESCRIPTION
**Pull request by TeKrop**
Added localisation support for eggs (list and gacha). Also added french translation.
Tested in both English and French. Italian, Spanish and German translations are copied from English.

Here are a few changes which could be discussed if needed :
- Gacha types french descriptions (for french native speakers or translators)
- Pull options text refactoring, in order to facilitate changes
- Pull options text resizing to make the french translation visually OK (see following screenshots)

Pull options today
image

Pull options after changes
image

Pull options in french
image

Eggs list in french
image
image
image
image

Eggs rarity after pull
image
image

Too many eggs
image

### CODE REVIEW

**Comment by Adri1** [comment]
I see sevral changes to make :
- Switching all apostrophes from ' to ’
- Each time a Pokémon Egg in mentioned, it should be written with the first letter in capital, so "Œuf"
- For the sentence "Qu'est-ce qui va en sortir ? Ça va mettre du temps." in the image, adding a non-breaking space between "sortir" and the question mark, to avoid it to be left alone.

**Comment by TeKrop** [comment]
@Adri1 Thank you for your feedbacks 🙏 I made the fixes you mentionned, and will make more tests before putting the PR as ready for review 👍

**Comment by TeKrop** [comment]
PR is up-to-date (conflicts solved) and ready to be reviewed 👍

**Comment by josericardo-fo** [comment]
I made #841 in portuguese without noticing this. Looks good to me

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
