### PR TITLE
Implemented Quick Draw

### PR DESCRIPTION
**Pull request by lucfd**

### CODE REVIEW

**Comment by Xavion3** [comment]
This doesn't work, it'd let it outspeed actual priority moves.

**Comment by lucfd** [comment]
Good catch. Thinking the simplest solution would be to increment priority by 0.5 to only outspeed the current priority bracket. Let me know if you can think of any problems with this approach

**Comment by TempsRay** [comment]
Hmm, the idea of making non integer priority is interesting and this code can be reused for things like stall, quick claw, and mycelium might but there's two main concerns I had. 
1. Might be for future proofing, but things that increment/decrement move priorities by half do not stack. A theoretical pokemon with two quick draw procs against an opponent with a single quick draw proc should still be in the same priority bracket.
2. How does this interact with moves/abilities that interact with priority like quick guard, queenly majesty, dazzling?
3. What about things that interact with breaking priority? (after you, quash, instruct, dancer)

**Comment by bennybroseph** [comment]
Closing this due to inactivity. Feel free to make a new request if interest is reignited

**Pull request closed without merging**
