### PR TITLE
Fix: display every hit result of multi-hit moves

### PR DESCRIPTION
**Pull request by SnowCharmQ**
## What are the changes:

- Remove the condition that judges whether to display _HitResult_ information.

## Why am I making these changes:

- This PR aims to address #1287. After changing, the hit result will be shown even if the opponent's Pokemon faints before the final hit of the multi-hit move.
- Follow the official versions, every hit result for multi-hit moves needs to be displayed correctly and respectively.

### CODE REVIEW

**Comment by torranx** [comment]
I think this is already being worked on, #783

**Comment by SnowCharmQ** [comment]
> I think this is already being worked on, #783

In #783, the condition is changed to `if (source.turnData.hitsLeft === 1 || this.isFainted())`. In fact, simply removing the condition can solve this problem.

**Comment by torranx** [comment]
> > I think this is already being worked on, #783
> 
> In #783, the condition is changed to `if (source.turnData.hitsLeft === 1 || this.isFainted())`. In fact, simply removing the condition can solve this problem.

have you tested other scenarios? pretty sure theres a reason why that condition is present

**Comment by SnowCharmQ** [comment]
> > > I think this is already being worked on, #783
> > 
> > 
> > In #783, the condition is changed to `if (source.turnData.hitsLeft === 1 || this.isFainted())`. In fact, simply removing the condition can solve this problem.
> 
> have you tested other scenarios? pretty sure theres a reason why that condition is present

The condition in #783 just displays information when multi-hit moves have finished all hits or the opponent has fainted. In this case, the information can be displayed only once per move. But in the official Pokemon versions, every hit result information will be displayed correctly and respectively. (indeed I do not test all versions) But it is better to follow the official version.

**Comment by torranx** [comment]
I meant have you tested your code change not other pokemon versions...

**Comment by Tempo-anon** [comment]
I believe https://github.com/pagefaultgames/pokerogue/pull/2857 should address this so I will close this issue out for now

**Pull request closed without merging**
