### PR TITLE
Add the option to localize the Dialogue

### PR DESCRIPTION
**Pull request by CodeTappert**
Example of Trainer Dialogue still working: (The text scrolling still works)
image
image

Rival Dialogue (With emotions etc still working)
image

Final Boss Dialogue works: (all dialogue but i do not want to spoil more here)
image

Also Ending dialogue also works (but again dont want to spoil)

### CODE REVIEW

**Comment by CodeTappert** [comment]
This is Ready for Review! 

I only added the option for dialogue translation in this PR. Not any translation itself (will be another PR).

**Comment by CodeTappert** [comment]
I am sorry. I dont know what you mean by female agreement 

The Player charakter was no dialogue.

**Comment by Adri1** [comment]
I know the player has no dialogue, but the Trainers you encounter do talk to you. And depending of your gender, changes applies.

Example (from line 21 in the dialogue.ts locale) :
**ENGLISH**
_"Wow! You're strong!"_

**FRENCH** (when you are taking to a **man**)
_"Woah ! T'es fort !"_

**FRENCH** (when you are taking to a **woman**)
_"Woah ! T'es forte !"_

Notice the extra "e" added to "fort", when you paly as the female

**Comment by CodeTappert** [comment]
Well currently it isnt easily possbile to add that. 

As it would require to add lots more logic to the selection. 

If you have a ideas feel free to make a pr to my pr

**Comment by Adri1** [comment]
I don't have the skills ti help with this, so I hope somebody would be able to help with this issue...

I don't know about German or Chinese, but more than French, it also gonna be an issue at least for Spanish, Italian and Portuguese locales

**Comment by CodeTappert** [comment]
As i am not doing the french thing in this pr anyways (would be another) this pr is still ready to be reviewed/merged by a dev..

@TempsRay

**Comment by CodeTappert** [comment]
image

Here is the proof of the double dialogue still working now that it is localizable

**Comment by CodeTappert** [comment]
@bennybroseph Its finished now. I added german localization and made sure it works (is not to long) etc.

**Comment by Adri1** [comment]
@CodeTappert While it's still not merged, I open a PR to your branch with a partial French translation

**Comment by CodeTappert** [comment]
> @CodeTappert While it's still not merged, I opened a PR to your branch with a partial French translation

Did you check that they arent  to long?

**Comment by Adri1** [comment]
It should mostly be OK, I made each translation by directly comparing to the length of the original sentences.
If corrections have to be made, it will be quick as there is not that much translated anyway, for the moment

**Comment by CodeTappert** [comment]
> It should mostly be OK, I made each translation by directly comparing to the length of the original sentences. If corrections have to be made, it will be marginal and quickly adjusted as there is not that much translated anyway, for the moment

Well then tell me when you are done. THen i will merge it. 

I dont really want to delay this one here any longer...

**Comment by Adri1** [comment]
You can go ahead don't worry, edits and completions are gonna be made once merged into main, I don't want you to delay it any further either. Especially considering I attend to take it more slowly than you did for German

**Comment by bennybroseph** [comment]
I'm hesitant to merge this. French is not the only language that needs different translations depending on the player character's gender. I think we need a solution that can account for this.

**Comment by CodeTappert** [comment]
> I'm hesitant to merge this. French is not the only language that needs different translations depending on the player character's gender. I think we need a solution that can account for this.

I mean we could do instead of

`export const dialogue: DialogueTranslationEntries = {`

`export const PCMdialogue: DIalogueTranslationsEntries = {
`

and 

`export const PCFdialogue: DIalogueTranslationsEntries = {
`

and then change the call to include that prefix depending on the player character gender

**Comment by bennybroseph** [comment]
I think that would work, yeah. That way we aren't duplicating translations where they aren't needed, but still provide them for languages that do.

**Comment by Adri1** [comment]
> I'm hesitant to merge this. French is not the only language that needs different translations depending on the player character's gender. I think we need a solution that can account for this.

I think it's okay to merge it now but only if their is a work behind to adapt it on a future PR.
After all this kind of case already exists, bacause soem traner classes are still not adapted to the trainer's gender (like for the Gym Leaders, Champions, Rival etc...)

**Comment by CodeTappert** [comment]
> > I'm hesitant to merge this. French is not the only language that needs different translations depending on the player character's gender. I think we need a solution that can account for this.
> 
> I think it's okay to merge it now but only if there is a work behind to adapt it on a future PR. After all this kind of case already exists, because some trainer classes are still not adapted to the NPC genders either (like for the Gym Leaders, Champions, Rival etc...). Female Gyms in French for example still use the male version of "Gym Leader" or a gender-inclusive writing in the meantime for some other classes

I will add the gender specific choosing of the title

**Comment by Adri1** [comment]
PR subbited to your branch with updated French trainers.ts

**Comment by CodeTappert** [comment]
> PR subbited to your branch with updated French trainers.ts

Since i now added the option for localized titles and dialogue based on player gender you will need to do that again. But please wait with it for when this was merged so you can create your own PR

**Comment by CodeTappert** [comment]
@bennybroseph I added player-gender specific dialogue.

**Comment by Adri1** [comment]
> > PR subbited to your branch with updated French trainers.ts
> 
> Since i now added the option for localized titles and dialogue based on player gender you will need to do that again. But please wait with it for when this was merged so you can create your own PR

Undertstood
Including the trainer classes PR to your branch?

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
