### PR TITLE
Localization: Added biomes, summary-ui-handler, party-ui-handler and summary images

### PR DESCRIPTION
**Pull request by rnicar245**

### CODE REVIEW

**Comment by CodeTappert** [comment]
Is there any way i can help in localizing the german part?

**Comment by josericardo-fo** [comment]
I think you forgot the pt_BR files

**Comment by josericardo-fo** [comment]
> Is there any way i can help in localizing the german part?

same with portuguese

**Comment by rnicar245** [comment]
> I think you forgot the pt_BR files

I didn't have pt_BR and portuguese when I created the branch,

**Comment by josericardo-fo** [comment]
> > > I think you forgot the pt_BR files
> > 
> > 
> > I didn't have pt_BR and portuguese when I created the branch,
> 
> I'm going to merge this branch with main now

Nice

**Comment by rnicar245** [comment]
@josericardo-fo @CodeTappert  You can either wait until this PR gets merged or make a PR to my fork's summary branch

**Comment by josericardo-fo** [comment]
> @josericardo-fo @CodeTappert You can either wait until this PR gets merged or make a PR to my fork's summary branch

2 things: did you merge with main? and how can I modify the type image texts?

**Comment by rnicar245** [comment]
> > @josericardo-fo @CodeTappert You can either wait until this PR gets merged or make a PR to my fork's summary branch
> 
> 2 things: did you merge with main? and how can I modify the type image texts?

I did now. Problem is, I have to fix some stuff because of some recent additions.
You just need an image editor, you should edit the type_de.png file for german, don't touch the json

**Comment by rnicar245** [comment]
> > @josericardo-fo @CodeTappert You can either wait until this PR gets merged or make a PR to my fork's summary branch
> 
> 2 things: did you merge with main? and how can I modify the type image texts?

I'm adding the portuguese images so don't do anything yet

**Comment by rnicar245** [comment]
> > @josericardo-fo @CodeTappert You can either wait until this PR gets merged or make a PR to my fork's summary branch
> 
> 2 things: did you merge with main? and how can I modify the type image texts?

I just added the portuguese related stuff

**Comment by Adri1** [comment]
Think for it, I'm gonna make the French assests!

**Comment by rnicar245** [comment]
> Think for it, I'm gonna make the French assests!

Pull the last changes, it adds and edits some images for the new abilty/passive images

**Comment by CodeTappert** [comment]
How did you create the type image? Pixel by pixel?

**Comment by rnicar245** [comment]
> How did you create the type image? Pixel by pixel?

I got the letters I wanted to use from the other types and rearranged them

**Comment by rnicar245** [comment]
@Adri1 @josericardo-fo I fixed an error related to the summary_tabs_2 image for fr and pt_BR (I named your files summary_tabs_2_ lang instead of summary_tabs_2_lang, so the game didn't load them)
Sorry for the trouble

**Comment by CodeTappert** [comment]
> > How did you create the type image? Pixel by pixel?
> 
> I got the letters I wanted to use from the other types and rearranged them

Lets hope that this works out :D

**Comment by josericardo-fo** [comment]
Any tips with the Photoshop? Noob here lol

**Comment by josericardo-fo** [comment]
@rnicar245 the "estelar" text in spanish has different shading from english. was that intentional?

**Comment by rnicar245** [comment]
> @rnicar245 the "estelar" text in spanish has different shading from english. was that intentional?

Not exactly but is so minor is not worth the hassle

**Comment by rnicar245** [comment]
> Any tips with the Photoshop? Noob here lol

I use Paint.NET which is like a mini photoshop, never used the actual photoshop actually.

**Comment by Adri1** [comment]
I completed the French translation, how can can I submit it to you?

**Comment by CodeTappert** [comment]
The types_<language>.png seems only to work in the summary screen. And not in the starter select. Am i missing something?

**Review by Adri1 — APPROVED** [review]

**Comment by CodeTappert** [comment]
I added a pr with my changes (german pr) here https://github.com/rnicar245/pokerogue-esp2/pull/2

**Comment by rnicar245** [comment]
> The types_.png seems only to work in the summary screen. And not in the starter select. Am i missing something?

I'll look into it, along with the PRs

**Comment by Adri1** [comment]
@rnicar245 I also added a pull request to you branch

**Comment by CodeTappert** [comment]
> > The types_.png seems only to work in the summary screen. And not in the starter select. Am i missing something?
> 
> I'll look into it, along with the PRs

I fixed it in my pr

**Comment by Adri1** [comment]
While we are onto thing taht aren't displayed on the summary screen, are the Natures properly translated with this PR, or are still in English on the summaries?
Can't check right now

**Comment by rnicar245** [comment]
> While we are into thing that aren't displayed on the summary screen, are the Natures properly translated with this PR, or are still in English on the summaries? Can't check right now

Yeah, they are displayed correctly now

**Comment by Adri1** [comment]
Is that normal if you merged my PR into you main branch and not to your summary branch used here, or a mistake slipped into the process, either to you side or my side?

**Comment by CodeTappert** [comment]
> Is that normal if you merged my PR into you main branch and not to your summary branch used here, or a mistake slipped into the process, either to you side or my side?

You created the pr wrong.

**Comment by Adri1** [comment]
Oops, sorry for the inconvenience

**Comment by rnicar245** [comment]
I made screenshots for all langs, including legacy UI,
https://drive.google.com/file/d/1Xi7NVGpCHO3Z-ci4_UbH_1nv-ppQiKru/view?usp=sharing

**Comment by CodeTappert** [comment]
> I made screenshots for all langs, including legacy UI, https://drive.google.com/file/d/1Xi7NVGpCHO3Z-ci4_UbH_1nv-ppQiKru/view?usp=sharing

There is an error in german. It should be "Fähigkeit" instead of "Fähgkeit"

in startet select

**Comment by Adri1** [comment]
I opened a pull request to your branch with edits I made to some French files

**Review by rnicar245 — COMMENTED** [review]
Apply the new summary_stats changes to the rest of the lang images

**Comment by rnicar245** [comment]
@bennybroseph I sent you a DM on discord

**Comment by Adri1** [comment]
As I explored the files, I noticed this image that you haven't submit to be adapted, is that on purpose or it has just been forgot ?

summary_overlay_shiny.png, in ui file

summary_overlay_shiny

**Comment by Adri1** [comment]
As you wish, if I took that liberty of pointing it out anyway is because theses images are added on the top of the base layout.
So it causes a tiny visal bug when you a son a shiny Pokémon in the laguages that have a diffrent way to write "No"
image

**Comment by bennybroseph** [comment]
Would really like this to be split up into smaller chunks. This is very difficult to review atm with so many comments and changes and updates

**Comment by rnicar245** [comment]
> Would really like this to be split up into smaller chunks. This is very difficult to review atm with so many comments and changes and updates

Almost all the stuff added is focused on the Pokemon battle menu. Also, I don't know how to split up an already existing PR 🙃

**Comment by CodeTappert** [comment]
Maybe first of all create a seperate one for the type symbol localization! This should work on its own easily

**Comment by Adri1** [comment]
@rnicar245  I noticed I forgot to translate a French type in types_fr.png, here is the corrected version :

types_fr

**Pull request closed without merging**
