### PR TITLE
[Feature] Initial version of pokedex

### PR DESCRIPTION
**Pull request by hayuna**
## What are the changes?
Adding access to pokedex to see what species we caught

## Why am I doing these changes?
It comes from plenty feature request on discord

## What did change?
Adding new screen based on vouchers to see caught pokemons

### Screenshots/Videos
Screenshot 2024-06-16 at 21 47 17

Screenshot 2024-06-16 at 21 43 06

## How to test the changes?
Go to menu screen and click Pokedex (behind Vouchers option)

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

## Progress
- [x] Display all species
- [x] Display caught species
- [x] Display only shown species
- [x] Shadow not seen species
- [x] Display all forms
- [x] Display not caught forms
- [x] Shadow not seen forms
- [x] Display Female symbol if caught 
- [x] Shadow Female symbol if not caught
- [x] Not show Female Symbol  if not available gender
- [x] Display Male symbol if caught 
- [x] Shadow Male symbol if not caught
- [x] Not show Male Symbol  if not available gender
- [x] Show yellow shiny icon if caught
- [x] Shadow yellow shiny icon if not caught
- [x] Show blue shiny icon if caught
- [x] Shadow blue shiny icon if not caught
- [x] Show red shiny icon if caught
- [x] Shadow red shiny icon if not caught
- [x] Show Hidden ability icon if caught
- [x] Shadow Hidden ability icon if not caught
- [x] Show Ribbon win icon if caught
- [x] Shadow Ribbon win icon if not caught
- [ ] The pokemon icons should not be overlapping with the UI borders as they currently are for displaying forms at the bottom
- [ ] The icons for catch attributes (gender, shiny, etc) should all be consistent sizes and spacing in the container
- [x] Any use of the word Pokedex should include the accent and display as "Pokédex"
- [ ] The hidden ability icon should not be used to represent every ability of a pokemon
- [ ] Cursor should wrap from bottom to top and vice versa as on other screens

### CODE REVIEW

**Comment by Tempo-anon** [comment]
Can you add a way for it to display all the caughtAttrs? And also ability trackers for both abilities and the hidden one too?
```
NON_SHINY: 1n,
SHINY: 2n,
MALE: 4n,
FEMALE: 8n,
DEFAULT_VARIANT: 16n,
VARIANT_2: 32n,
VARIANT_3: 64n,
DEFAULT_FORM: 128n
  ```

**Comment by Tempo-anon** [comment]
Tested it out and this is a very cool resource even in its current state. Trying to think how best to fit those 8 bits of caughtAttr and abilities. Excuse the horrible paint job, but maybe something like this where it uses the empty space in the forms section or name box?

Male, female, 3 shiny variants, 3 abilities, completion ribbon

**Comment by hayuna** [comment]
Lets try this. But I suggest to put all of icons in the "caught" container

**Comment by Tempo-anon** [comment]
> Lets try this. But I suggest to put all of icons in the "caught" container

Sounds good! Just hope there's enough space since in some languages the text might take up a lot of space

**Comment by hayuna** [comment]
Small Update

Screenshot 2024-06-18 at 19 06 26
Screenshot 2024-06-18 at 19 07 11

**Comment by hayuna** [comment]
Gender icons will no longer be visible if pokemon has no possibility to have specific gender (Tauros always Male, Jinx always Female, Porygon is Genderless)

**Comment by hayuna** [comment]
I think It could be ready for review. If we have any graphic here, maybe icons could be redesigned for pokedex

**Review by brain-frog — CHANGES_REQUESTED** [review]
Personally I don't like that the UI of this is near identical to the achievements/vouchers. Pokedex in most games will usually stand out and be closer to something like the starter select.
Otherwise: 

- the pokemon icons should not be overlapping with the UI borders as they currently are for displaying forms at the bottom
- the icons for catch attributes (gender, shiny, etc) should all be consistent sizes and spacing in the container
- any use of the word Pokedex should include the accent and display as "Pokédex"
- the hidden ability icon should not be used to represent every ability of a pokemon
- cursor should wrap from bottom to top and vice versa as on other screens

I believe there is more but these are my initial thoughts

**Comment by bennybroseph** [comment]
https://github.com/pagefaultgames/pokerogue/assets/13838608/98457f4b-ed47-47f9-8fce-a7daca9c4c3e

Here's a mock-up of something more akin to a traditional Pokedex but with the same box list of Pokemon we have in this game if you need ideas. Obviously this would need to be adapted for Legacy UI, but this uses assets already in the game with very minimal tweaks that can be done through code or image editing depending on preference.

**Comment by donneeee** [comment]
i love that finally someone picked up the  daunting task of implementing a pokedex in game! i've been working on the spreadsheet version of this for 3 months now and if there is anything i could do to help with this as far as features it might be missing for a pokerogue dex (i noticed seen attribute was not account for; only mention this cause we have a "seen" % on stats page) or if you need quick references, i've documented where nearly anything that was needed for a pokedex already in a database that's importing the raw text urls from github. feel free to reach out if you could use a hand and if i see if i can contribute!

thank you so much!

**Comment by hayuna** [comment]
Work in progress

Screenshot 2024-06-23 at 14 06 47

**Comment by hayuna** [comment]
Screenshot 2024-06-23 at 18 42 40

**Comment by hayuna** [comment]
Screenshot 2024-06-24 at 12 28 19

**Comment by hayuna** [comment]
Continuation is here: https://github.com/pagefaultgames/pokerogue/pull/3342

**Pull request closed without merging**
