### PR TITLE
 [QoL] Enable female gender for all default starters and all existing s…

### LINKED ISSUE #2103: [Feature] Start the game with both male and female starter pokemon
**Is your feature request related to a problem? Please describe.**
I introduced a friend to the game and when choosing her first team, she asked me if she could choose female pokemon. I thought you might just be able to toggle the gender but I was surprised to find only the male starters are available at first. It's a small but I think important option to have.

**Describe the Feature**
New players should have the ability to toggle the gender of the starting pokemon with G (as if they had been caught).

**Additional context**
I looked through the code and I believe changing this one line, 1308, in /src/system/game-data.ts should do it:
From:
`const defaultStarterAttr = DexAttr.NON_SHINY | DexAttr.MALE | DexAttr.DEFAULT_VARIANT | DexAttr.DEFAULT_FORM;`
To:
`const defaultStarterAttr = DexAttr.NON_SHINY | DexAttr.MALE | DexAttr.FEMALE | DexAttr.DEFAULT_VARIANT | DexAttr.DEFAULT_FORM;`

### PR DESCRIPTION
**Pull request by timchi94**
## What are the changes?
Small change to allow gender changes in default starter pokemon 

## Why am I doing these changes?
some people want notboy pokemon
Closes #2103 

## What did change?
-set option for default starter pokemon gender 
-add migration for above

## How to test the changes?
start a new save, verify female exists for all 27 starters, then in existing save verify addition

## Checklist
- [y] There is no overlap with another PR?
- [y] The PR is self-contained and cannot be split into smaller PRs?
- [y] Have I provided a clear explanation of the changes?
- [y] Have I tested the changes (manually)?
    - [y?] Are all unit tests still passing? (`npm run test`) 6 errors on main
- [n] Are the changes visual?
  - [n] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by corentin-feys** [comment]
Is something missing for approval? Also this would close issue #2103

**Comment by frutescens** [comment]
Hi, I was wondering if you were still working on this. If you are, could you merge your branch with the latest beta repo? Thank you.

**Comment by frutescens** [comment]
Tentative Approval provided above.

## My Testing
### New Game Starter Select
Screenshot 2024-08-19 at 7 29 13 PM

### Test Data  
Screenshot 2024-08-19 at 7 33 47 PM

### Test Data after Importing 
Screenshot 2024-08-19 at 7 33 26 PM

**Review by frutescens — DISMISSED** [review]

**Review by xsn34kzx — DISMISSED** [review]
lgtm!

**Comment by Xavion3** [comment]
If this is happening remember to update fresh start to not gender lock.

**Comment by timchi94** [comment]
rebased on latest beta

**Comment by frutescens** [comment]
Could you update the fresh start challenge to allow for both genders as well then?

**Comment by frutescens** [comment]
Fixed it myself so this can be merged into the next beta. 


https://github.com/user-attachments/assets/206dfa21-6081-4762-9167-ab4fe77160cb

**Review by DayKev — APPROVED** [review]

**Review by CodeTappert — APPROVED** [review]

**Review by frutescens — APPROVED** [review]

**Pull request merged**
