### PR TITLE
Persist last used Nature, Ability, Gender, Variant and Form

### PR DESCRIPTION
**Pull request by JakubHanko**
## What are the changes?

I am adding persistence of last used nature, ability, form, variant and gender to the local storage. This allows for automatic setting of default natures, etc. at the starter select screen to the last used.

## Why am I doing these changes?

Numerous requests on Discord and Reddit. Not having this persistence often leads to incorrect party setup and runs having to be restarted.

## What did change?

I have added a new attribute to the GameData class to be used as storage for the last used Pokemon properties. This is then persisted into the local storage and used as a default in the starter select ui handler. Each user has its own local storage entry.

However, there is a small visual bug when you first log in where if you already have a variant persisted in the local storage, its sprite won't be set appropriately. This fixes itself the moment you set the cursor over the respective Pokémon. Based on my understanding, the PR that is doing the same thing as I do, has a similar problem. 

In my case, it's due to the Login Phase coming after the UI setup. I don't see it as a huge impediment and can be fixed in a follow-up. The fix for this scenario would require a bigger scope of changes.

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/60473007/e27e89f9-a54d-4dec-9835-fc9d5574f85e

## How to test the changes?
Add 
```
eyIxIjp7ImRleEF0dHJDdXJzb3IiOjE0OX0sIjQiOnsiZGV4QXR0ckN1cnNvciI6MTQ5fSwiNyI6eyJkZXhBdHRyQ3Vyc29yIjoxNDl9LCIxMCI6eyJkZXhBdHRyQ3Vyc29yIjoxNDl9LCIxMyI6eyJkZXhBdHRyQ3Vyc29yIjoxNDl9LCIxNiI6eyJkZXhBdHRyQ3Vyc29yIjoxNDl9LCIxOSI6eyJkZXhBdHRyQ3Vyc29yIjoxNTN9LCIyMSI6eyJkZXhBdHRyQ3Vyc29yIjoxNTB9LCIyMyI6eyJkZXhBdHRyQ3Vyc29yIjoxNDl9LCIzNyI6e30sIjU2Ijp7fSwiNzkiOnt9LCI5NiI6e30sIjExMSI6e30sIjEyNCI6e30sIjEzNyI6e30sIjE1MCI6e30sIjE1MiI6eyJkZXhBdHRyQ3Vyc29yIjoxNDl9LCIxNTUiOnsiZGV4QXR0ckN1cnNvciI6MTQ5fSwiMTU4Ijp7ImRleEF0dHJDdXJzb3IiOjE0OX0sIjE2MSI6eyJkZXhBdHRyQ3Vyc29yIjoxNDl9LCIxNjMiOnsiZGV4QXR0ckN1cnNvciI6MTQ5fSwiMTY1Ijp7ImRleEF0dHJDdXJzb3IiOjE0OX0sIjE3MyI6e30sIjE3NSI6e30sIjE3NyI6e30sIjE3OSI6eyJkZXhBdHRyQ3Vyc29yIjoxNDl9LCIxODMiOnsiZGV4QXR0ckN1cnNvciI6MTQ5fSwiMTkxIjp7fSwiMjAwIjp7fSwiMjAxIjp7ImRleEF0dHJDdXJzb3IiOiI0Mjk0OTY3MzE3In0sIjIwNiI6e30sIjIyMCI6e30sIjIzNSI6e30sIjI0NiI6e319
```
as a starterData_Guest value to the local storage.

Hoothoot should be a good candidate for testing of everything but the forms. On the other hand, Unown has a few forms unlocked.

Alternatively, you can catch the pokemon yourself.

## Checklist
- [ ] Have I checked that there is no overlap with another PR?
There is an overlap with #1401 which is doing multiple features in one PR.
- [x] Have I made sure the PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by bennybroseph** [comment]
Should get a Lead Dev/Admin to approve this before you put too much work into it. Even a few more bytes of data has huge implications on how much data we have to store on the server. 

Is this going to be stored in locally only?

**Comment by JakubHanko** [comment]
Local storage would make the most sense since I do not want to store 2 x N x 4 bytes per player (where N is the number of starters). To be frank, I am still trying to familiarize myself with the data persistence part - I am unable to tell if the storage right now is local only or not. This will be part of my internal testing as well.

**Comment by bennybroseph** [comment]
settings are only stored locally. things like audio levels, game speed, tutorials, etc. that'd be a place to start

**Comment by JakubHanko** [comment]
Moved the nature and ability persistence into local storage. Haven't found any bugs but for the changes to come online, the server has to be restarted and local storage purged? Have yet to find a better way.

**Comment by wesleyschlenker** [comment]
> Should get a Lead Dev/Admin to approve this before you put too much work into it. Even a few more bytes of data has huge implications on how much data we have to store on the server.

@bennybroseph, it seems like you're pretty active in the repo. Now that the author has these configurations set in local storage, could you ping a "Lead Dev/Admin" for us so that this can get approved? It brings a tear to my eye not seeing any progress here in days :(

**Comment by wesleyschlenker** [comment]
@bennybroseph @prime-dialga bump

**Comment by JakubHanko** [comment]
Sure, why not. Won't have time until the weekend though.

**Comment by prime-dialga** [comment]
> @bennybroseph @prime-dialga bump

Thanks for the ping.
It might make more sense to implement that for https://github.com/pagefaultgames/pokerogue/pull/1401 as that already stores abilities, natures, shiny choice, versions (and genders with todays update)

**Comment by prime-dialga** [comment]
Also, if we use a new localstorage entry (maybe even completely independant from game-data.ts) we could easily bypass any purging.

**Comment by JakubHanko** [comment]
@prime-dialga I don't agree with you since the scope of #1401 is already multiple features. And on top of that your PR came after mine so there is a clear overlap with an existing PR.

**Comment by JakubHanko** [comment]
Added the persistence of whole dex attr. However, there is a small visual bug when you first login where if you already have a variant persisted in the local storage, its sprite won't be set appropriately. This fixes itself the moment you set the cursor over the respective Pokémon.

I will update the PR description in a minute.

**Comment by Tempo-anon** [comment]
Nature, ability, form, gender, and variant are now currently persisted in game so I will close out this PR

**Pull request closed without merging**
