### PR TITLE
[Localization] Updated pixel font for Simplified Chinese

### PR DESCRIPTION
**Pull request by Siyuanw**
## What are the changes?

Introduced pixel font for Chinese, to match the game style.

The font comes from an open-source project https://github.com/TakWolf/fusion-pixel-font

And you can find the licence here https://github.com/TakWolf/ark-pixel-font/blob/develop/LICENSE-OFL

## Why am I doing these changes?

The game currently uses a font that only contains basic latin characters.

All the CJK characters are fall back to a system defined font.

## What did change?

Added a pixel font in the static resource, and use the font when the language is set to Simplified Chinese.

There're too many places which are designed for "emerald" font.

After the change, the "emerald" font still take the precedence over the newly introduced pixel font.

### Screenshots/Videos

main

battle

## How to test the changes?

Please switch the language to Chinese Simplified to verify the change.

change

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Tempo-anon** [comment]
While this does fit the game aesthetics better I feel like it loses some readability

**Comment by 40chyan** [comment]
Actually I think this font is good, the original ch font not only looks weird, several pixels on the very top of each chinese character are not being displayed correctly. In terms of readability, I don't think there's any problem on it. Or you think I should make a poll in CH community to make sure? @Tempo-anon 
image

**Comment by Tempo-anon** [comment]
> Actually I think this font is good, the original ch font not only looks weird, several pixels on the very top of each chinese character are not being displayed correctly. In terms of readability, I don't think there's any problem on it. Or you think I should make a poll in CH community to make sure? @Tempo-anon image

If you can get the CH player's community's thoughts on this that would be great since they would be the primary users of this text.

**Comment by bennybroseph** [comment]
It seems like the community has a different solution for this. Feel free to join the discussion in the Discord

**Pull request closed without merging**
