### PR TITLE
Implement Expanding Force

### PR DESCRIPTION
**Pull request by nrawicz**
Implemented Expanding Force with the following new attributes:

- Power is multiplied by 1.5x on Psychic Terrain. (MovePowerMultiplierAttr)
- Target is changed to ALL_NEAR_ENEMIES on Psychic Terrain, otherwise target is NEAR_ENEMY. (VariableTargetAttr)

Created new attribute: VariableTargetAttr

- Code is based on MovePowerMultiplierAttr, a simple function which sets the parameter fed into it as whatever the conditional logic in the move's initialization returns.

Added code in getMoveTargets() to apply VariableTargetAttr to any moves that have one. Should theoretically be applicable to Tera Starstorm with conditional logic as well. Does not appear to interfere with current move logic (all other moves behave as normal and Expanding Force's behavior was tested with and without terrain) but I recommend more testing.

*Technically* this is not a 100% one-to-one implementation as Expanding Force should not change its behavior in target *selection* regardless of whether terrain is active, so that could be worth examining in the future, however I would consider this satisfactorily fully implemented assuming it does not have any bugs (again, I tested but I recommend further testing just in case).

### CODE REVIEW

**Review by Madmadness65 — CHANGES_REQUESTED** [review]
It looks like some previous commits to the move file got undone in your PR here, so you'll want to double check that.

**Comment by nrawicz** [comment]
Thank you @Madmadness65 , my mistake.

**Comment by nrawicz** [comment]
Alright, it should be good for real this time.

**Review by Madmadness65 — APPROVED** [review]
LGTM now

**Pull request merged**
