### PR TITLE
Fix boss-segment reload issue

### LINKED ISSUE #1697: [BUG] 145 rival boss pokemon gains extra HP barrier when reloading
I did a brief search for "Rival", "Barrier", "145" and couldn't find this mentioned

**Describe the bug**
If you reload the rival fight at 145 by any method then her starter gains an extra HP barrier

**To Reproduce**
Enter the 145 rival fight
Reset by any means, save & exit, refresh, disconnect
Check HP barriers

**Expected behavior**
I'd expect pokemon states to stay consistent to initial appearance.

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/46976469/e888dbd9-7d29-41a5-be45-73e3a9030d63

**Device**
PC

**Additional context**
Is the game doing weird interactions with Rayquazas HP barriers since he has 3? I'll get back with an edit once I've also checked the 195 fight.

Edit: The 195 fight did not perform this behavior

Edit2: I don't know how I missed this the first time, but the Rayquaza also went up a barrier from 2 to 3
Ray barrier

### PR DESCRIPTION
**Pull request by flx-sta**
add boss-segments to into pokemon-data & load it in EnemyPokemon constructor

## What are the changes?

I've added the boss segments number to the pokemon-data to persist it throughout reloads

fixes #1697

## Why am I doing these changes?

Previously (as described here: https://github.com/pagefaultgames/pokerogue/issues/1697#issuecomment-2189151817) the boss segments were inconsistent with hard-coded trainers. This should fix it

## What did change?

persisting the segments into the pokemon-data object (which is saved to the session)

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/50131232/da15b8ef-48f1-4770-aa23-985d66420e56

## How to test the changes?

overrides.ts
```ts
export const STARTING_WAVE_OVERRIDE: integer = 145;
```
- Start a new game
- count the boss sections on the first trainer pokemon
- reload
- continue
- check again -> Should be still 2

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
       - **The failing test is a known and not my fault!**
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by Tempo-anon — APPROVED** [review]
:goomed:

**Comment by Tempo-anon** [comment]
Slime has reported a possible bug of this while testing, so just a heads up.

**Comment by flx-sta** [comment]
Review from smile:
image
https://discord.com/channels/1125469663833370665/1244839350919888897/1255393259774148720

image
https://discord.com/channels/1125469663833370665/1244839350919888897/1255399479788699710

image
https://discord.com/channels/1125469663833370665/1244839350919888897/1255402962700992613

**Comment by flx-sta** [comment]
##Reproduction Video

https://github.com/pagefaultgames/pokerogue/assets/50131232/581d6952-87a9-4a60-8e6d-e15eb4271733

The same doensn't seem to happen on `main`

**Comment by flx-sta** [comment]
Now I'm not able to reproduce this. ....
I need a 3rd tester PLEASE

**Comment by Tempo-anon** [comment]
Seems like the issue observed is because of offline functionality.

**Pull request merged**
