### PR TITLE
[QoL] Giving Xurkitree Tail Glow

### PR DESCRIPTION
**Pull request by EvasiveAce**
## What are the changes?

I gave Xurkitree Tail Glow, since it is one of the only pokemon to learn it, and it was in the game in its moveset on Xurkitree's release.

## Why am I doing these changes?

Issue popped up wondering why it did not have it.

## What did change?

I gave Xurkitree's level 1 moveset Tail Glow.

### Screenshots/Videos

I will post some screenshots, and a video that shows it is indeed in its level 1 moveset.
image
image

[Video](https://github.com/pagefaultgames/pokerogue/assets/71776311/f2d9fb97-8fb3-46b1-a404-d00d6fed9bc3)

## How to test the changes?

Select Xurkitree or use override for its species. 

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by jaimefd — APPROVED** [review]
Just wanna add that I agree with this change. Xurkitree had the move in Gen 7, the only generation where both existed together, so this is fair. Bulbapedia shows entries in Gen 8 but that's only BDSP, SwSh (where Xurkitree existed) [did not have Tail Glow](https://bulbapedia.bulbagarden.net/wiki/Tail_Glow_(move)#Generation_VIII).

**Comment by RNGezeus** [comment]
When you said "did not have it" were you aware that it does have it, but its locked behind eggmoves?

**Comment by EvasiveAce** [comment]
> When you said "did not have it" were you aware that it does have it, but its locked behind eggmoves?

I was not aware. I apologize, I just saw an issue and looked at the level 1 moveset. Should I close PR?

**Comment by Tempo-anon** [comment]
Cleaning up the PR list so I will close this for now since Xurkitree currently has tail glow as an egg move.

**Pull request closed without merging**
