### PR TITLE
Make more phases strings translatable and add their spanish locale

### PR DESCRIPTION
**Pull request by PabloG02**

### CODE REVIEW

**Comment by Flashfyre** [comment]
Can we also add the English to the French file if we're adding new keys?

**Comment by PabloG02** [comment]
Done

**Review by Flashfyre — APPROVED** [review]

**Comment by Flashfyre** [comment]
Resolve conflicts and this is good to go

**Comment by PabloG02** [comment]
Rebased

**Review by Flashfyre — APPROVED** [review]

**Pull request merged**
