### PR TITLE
[Localization] Zh fix 8-14

### PR DESCRIPTION
**Pull request by mercurius-00**
## What are the changes?

adding missing translation for zh-CN and zh-TW

## Why am I doing these changes?

zh-TW missing a lot of translation

## What did change?

zh-CN small fix
update the zh-TW translation to match the progress of zh-CN.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by 40chyan — APPROVED** [review]

**Review by frutescens — COMMENTED** [review]
Hi, if possible, could you attach some screenshots of how the localization changes look in-game?

**Comment by frutescens** [comment]
Hi, please reach out to @pagefaultgames/english-translation-team if you have any questions about the new localization system + ping me once you make the changes. Thank you for your work :)

**Comment by Tempo-anon** [comment]
Please fix merge conflicts

**Comment by Tempo-anon** [comment]
Going to close this PR since it looks like Sangara is fixing the Chinese translations

**Pull request closed without merging**
