### PR TITLE
[QoL] Cursor memory setting

### PR DESCRIPTION
**Pull request by LeBulldoge**
## What are the changes?
This PR adds a new setting to control whether or not the game maintains the cursor at its last position between battles, inside the command and move menus. The possible values are:
* Off
* Commands
* Moves
* Both

The default value is `Both`, in line with current behavior.

## Why am I doing these changes?
I frequently find myself in a loop of sorts, as my mind is expecting the `Fight` button to be highlighted after each combat. This especially hurts if I managed to fumble the inputs last fight and hit `Run`.
However, I do find cursor memory for the move menu quite useful. This way players can pick and choose whichever setting feels best for them.
This should also close out #1398 

## What did change?
Added a new setting `Cursor memory`, which will let players control in which combat menus they want the last cursor position to be remembered.

### Screenshots/Videos
https://github.com/pagefaultgames/pokerogue/assets/13983982/a53d862c-bfce-4c58-a268-858cb682620d

## How to test the changes?
Change the setting to the desired value. While in combat, the cursor position should, or should not, be remembered on the command or move menus, according to the chosen value.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by flx-sta** [comment]
Does this also handle that the cursor memory is separate in tag-team fights?
If not, would be a good addition

**Comment by LeBulldoge** [comment]
> Does this also handle that the cursor memory is separate in tag-team fights? If not, would be a good addition.
> 
> Right now the previous choice of Pokemon 2 can affect the next choice of Pokemon 1 in the next turn (and the other way around same turn)

This PR doesn't change that and it probably shouldn't, seems like a whole separate bug. I wouldn't mind looking into it after this though. Is there an issue open for it?

**Comment by flx-sta** [comment]
> > Does this also handle that the cursor memory is separate in tag-team fights? If not, would be a good addition.
> > Right now the previous choice of Pokemon 2 can affect the next choice of Pokemon 1 in the next turn (and the other way around same turn)
> 
> This PR doesn't change that and it probably shouldn't, seems like a whole separate bug. I wouldn't mind looking into it after this though. Is there an issue open for it?

I don’t think there is. Try searching for it. Otherwise you can suggest it on their discord

**Comment by Tempo-anon** [comment]
Cool idea but this PR is a bit out of date and has merge conflicts. You're welcome to make a new PR for this feature though

**Pull request closed without merging**
