### PR TITLE
[Sprite] Fixed shinies for Zubat, Golett, female Garchomp

### PR DESCRIPTION
**Pull request by Fontbane**
Converted to draft while awaiting further instruction from the Head Artists.
## What are the changes?

- Fixed shiny/rare Zubat, Golbat, Crobat
- Fixed inconsistencies in Garchomp's shiny
- Fixed Golett's shiny front sprite still using base replacement

## Why am I doing these changes?

- Zubat was meant to have its base replacement removed. This was not done correctly, resulting in its shiny and rare variant colors being mixed up, and also different between male and female.
- Shiny Garchomp was also very slightly different based on gender which was unintentional.
- Golurk was meant to have its base replacement removed a month ago
image
image

## What did change?

- Zubat line entirely restored to original shiny color, male rare variants fixed
- Female Garchomp now matches male's colors
- Golett shiny front sprite fixed
- Removed entries in _masterlist.json for the genies and Palossand, whose base replacements were reverted (having their entries allowed their nonexistent variants to be caught)

### Screenshots/Videos

Before:
image
Screenshot_766
Screenshot_768
Screenshot_770
Screenshot_771
Screenshot_772
Screenshot_773
Screenshot_774
After:

Screenshot_775
Screenshot_776
Screenshot_777
Screenshot_778
Screenshot_779
Screenshot_780

## How to test the changes?

- Use a save file with every variant and shiny.
- Check every affected mon in game to see if their shinies/variants are correctly colored.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by chaosgrimmon** [comment]
did you ensure that all icons still match?

**Comment by chaosgrimmon** [comment]
also, i'm not sure why Crobat's paletteswap was replaced when it's not a BSR?
image
image

i don't believe any mobile user has complained about that one either, even.

**Comment by Fontbane** [comment]
> also, i'm not sure why Crobat's paletteswap was replaced when it's not a BSR? image image
> 
> i don't believe any mobile user has complained about that one either, even.

It wasn't replaced, just deleted. It's not needed since it has the sprite.

**Comment by chaosgrimmon** [comment]
yeah, but paletteswaps should be favoured since they impact the server load less. 
if that weren't the case, they wouldn't exist, since none of the artists go out of their way to make them, they just submit sprites in their submissions. sprite fixes wouldn't be necessary either, since you could just upload a variant sprite with whatever patterns you wanted

**Comment by Fontbane** [comment]
> yeah, but paletteswaps should be favoured since they impact the server load less. if that weren't the case, they wouldn't exist, since none of the artists go out of their way to make them, they just submit sprites in their submissions. sprite fixes wouldn't be necessary either, since you could just upload a variant sprite with whatever patterns you wanted

I see. Would it be kept as 1 in the master list then?

**Comment by chaosgrimmon** [comment]
yeah, so long as the json exists

**Comment by Fontbane** [comment]
> yeah, but paletteswaps should be favoured since they impact the server load less. if that weren't the case, they wouldn't exist, since none of the artists go out of their way to make them, they just submit sprites in their submissions. sprite fixes wouldn't be necessary either, since you could just upload a variant sprite with whatever patterns you wanted

Actually I'm not sure that's a good idea because palette swaps are broken on mobile in many cases

**Pull request closed without merging**
