### PR TITLE
Use getBattleStat instead of getStat in BattleStatRatioPowerAttr

### PR DESCRIPTION
**Pull request by JakubHanko**
Usage of getStat causes moves like Electro Ball to use incorrect Stat.SPD (SPD before it gets halved).

### CODE REVIEW

**Review by Flashfyre — APPROVED** [review]

**Review by Flashfyre — CHANGES_REQUESTED** [review]
Should this also pass opponent in for abilities like Unaware?

**Comment by JakubHanko** [comment]
> Should this also pass opponent in for abilities like Unaware?

I have two questions since my Pokémon skills are rusty:

1. correct me if I am wrong but Unaware should still respect the speed changes in case of Gyro Ball and Electro Ball
2. right now there aren't any moves in the game that fall into the BattleStatRatio category - are you aware of any moves that are somehow take the ratio of your and opponent's stats into consideration?

**Review by TempsRay — APPROVED** [review]
Unaware doesn't ignore speed so this should work fine.

Should probably rename the `BattleStatRatioPowerAttr` attr though, as it's only ever being used for 1 stat (speed) and 2 moves that have different calculations

**Comment by JakubHanko** [comment]
Decided to go with two classes, each dedicated to its respective move since both calculations are fairly specific to their use cases.

**Review by TempsRay — COMMENTED** [review]
Looks good and I guess it makes sense to separate out these as two classes. Please add some documentation to the new classes though

**Comment by JakubHanko** [comment]
TSDocs have been added.

**Review by Flashfyre — APPROVED** [review]

**Pull request merged**
