### PR TITLE
[QoL] Add TypeDoc as a Valid Doc Generator

### PR DESCRIPTION
**Pull request by bennybroseph**
TypeDoc auto generated documentation can now be generated from the project. This makes our code documentation even more important!

## Why am I doing these changes?

This allows us to either view the code base through standardized docs or use the output for a website that hosts these docs. This way someone does not need to open an IDE to parse through the code. It can all be done using a web browser.

## What did change?

- `.gitignore` to prevent versioning of docs since that can be generated locally for now.
- `package-lock` and `package` to install TypeDoc
- `tsconfig.json` so that running the command is as short and easy as possible

### Screenshots/Videos

image
image
image

## How to test the changes?

Run `npm install typedoc --save-dev`
then
Run `npx typedoc`

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by flx-sta — APPROVED** [review]
LGTM 🚀 

I'd recommend to add a script for that 
Something like `npm run docs`

```json
{
....
        "scripts": {
		....
		"docs": "typedoc"
	},
....
```

-------


https://github.com/pagefaultgames/pokerogue/assets/50131232/b68e6075-9ec0-4633-858d-1e08abcf8512



-------

_running `npm install typedoc --save-dev` is not necessary. simply run `npx typedoc`. The dependency is in the package.json `devDependencies` and if you need to install you probably didn't run `npm i` in the first place..._

**Comment by bennybroseph** [comment]
> There were a lot of warnings. are they to be expected?

Yes and no. It's people not commenting correctly. I didn't look at every single one yet (i'm going to fix them all at some point just like the errors) but it's just people copy pasting stuff incorrectly or not following the standards.

**Comment by bennybroseph** [comment]
> running `npm install typedoc --save-dev` is not necessary. simply run `npx typedoc`. The dependency is in the package.json `devDependencies` and if you need to install you probably didn't run `npm i` in the first place...

Yes, but those instructions were for someone pulling down the branch. Does npm auto update based on the package.json? I was assuming no

**Comment by bennybroseph** [comment]
> Something like `npm run docs`

Added, tested, works

**Comment by flx-sta** [comment]
> > running `npm install typedoc --save-dev` is not necessary. simply run `npx typedoc`. The dependency is in the package.json `devDependencies` and if you need to install you probably didn't run `npm i` in the first place...
> 
> Yes, but those instructions were for someone pulling down the branch. Does npm auto update based on the package.json? I was assuming no

it does not, no but `npx typedoc` will automatically tell you it needs to install that dependency if not there

**Comment by flx-sta** [comment]
> > There were a lot of warnings. are they to be expected?
> 
> Yes and no. It's people not commenting correctly. I didn't look at every single one yet (i'm going to fix them all at some point just like the errors) but it's just people copy pasting stuff incorrectly or not following the standards.

I expected that.
Well then you have a system in place to catch the culprits, might eben be able to use it in a github action to block PRs with warnings/errors

**Review by Tempo-anon — APPROVED** [review]

**Pull request merged**
