### PR TITLE
Add Korean Locale

### PR DESCRIPTION
**Pull request by MrWaterT**
There is the same problem with Chinese locale.

With font, file size is too big(2+MB), but without font, text size is too big,  
so only partially translated.

### CODE REVIEW

**Comment by MrWaterT** [comment]
I don't know which is better- partially translated language or unnecessarily loaded font file(for non-Korean),  
but anyway I pushed the commits for full translation: from ec7463e6.

* `pokemon-dppt` font is added since there is no Korean version in Generation III.  
It is used along with `pokemon-emerald-pro`, not in a beautiful way, though.
* `pkmnems` doesn't cause a big-letter-problem, so it is not replaced or else.

**Comment by MrWaterT** [comment]
I did some optimization on font loading: bc7c6b7

No longer useless font for Non-Korean user,
no longer huge text in Korean locale (except change locale handler),
no longer too much file changes for font styling.

**Comment by majaksin** [comment]
[ko.zip](https://github.com/pagefaultgames/pokerogue/files/15334355/ko.zip)
I didn't know there was someone who had already translated it.
This is the file I was working on.

**Comment by MrWaterT** [comment]
These are commits to resolve conflicts, including implicit.
Locale files and attributes are not old one anymore.
I wish reviewing is not ongoing yet (to prevent double work).

**Comment by bennybroseph** [comment]
@molker @Madmadness65 this adds a new license text file, not sure how to handle this

**Comment by MrWaterT** [comment]
I wrote my [own font file](https://github.com/MrWaterT/PokePT_Wansung) with pokemon-game-style.
So there isn't license issue now.

**Review by bennybroseph — DISMISSED** [review]

**Review by bennybroseph — APPROVED** [review]

**Comment by bennybroseph** [comment]
@MrWaterT thank you, truly for the effort put into this. I had to some minor fixes, but it's merged now. I'm so glad we support another language 🥇

**Comment by flx-sta** [comment]
@bennybroseph this merge broke the tests on `main`.
I've provided the fix for it in #1591

**Comment by returntoice** [comment]
requesting modifications on some translated name
바이옴 이름 관련 수정 건의할 게 있습니다.
일단 한국어화에 큰 역할 해 주신 점 감사드립니다. 다만 바이옴 이름 관련 좀 수정을 요청하고자 글을 써 봅니다. 깃허브에 익숙하지 않아 어떻게 하는 게 제일 좋은 방법일지 몰라 코멘트로 남깁니다.
현재 'ruins'가 '고대 폐허', 'space'가 '성층권', 'fairy cave'가 '요정 동굴'로 되어 있는데, 이 세 이름을 바꾸는 게 어떨까 싶습니다.
우선 'ruins'는 폐허긴 한데, 보통 '유적'의 의미로도 많이 쓰이는 단어이고, 원래 명칭에 'ancient'라는 말이 없기 때문에 간단하게 '유적'이라고만 하는 것이 더 좋지 않을까 싶습니다.
다음으로 'space'는 아마 원래 명칭이 'stratosphere'이어서 '성층권'으로 번역하신 것 같은데, 현재 영어 공식 명칭도 'space'로 되어 있기 때문에 간단히 그냥 '우주'라고 하는 게 좋지 않을까 싶습니다.
마지막으로 'fairy cave'의 경우, 현재 포켓몬에서는 공식적으로 '요정 타입'이 아니라 '페어리 타입'이라는 용어를 사용하는 점, 해당 바이옴에서 페어리 타입 포켓몬이 주로 출현한다는 점을 생각해 보면 '요정 동굴'보다는 '페어리 동굴'이 낫지 않을까 싶습니다.
수고하세요

**Comment by flx-sta** [comment]
@returntoice that's not the process for this.
You'd have to create a PR for these changes.
Eventually discuss them on Discord or something.

**Comment by MrWaterT** [comment]
> @returntoice that's not the process for this. You'd have to create a PR for these changes. Eventually discuss them on Discord or something.

It is finally discussed and merged in #1665. Thanks for all your effort.
(I saw comments in here soooo late)

I'm not a pro translator or something. More correct translations makes better game.
Just regard this PR as a blueprint, not a completed one.

**Comment by davidyan-hub** [comment]
I did not have envirement to do this...
Who can modify the text.ts to change the font-family and font-size for chinese.

Code as below:

fontFamily: localStorage.getItem('prLang')==="zh_CN"?'simhei':'emerald',

styleOptions.fontFamily = localStorage.getItem('prLang')==="zh_CN"?'MuZaiPixel':'pkmnems';

and same judgement logic for changing font-size, let the size is smaller.

**Pull request merged**
