### PR TITLE
Add candy jar jar

### PR DESCRIPTION
**Pull request by IceFire03**
The people love candy jars! This is the logical next step. Tested and fully functional :)

Example
Jar Jar Seal of Approval

### CODE REVIEW

**Comment by Flashfyre** [comment]
Just because you can doesn't mean you should.

**Comment by patapancakes** [comment]
where's the candy jar jar jar

**Comment by IceFire03** [comment]
in development

**Comment by Flashfyre** [comment]
Good for a laugh but as an actual feature it's a no from me.

**Comment by Admiral-Billy** [comment]
April fools inclusion?

**Comment by IceFire03** [comment]
aw, man... i had just implemented candy jar jar jar, too!

**Pull request closed without merging**
