### PR TITLE
French corrections to Toxic Orb and Flame Orb descriptions

### PR DESCRIPTION
**Pull request by Adri1**
## What are the changes?
Change French translation of Toxic Orb and Flame Orb.

## Why am I doing these changes?
The French description was too generic and did not provided the same amount of informations as the original custom English description made for Rogue.

## What did change?
French Toxic Orb and Flame Orb French descriptions

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)

### CODE REVIEW

**Comment by InnocentGameDev** [comment]
This was done to follow gen 9 descriptions, as discussed yesterday in the discord and the PR that added the translation.

English translation was also edited to match the game's so what are you translating from now exactly?

**Comment by Dakurei** [comment]
Yesterday we were told to keep the item description as it is in the last generation.

image

If it hasn't been done in English, that's their business, but the description in other languages corresponds to the game as agreed.

**Comment by InnocentGameDev** [comment]
> Yesterday we were told to keep the item description as it is in the last generation.
> 
> image
> 
> If it hasn't been done in English, that's their business, but the description in other languages corresponds to the game as agreed.

English matches the game's wording as well (since last night)

**Comment by Adri1** [comment]
> This was done to follow gen 9 descriptions, as discussed yesterday in the discord and the PR that added the translation.
> 
> English translation was also edited to match the game's so what are you translating from now exactly?

French description doesn't specify it that the holder should not have any status problem.
+ Even the English descrption is not follow the games descriptions at all.
image

**Comment by Dakurei** [comment]
> > Yesterday we were told to keep the item description as it is in the last generation.
> > image
> > If it hasn't been done in English, that's their business, but the description in other languages corresponds to the game as agreed.
> 
> English matches the game's wording as well (since last night)

Not currently according to the state of main
https://github.com/pagefaultgames/pokerogue/blob/b7ecebbc6e0be0632780765806c08fb7cee68f17/src/locales/en/modifier-type.ts#L212

**Comment by Adri1** [comment]
I admit, I do not understand that decition to the fathful to the games descriptions.
As the OG games not always provide clear description and might leave us in the fog on how somthing is supposed to work, it's the perfect occasion to be more precise and yet we miss that occasion on purpose.

**Comment by InnocentGameDev** [comment]
> > > Yesterday we were told to keep the item description as it is in the last generation.
> > > image
> > > If it hasn't been done in English, that's their business, but the description in other languages corresponds to the game as agreed.
> > 
> > 
> > English matches the game's wording as well (since last night)
> 
> Not currently according to the state of main
> 
> https://github.com/pagefaultgames/pokerogue/blob/b7ecebbc6e0be0632780765806c08fb7cee68f17/src/locales/en/modifier-type.ts#L212

I made a mixup where the proper English is correctly pasted in all the locales that are still untranslated, but the English one is still holding the old version. You're absolutely right

**Comment by InnocentGameDev** [comment]
> I admit, I do not understand that decision to be faithful to the games descriptions word by word. OG games do not always provide clear and complete descriptions and might leave us in the fog on how somthing is supposed to work. It's the perfect occasion to be more precise and yet we decide to miss that occasion on purpose.

I agree with you but I don't make the rules.

**Comment by Tempo-anon** [comment]
This sounds like it'd require a deeper dive from the development team on how we want to handle localizations. Do we want to stick with the canon in-game text for all things or should there be some flexibility?

**Pull request closed without merging**
