### PR TITLE
[Localization] Spanish modification form es to es-ES

### PR DESCRIPTION
**Pull request by Adri1**
## What are the changes the user will see?
"Español" becomes "Español (ES)" in Game Settings

## Why am I making these changes?
To prepare the future implementation of LATAM Spanish (es-MX)

## What are the changes from a developer perspective?
All "es" labels got changed into "es-ES"

### Screenshots/Videos
Screenshots taken after the edits
image
image

## How to test the changes?
Set the game in Spanish

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by MokaStitcher — CHANGES_REQUESTED** [review]
This require changes in the locales repo, right? Because when testing with the current beta locales folder everything is in English as a result when I change the language to es-ES.
How should we proceed to time PRs on both sides? (can discuss this on discord)

There may be other spots in the game that use the locale, the event banner being one of them. Please update the name of the banner for the current event `public/images/events/halloween2024-event-es.png` to  `halloween2024-event-es-ES.png`

For it all to work you will also need to change `es` to `es-ES` here:

https://github.com/pagefaultgames/pokerogue/blob/fb2d3e45d617164eab37f4c70d30ad7cd1215e59/src/loading-scene.ts#L247

and here:

https://github.com/pagefaultgames/pokerogue/blob/fb2d3e45d617164eab37f4c70d30ad7cd1215e59/src/timed-event-manager.ts#L38

**Comment by Adri1** [comment]
> This require changes in the locales repo, right?

Yes, just rename the Spansh repo into es-ES. The PR in the locales repo is ready, but I just wait for this ont to merge the modifications in the locale repo

**Comment by MokaStitcher** [comment]
> The PR that modifies it in the locales repo is ready, I just wait for this one to merge the modifications in the locale repo

Ok, but in order for the locale changes to propagate to beta once they are in, we need a PR on our side to point to that version of the locales repo. So I think once this PR has enough approvals and I'm ready to merge it I'll let you know, you'll merge the locale PR, and update this PR to point to the latest locale commit. And then we merge this PR. This way beta will not sit with Spanish not working for a while. Hope that makes sense!

**Comment by MokaStitcher** [comment]
Went ahead and made sure there was no more missed "es" stuff.
Made a [PR to your repo](https://github.com/Adri1/pokerogue/pull/22) to fix those I found

**Review by MokaStitcher — DISMISSED** [review]

**Review by CodeTappert — APPROVED** [review]

**Review by MokaStitcher — APPROVED** [review]

**Pull request merged**
