### PR TITLE
Minor text corrections to item descriptions.

### PR DESCRIPTION
**Pull request by Argenrost**
Realized after posting to Issues last night that I could very easily make this change myself. ¯\_(ツ)_/¯

Should be pretty non-invasive as it's only altering text display.

### CODE REVIEW

**Review by Flashfyre — CHANGES_REQUESTED** [review]
Periods were omitted on purpose since they're sentence fragments, not sentences.

**Comment by Argenrost** [comment]
Hadn't considered that before. Something about it still feels off to me personally, and upon investigating item descriptions used in original Pokemon games it seems they don't follow this rule, they simply cap everything off with a period as I believe most games do for item descriptions even if they're technically formatted as sentence fragments.

Regardless, I'll respect the governing logic of this project, so I made some additional tweaks I wanted to provide context on:

- Several changes from "restore" and "increase" to "restores" and "increases", as this not only matches original game descriptions but is also better formatting to keep consistency with these being sentence fragments as opposed to command statements
- Lenses changed from "(up to 100)" to "(maximum 100)" to keep consistency with other items using similar designations
- Some words were capitalized in descriptions including "Revives", "Shiny", and "Hidden Ability", as these are specific in-game item/effect designations that are always capitalized when referred to otherwise
- Some items were left with the added periods due to their descriptions being actual sentences and not fragments

**Review by Argenrost — COMMENTED** [review]
Duplicate comment because I briefly forgot GitHub workflow.

**Review by Argenrost — COMMENTED** [review]
Changes explained and justified in above comment.

**Review by Flashfyre — APPROVED** [review]

**Pull request merged**
