### PR TITLE
Promise Rework

### PR DESCRIPTION
**Pull request by molker**
This is the beginning of a big cleanup, please test thoroughly

### CODE REVIEW

**Comment by DustinLin** [comment]
just saw this, seems like it will conflict with the changes I made in PR #783

**Comment by molker** [comment]
> just saw this, seems like it will conflict with the changes I made in PR #783
> 
> skimming through there will me merge conflicts, but doesn't seem like the functionality or the change will be impacted? Especially looking at `pokemon.ts` and `phases.ts`

No part of this should change functionality, its cleaning up the code to be more readable and use async/Promises cleaner

**Comment by DustinLin** [comment]
looked and did some testing (with my changes) and everything seems ok from my perspective

**Comment by DustinLin** [comment]
small thing i noticed though is multi-hit move animations are faster now? check out the 2 clips

---- NEW


https://github.com/pagefaultgames/pokerogue/assets/39450497/73921078-656f-492d-be5c-1f094f7c8ada



---- OLD

https://github.com/pagefaultgames/pokerogue/assets/39450497/87f4fbb0-d2dc-425f-b31a-9e16b6d0a50b

**Comment by molker** [comment]
closing this to restart and test more thoroughly along the way

**Pull request closed without merging**
