### PR TITLE
Added more trainer classes

### PR DESCRIPTION
**Pull request by Alekemon**
Rework of the firebreather pull request. List of trainers added:

1. Camper (with female Picknicker variant): Uses Normal, Grass, Water and Fire type Pokémon
2. Firebreather: Uses Pokémon who can learn Smog
3. Sailor: Uses Water and Fighting type Pokémon
4. Prisoner: Uses Steel and Dark type Pokémon.

Sprites are from HGSS (Camper, Picknicker, Firebreather and Sailor), and King_Waluigi made the Prisoner sprite

### CODE REVIEW

**Comment by Alekemon** [comment]
> Minor nitpick, is Chantey supposed to be Shanty for Sailor trainer types?

Oh thanks for that, yep, it was supposed to

**Comment by Alekemon** [comment]
I marked as draft because I was missing trainer named

**Comment by bennybroseph** [comment]
Can these be split into separate PR?

**Comment by Alekemon** [comment]
> Can these be split into separate PR?

I'll put this PR as a draft for now, I see what I'll do for that

**Comment by Alekemon** [comment]
Splitting this into different PRs

**Pull request closed without merging**
