### PR TITLE
Issue #1118 Added Galar Elite 4

### PR DESCRIPTION
**Pull request by CodeTappert**
Fixes [#1118](https://github.com/pagefaultgames/pokerogue/issues/1118)

Added Galar Elite 4 with their teams from (https://www.pokewiki.de/Champ-Turnier_(nach_dem_Galar-Star-Turnier)) (Their strongest team in the Champ-Cup after you beat the Galar Star Cup. This one https://bulbapedia.bulbagarden.net/wiki/Galar_League)

Marnie:
image

Nessa:
image

Allister:
image

Raihan:
image

As planned Leon appears after them:
image

I added Marnie, Nessa, [Bea,Allister],Raihan as this is what you fight in the first champ cup (minus Hop and Bede to keep it to type themend trainers).

We could also have Marnie be optional with Bede since he is a fairy type trainer. So like one of them will appear.

### CODE REVIEW

**Comment by TempsRay** [comment]
Admittedly I'm not too familiar with Sword/Shield, but how did the gym leaders and elite four work in that game?

Will this make the champions line up with the proper E4s now? Also, should there be new voucher options made for them as they are new E4 members?

**Comment by CodeTappert** [comment]
So i looked it up ingame. 

There are different vouchers.

See here for their gym leader appearance:
image

And here for their elite 4 appearance
image

**Review by jaimefd — APPROVED** [review]
Looks amazing, thank you for this

**Comment by CodeTappert** [comment]
This PR is ready to be reviewed/merged by a dev.

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
