### PR TITLE
[Localization]Add chinese type icons

### PR DESCRIPTION
**Pull request by mercurius-00**
## What are the changes?

Add chinese type icons

## What did change?

- public/images/types_zh-CN.png
- public/images/types_zh-TW.png

### Screenshots/Videos

before

after

## How to test the changes?

1. Set the language to ”简体中文“ or “繁體中文” in Settings
2. Enter a battle
3. Select ”Pokemon“
4. Select “Summary”

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by Tempo-anon — COMMENTED** [review]
Personally the thickness of the text makes it a bit hard to read for me but I'll leave it up to the Chinese translation team to decide if this is okay or not

**Comment by mercurius-00** [comment]
> Personally the thickness of the text makes it a bit hard to read for me but I'll leave it up to the Chinese translation team to decide if this is okay or not

Yep. It is kind of difficult to display Chinese in 10 pixs

**Comment by CodeTappert** [comment]
Like i said already in another place. Maybe its time to switch to more modern type icons

**Comment by 40chyan** [comment]
“飞” → “飞行”
font can be better, try using a 12px pixel

**Comment by 40chyan** [comment]
also the shadow color of psychic is wrong
but We've made a new one in the pr below, feel free to join discord and contact or discuss more with other cn translators

#2639

**Comment by Tempo-anon** [comment]
Closing because #2639 was merged in

**Pull request closed without merging**
