### PR TITLE
[Localization][ko] StatRose, StatFell Message Fix

### PR DESCRIPTION
**Pull request by layharu0**
## What are the changes?

StatRose, StatFell message fix on localization of battle

## Why am I doing these changes?

First, some message was improperly translated.
Second, i think message need to be same as original game.

## What did change?

rose/fell => 올라갔다/떨어졌다
sharply rose/fell => 크게 올라갔다/떨어졌다
drastically rose/fell => 매우 크게 올라갔다/떨어졌다
wontgoany higher/lower => 더 이상 올라가지/떨어지지 않는

### Screenshots/Videos

statrose

## How to test the changes?

On local

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by sodaMelon** [comment]
hi. translation is correct.(i m native korean) but you can't pass test. check details.

**Comment by sodaMelon** [comment]
유닛 테스트 통과 안되셨으니 확인해보세요.
your pull request can't pass unit test. check them and fix them right

**Comment by EnochG1** [comment]
I think you should modify test file also.
/test/lokalisation/battle-stat.test.ts

**Comment by EnochG1** [comment]
조사로 인해 테스트 코드 통과가 안되는 것 같아 아래와 같이 수정 제안드립니다.
I suggest you to modify test code to pass test script for [[가]], [[는]].

file : /src/test/lokalisation/battle-stat.test.ts
198~204번째줄 수정 / modify 198~204 line
```typescript
    it("Test getBattleStatLevelChangeDescription() in 한국어", async () => {
    i18next.changeLanguage("ko", () => {
      battleStatLevelUnits.forEach(unit => {
        const processor = new KoreanPostpositionProcessor();
        const message = processor.process(koBattleStat[unit.key]);
        testBattleStatLevelChangeDescription(unit.levels, unit.up, message);
      });
    });
  });
```

같은 파일 24번째줄에 import문 추가 / modify same file, add import
```typescript
import { KoreanPostpositionProcessor } from "i18next-korean-postposition-processor";
```

**Comment by layharu0** [comment]
Ok I check that. Thank for help!
확인 감사합니다.

**Comment by layharu0** [comment]
I do what you say in comment, unit test is done. :D

**Comment by CodeTappert** [comment]
So the koreans on the wiki discord wanted me to do this PR:
https://github.com/pagefaultgames/pokerogue/pull/2292

Which as far as i see it has different text.

Can you please use 
https://abcboy101.github.io/poke-corpus
or any other source (please provide it)
and use the OFFICAL text from the games?

**Comment by layharu0** [comment]
> So the koreans on the wiki discord wanted me to do this PR: #2292
> 
> Which as far as i see it has different text.
> 
> Can you please use https://abcboy101.github.io/poke-corpus or any other source (please provide it) and use the OFFICAL text from the games?

difference of your's text and my text is used "상승했다" or "올라갔다" in stat rose. they are same meaning, but official use "올라갔다" like this

statrose_2

**Comment by EnochG1** [comment]
@CodeTappert 
Also, korean has dynamic postposition depends on pre-word so it should be added.
That's the reason there's [[가]] or [[는]]

image
image

**Comment by Tempo-anon** [comment]
I merged in #2292 is this still needed?

**Review by EnochG1 — APPROVED** [review]
LGTM!
I hope this commit should merge to main ASAP.
Because the word "약간" is incorrect ("약간" means 'a little', totally different with 'Sharply')
So many korean users are confused now.

**Comment by EnochG1** [comment]
@Tempo-anon 
In my opinion, this request is more close translation with original game.
(Cause of postposition using i18next-korean-postposition-processor and symbol at the end of sentence.)
Hope you review this request after resolve conflicts. (CC : @layharu0)

**Comment by layharu0** [comment]
i resolve conflicts. thanks to help @EnochG1

**Review by Tempo-anon — APPROVED** [review]
Ok I'll merge this one in then. If there's still issues with localization feel free to open another PR

**Pull request merged**
