### PR TITLE
Issue#613 Prevent evo item use on none base form Pokes

### PR DESCRIPTION
**Pull request by JackGilham**
Issue#613.

Have added additional EvolutionItemModifierType condition that prevents non-base form mons from taking Evo Items.

Fixes scenarios like where you may have a GMAX Pikachu and some other Thunderstone evo mon on your team:
1) Shop offers Thunderstone because of other evo mon
2) You are able to use Thunderstone on GMAX Pikachu because no form check.
3) GMAX Pikachu eats Thunderstone and nothing happens due checks/fails during evo.

### CODE REVIEW

**Comment by bennybroseph** [comment]
Does this work for fusions as well?

**Comment by JackGilham** [comment]
It does indeed. See attached gifs for pre-patch behavior and post-patch behaviour.
Pre-Fix
Post-Fix

**Comment by bennybroseph** [comment]
Does this also remove the item from the pool when it can't apply?

**Review by bennybroseph — APPROVED** [review]

**Comment by Snailman11** [comment]
Probably closes (Cosplay Pikachu can use thunderstone to no effect)
https://github.com/pagefaultgames/pokerogue/issues/1787

**Comment by Snailman11** [comment]
Discord Bug report (pikachu + thunderstone)
https://discord.com/channels/1125469663833370665/1248678817275318353

**Pull request merged**
