### PR TITLE
Update inputs-controller.ts

### PR DESCRIPTION
**Pull request by tsutsurana**
Updating Button.Action in inputs-controller.ts in order to Add Y as a viable input method to confirm menus.

### CODE REVIEW

**Comment by CodeTappert** [comment]
Yes Please. It is so annoying that it only works for Z atm

**Comment by bennybroseph** [comment]
Are there other common layouts that we don't support properly?

**Comment by tsutsurana** [comment]
QWERTZ is the main one that comes to mind for me personally, but basically any Layout that doesn't have Z besides X is either a reach or requires remapping / changing the layout to play with keyboard.
Optimally there should be a remapping system to map the actions to whatever a user wants, but I currently lack the knowledge to implement that.

**Comment by CodeTappert** [comment]
Dont the french have something completly different?

**Comment by bennybroseph** [comment]
Yeah, unfortunately that opens up a weird can of worms. AZERTY has W where z normally is and that obviously cannot be mapped here. I think we should just wait until our keybind remapping PR is finished instead of making an exception here.

**Pull request closed without merging**
