### PR TITLE
Fixes status immunity abilities not showing on UI

### PR DESCRIPTION
**Pull request by notpatchmaybe**
Status abilities ( Limber, Insomnia, Immunity, Magma Armour, Water Veil, Vital Spirit, Leaf Guard, Sweet Veil, Water Bubble, Pastel Veil, Thermal Exchange, Purifying Salt ) will now show on the left ability/passive pane when they successfully immune a status, and correctly send their chat box message. [Example](https://imgur.com/aJ5aMSj)

The change in the applyPreSetStatusAbAttrs removes the !simulated arg so that the message doesn't get suppressed by .attr.
The change in getTriggerMessage is because after getting the trigger message to actually show, turns out it never worked and just produced undefined. Instead it accesses the immuneEffects array.

One bug still remains in the sleep prevention abilities, as yawn is handled by BattlerTagImmunityAbAttr which would need another fix to properly send a chat message.

### CODE REVIEW

**Comment by CodeTappert** [comment]
Could you maybe think already about localization?

**Comment by notpatchmaybe** [comment]
> Could you maybe think already about localization?

What is there for me to think about? None of this PR even affects plain text...

**Comment by CodeTappert** [comment]
> > Could you maybe think already about localization?
> 
> What is there for me to think about? None of this PR even changes plain text?

Oh sorry. I was not aware that the hardcoded english text was already there before your PR: Then nevermind

**Comment by Xavion3** [comment]
What if you just change it from `!simulated` to `simulated`? Rewriting a function signature kinda suss too, but doing that and entirely deleting an argument's functionality just to patch over slightly faulty logic seems like a bad idea.

**Pull request closed without merging**
