### PR TITLE
[Dev] Add new lint rules

### PR DESCRIPTION
**Pull request by torranx**
# Only relevant file here is `eslint.config.js`, other changes were generated from running `npm run eslint`

## What are the changes the user will see?
n/a

## Why am I making these changes?
enforce code style consistency

## What are the changes from a developer perspective?
Rules added:
```
"array-bracket-spacing": ["error", "always", { "objectsInArrays": false, "arraysInArrays": false }], // Enforces consistent spacing inside array brackets
"object-curly-spacing": ["error", "always", { "arraysInObjects": false, "objectsInObjects": false }], // Enforces consistent spacing inside braces of object literals, destructuring assignments, and import/export specifiers
"computed-property-spacing": ["error", "never" ], // Enforces consistent spacing inside computed property brackets
"space-infix-ops": ["error", { "int32Hint": false }], // Enforces spacing around infix operators
"no-multiple-empty-lines": ["error", { "max": 2, "maxEOF": 1, "maxBOF": 0 }], // Disallows multiple empty lines
```
- [object-curly-spacing](https://eslint.style/rules/js/object-curly-spacing)
- [array-bracket-spacing](https://eslint.style/rules/js/array-bracket-spacing)
- [computed-property-spacing](https://eslint.style/rules/js/computed-property-spacing)
- [no-multiple-empty-lines](https://eslint.style/rules/js/no-multiple-empty-lines)
- [space-infix-ops](https://eslint.style/rules/js/space-infix-ops)

**errors from these rules, if any, could easily be fix by running `npm run eslint`**

## How to test the changes?
n/a

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by KimJeongSun — COMMENTED** [review]
LGTM! ( However, I'm not very familiar with the eslint configuration, so I would appreciate it if another dev could check this part. )

**Review by CodeTappert — APPROVED** [review]

**Comment by DayKev** [comment]
Why does fixing merge conflicts have to be so hard...

**Comment by DayKev** [comment]
Oh I see what happened. I disagree with the `[ lspace, rspace ]` changes, if only because that clashes with VSCode's built-in auto-formatting and idk how to change its rules (but also because I slightly prefer no spaces for those).

**Comment by torranx** [comment]
> Oh I see what happened. I disagree with the `[ lspace, rspace ]` changes, if only because that clashes with VSCode's built-in auto-formatting and idk how to change its rules (but also because I slightly prefer no spaces for those).

I've asked on discord and they like the one with spaces more

**Comment by flx-sta** [comment]
> Oh I see what happened. I disagree with the `[ lspace, rspace ]` changes, if only because that clashes with VSCode's built-in auto-formatting and idk how to change its rules (but also because I slightly prefer no spaces for those).

A simple `eslint --fix` will get you through the door. No worries.

It at all looms from the fact that we...
### ...still don't have a code-formatter!

**Review by flx-sta — APPROVED** [review]

**Review by ben-lear — APPROVED** [review]
Lgtm

**Review by DayKev — DISMISSED** [review]

**Review by DayKev — APPROVED** [review]

**Comment by DayKev** [comment]
That's a lot of merge conflicts lol

**Review by DayKev — APPROVED** [review]

**Review by flx-sta — DISMISSED** [review]
I've just looked at `eslint.config.js` so I hope that's sufficient

**Review by DayKev — APPROVED** [review]

**Review by DayKev — APPROVED** [review]

**Review by frutescens — APPROVED** [review]

**Review by xsn34kzx — APPROVED** [review]

**Pull request merged**
