### PR TITLE
[Visual] Achievements / Voucher Icons

### PR DESCRIPTION
**Pull request by frutescens**
This PR converts the 'generation one, generation two, generation three...' wording to the standard "Generation I, Generation II, ..." English wording. In addition, it will add distinct icons for each MonoGen achievement. It also replaces Voucher Unlocks with Gym Badges.

## What are the changes?
- Roman Numerals for Generation Numbers
- Achievement Icons to Ribbons
- Voucher Unlocks to Gym Badges

## Why am I doing these changes?
I think it would be cool! It would also be a nice homage to the base games. 

## What did change?
- English Text 
- (In the works...) I am searching for artists to help implement these ribbons and gym badges. 

Additional details will be added to this description as I get more assets. This will remain in draft until I acquire everything. 
[X] Wording
[X] MonoGen Ribbons
[ ] Voucher Unlocks

### Screenshots/Videos
image

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by frutescens** [comment]
Implemented Mono-Gen Ribbons
image

**Comment by 40chyan** [comment]
is there any references in the original games in terms of these ribbon sprites?

**Comment by frutescens** [comment]
Yes, these ribbons are based on those given by the base games.  https://bulbapedia.bulbagarden.net/wiki/List_of_Ribbons_in_the_games

The Gen I ribbon is the Champion Ribbon (from FRLG) since Gen III can be represented with a ribbon from ORAS. 
Only Gen II and Gen V do not have ribbons. Gen II's ribbon is the Legend Ribbon which was given to the player for defeating Red in HGSS. Gen V is based on the Royal Ribbon because of its story line and similar coloration to N's hair.

**Comment by frutescens** [comment]
Progress so far... 
image

**Comment by frutescens** [comment]
image

**Comment by Tempo-anon** [comment]
@frutescens do you mind making a PR of just changing the achievement icons to the new ribbons? Not sure about all the badges yet but the new ribbons look nice

**Comment by frutescens** [comment]
Ok! The badges are almost done though (unless you want to wait for the Evil Team logos)

**Comment by Tempo-anon** [comment]
> Ok! The badges are almost done though (unless you want to wait for the Evil Team logos)

I think since the ribbons are done first you can just put those in their own PR so I can get the other devs to take a look at that. Then in a separate PR you can add in the rest of the icons since those go in the vouchers menu while the ribbons go in the achievement menu and one of the things I sort of want to prioritize is removing all voucher icons in the achievement menu to prevent user confusion

**Comment by frutescens** [comment]
aye aye 
https://github.com/pagefaultgames/pokerogue/pull/2617

**Comment by flx-sta** [comment]
@frutescens  closed for being stale (no updates for over a month)

----

Feel free to create a new PR or ask us to re-open this one.

**Pull request closed without merging**
