### PR TITLE
Drop Shadow Fixes On Team Builder Screen

### PR DESCRIPTION
**Pull request by zaccie**
What it originally looked like
68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f313234313136343538313939373531303635362f313234323534313731393732383239353933362f696d6167652e706e673f65783d36363465333661372669733d3636

Left is what it became after my changes, right is an attempt to fix this
textfix

### CODE REVIEW

**Comment by zaccie** [comment]
I'm not used to github stuff so unsure if its normal for all the changes I made in the other PR to appear here etc
just looking at "Fixed Broken Drop Shadows" change

**Comment by admsev** [comment]
@gooroo-dev, @gooroo-ai please review

**Comment by admsev** [comment]
@gooroo-dev please review

**Comment by bennybroseph** [comment]
Nah, you'll need to update your branch from main. That way it only shows changes in this PR and not from your last one

**Pull request merged**
