### PR TITLE
[Feature] Add setting for rival gender

### PR DESCRIPTION
**Pull request by AbbyStrawby**
## What are the changes?

This change allows you to set which rival character gender you fight. It adds an option to the display settings under Player Gender. 

## Why am I doing these changes?

This change enables setting the rival gender/character independently of the player character's gender, allowing you to play as a boy and have Finn as a rival or play as a girl and have Ivy as a rival in addition to being able to have a rival of the opposite gender. 

## What did change?

Changes were made to src/battle.ts, src/system/game-data.ts, and src/system/settings/settings.ts to introduce a new setting to manually set the rival gender. Specifically, a new `SettingKeys` member was added, as well as supporting code to correctly update/save that setting & apply it to the trainer instance in the relevant battles.

### Screenshots/Videos

image
image

## How to test the changes?

Set src/override to any wave with a rival fight (8, 25, 55, 95, 145, and 195). Go into settings > Display and toggle the rival gender to Girl. When starting a new save, ensure Ivy appears as the rival you fight and the expected dialogue is present.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
         - Before making any changes, 9 unit tests related to input were failing. Afterwards, those same 9 were failing, so these are likely unrelated to our changes.
- [x] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by EvasiveAce** [comment]
Is it purely based on the player's gender on who you get? If so: I would personally rather it be random than adding an option.

**Comment by Tempo-anon** [comment]
Duplicate of https://github.com/pagefaultgames/pokerogue/pull/212. Not currently planned at this time due to ending CGs.

**Comment by AbbyStrawby** [comment]
> Is it purely based on the player's gender on who you get? If so: I would personally rather it be random than adding an option.

No the change is not based on the player's gender. You get to choose which rival you fight regardless of what gender you choose as the player. You can be the girl trainer and choose to have either Finn or Ivy as your rival or you can choose to be the boy trainer and have either Finn or Ivy.

We did consider also adding an option to randomize what rival you fight, but that would need to save the setting into the save file as opposed to being a setting you can change at any time, which would require it be a gameplay setting for something that's realistically just a cosmetic change.

**Comment by AbbyStrawby** [comment]
> Duplicate of #212. Not currently planned at this time due to ending CGs.

@Tempo-anon Hello, I was hoping to ask a clarifying question about this being closed. To my understanding the reason this feature isn't being implemented currently is because of the CGs when you win a run, which currently just feature the default pairs of rivals, and so having this setting without having CGs match your current settings would be immersion breaking.

If I were to draw or commission matching victory screens for the other two pairs of player character/rival combos, would this feature then be able to be implemented?

**Comment by Tempo-anon** [comment]
> > Duplicate of #212. Not currently planned at this time due to ending CGs.
> 
> @Tempo-anon Hello, I was hoping to ask a clarifying question about this being closed. To my understanding the reason this feature isn't being implemented currently is because of the CGs when you win a run, which currently just feature the default pairs of rivals, and so having this setting without having CGs match your current settings would be immersion breaking.
> 
> If I were to draw or commission matching victory screens for the other two pairs of player character/rival combos, would this feature then be able to be implemented?

I don't know how the rest of team feels but for me personally, I'd feel that this might be considered if there were ending CGs of comparable quality and aesthetics. I believe the artist for the trainer designs and the ending cg's is pkmn_realidea

**Pull request closed without merging**
