### PR TITLE
[QoL] Summary Option for Caught Pokemon

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes?
When a player's party is full, they are presented with yes/no options to add the Pokemon to the party or release the newly caught Pokemon. This adds a 'SUMMARY' option so that the player could look at the caught Pokemon's summary before making a decision. 

## Why am I doing these changes?
I decided to make these decisions following a discussion in the Discord about the UI and the player's access to essential information regarding party formation. In addition, this feature brings PokeRogue in line to the mainline Pokemon games, which do allow the player to look at the summary page of a newly caught Pokemon. 

## What did change?
This alters the presentation of confirm-ui-handler.ts when a new Pokemon is caught and the player's party is at max from {YES, NO} to {SUMMARY, YES, NO}
In addition, it changes summary-ui-handler.ts behavior in regards to the cancellation button using differences found in setModeWithoutClear() and setMode(). The video will be also demonstrating that the Summary-UI in other occasions has not been altered in behavior in the comments. 

### Screenshots/Videos
Please see Discord. 

## How to test the changes?
Catch a Pokemon with a full party. 

## Checklist
- [ x ] There is no overlap with another PR?
- [ x ] The PR is self-contained and cannot be split into smaller PRs?
- [ x ] Have I provided a clear explanation of the changes?
- [ x ] Have I tested the changes (manually)?
    - [ x ] Are all unit tests still passing? (`npm run test`)
- [ x ] Are the changes visual?
  - [ x ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by frutescens** [comment]
Video Link : 
https://discord.com/channels/1125469663833370665/1249614808400007198/1249614995981864993

**Comment by frutescens** [comment]
My local files weren't updating correctly, which is why Summary is in all caps in the video above. It should be working now. 
image

**Comment by HopsWas** [comment]
Found several issues with this PR. Firstly being the text " Summary " is still capitalized. Secondly, if you scroll down while looking at the summary for the caught pokemon, You can view your party instead, which is only an issue due to the fact that you can then no longer scroll back up to see the summary of the caught pokemon. Thirdly, When pressing back to exit the summary menu, the catch text is once again proc'd, causing you to gain additional catch rewards, IE infinite candy. 
Summary text:
image_2024-06-10_005929952
Repeat catch rewards:
image
image

**Comment by frutescens** [comment]
Thank you for testing this.
For the first issue, I believe that you have to update your repository files. There's been many localization updates added recently. 
I will push a fix for the other issues soon.

**Comment by frutescens** [comment]
See Discord for video of fixed version. (Video size too big once again)

**Comment by knispeja** [comment]
The stats window isn't getting moved far enough over anymore, probably because the confirm window width [here](https://github.com/pagefaultgames/pokerogue/blob/5bdc6537e0f4b2dc9fb7622dfe59724253c689c9/src/ui/confirm-ui-handler.ts#L9) is no longer correct

**Comment by frutescens** [comment]
Thank you for taking a look at this PR.
I made some changes to fit your suggestions. 
image

**Comment by frutescens** [comment]
Image to show that changes to makeRoomForConfirmUi do not change other uses of ConfirmUI
image

**Comment by frutescens** [comment]
Closing Branch because I suck at Git

**Comment by frutescens** [comment]
Reopened here: https://github.com/pagefaultgames/pokerogue/pull/2242

**Pull request closed without merging**
