### PR TITLE
Edited Electro Shot to raise stat before attacking

### PR DESCRIPTION
**Pull request by EmoUsedHM01**
Should be a fix to issue #85

### CODE REVIEW

**Comment by LaukkaE** [comment]
I dont think this does anything.

**Comment by EmoUsedHM01** [comment]
> I dont think this does anything.

Yes, swapping the order of the StatChangeAttr and ElectroShotChargeAttr functions would change the execution order. In the modified code snippet, StatChangeAttr will be applied before ElectroShotChargeAttr. Therefore, the stat change will occur first, followed by the gathering of electricity on the first turn.

I tested this myself, but feel free to verify

**Comment by molker** [comment]
Just tested this, changing the order of the lines doesn't effect when the buff is applied

**Comment by EmoUsedHM01** [comment]
Super weird, running the whole thing through my IDE shows the function executing in that specific order, I'll take a second look and then test on a localhost

**Comment by EmoUsedHM01** [comment]
Ahhh I see the issue, my IDE is still set up for Lua. In TypeScript, the order of function calls inside the constructor doesn't affect the order in which those functions are executed. My bad then, I'll likely take another look into the ElectroShotChargeAttr function then and see about changing the whole thing through that

**Comment by EmoUsedHM01** [comment]
Finished updating and tested the skill inside and outside rain, functions as intended now

**Review by Flashfyre — CHANGES_REQUESTED** [review]
Needs formatting fixed before I approve this

**Review by Flashfyre — APPROVED** [review]

**Pull request merged**
