### PR TITLE
New growth rate lang files

### PR DESCRIPTION
**Pull request by ArceUseless**
Added new growth rates lang files for all langs

### CODE REVIEW

**Comment by molker** [comment]
Please check the new i18n file changes

**Comment by ArceUseless** [comment]
> Please check the new i18n file changes

I meant to do a pull request for main pokerogue not this, sorry

**Comment by ArceUseless** [comment]
> Please check the new i18n file changes

I think it's ok now

**Comment by Flashfyre** [comment]
> > Please check the new i18n file changes
> 
> I think it's ok now

You reverted the changes that separated the references into its own config.

**Comment by ArceUseless** [comment]
> > > Please check the new i18n file changes
> > 
> > 
> > I think it's ok now
> 
> You reverted the changes that separated the properties into their own config.

You mean the nature config in the i18 file from my previous PR, right?

**Comment by rnicar245** [comment]
@Flashfyre this should be ready

**Review by Madmadness65 — APPROVED** [review]

**Pull request merged**
