### PR TITLE
[Balance][Daily] Give the Player a Map in Daily Run

### PR DESCRIPTION
**Pull request by RedstonewolfX**
## What are the changes the user will see?
When the player starts a Daily Run, they will start with a Map in addition to the 3 Golden EXP Charms.

## Why am I making these changes?
I already did this in my [previous](https://github.com/pagefaultgames/pokerogue/pull/3776) pull request, but wasn't able to get this out until I also got the tests done for the other two features - something that was very hard, and which I still haven't been able to do yet.

## What are the changes from a developer perspective?
Almost nothing. Adds two lines of code.

### Screenshots/Videos
(Copied from original PR)
image

## How to test the changes?
Open a Daily Run. You'll have a Map.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [ ] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by DayKev** [comment]
Welp I have no idea how to make the newly broken test continue past the `SelectBiomePhase`, no matter what I do it refuses to accept button presses.
```ts
    // you'd think this would work but no
    game.onNextPrompt("SelectBiomePhase", Mode.OPTION_SELECT, () => {
      const optionSelectUiHandler = game.scene.ui.getHandler() as OptionSelectUiHandler;
      optionSelectUiHandler.processInput(Button.ACTION);
      game.endPhase();
    });
```
Feel free to just disable it and mark it with `// TODO: fix this later somehow`. The test isn't even that important imo.

**Comment by DayKev** [comment]
Uh, you shouldn't be using your own beta branch for PRs. When I checked out the PR to try and fix the test it fucked up my local beta branch.

**Comment by DayKev** [comment]
Well this *might* work, try adding this after line 52 (should be `await game.doKillOpponents();`) of `reload.test.ts`:
```ts
    game.onNextPrompt("SelectBiomePhase", Mode.OPTION_SELECT, () => {
      (game.scene.time as MockClock).overrideDelay = null;
      const optionSelectUiHandler = game.scene.ui.getHandler() as OptionSelectUiHandler;
      game.scene.time.delayedCall(1010, () => optionSelectUiHandler.processInput(Button.ACTION));
      game.endPhase();
      (game.scene.time as MockClock).overrideDelay = 1;
    });
```
and replace the imports with this:
```ts
import { GameModes } from "#app/game-mode";
import OptionSelectUiHandler from "#app/ui/settings/option-select-ui-handler";
import { Mode } from "#app/ui/ui";
import { Biome } from "#enums/biome";
import { Button } from "#enums/buttons";
import { Moves } from "#enums/moves";
import { Species } from "#enums/species";
import GameManager from "#test/utils/gameManager";
import { MockClock } from "#test/utils/mocks/mockClock";
import { afterEach, beforeAll, beforeEach, describe, expect, it } from "vitest";
```

**Comment by RedstonewolfX** [comment]
> Uh, you shouldn't be using your own beta branch for PRs. When I checked out the PR to try and fix the test it fucked up my local beta branch.

Sorry, my bad

> Welp I have no idea how to make the newly broken test continue past the `SelectBiomePhase`, no matter what I do it refuses to accept button presses.
> 
> ```ts
>     // you'd think this would work but no
>     game.onNextPrompt("SelectBiomePhase", Mode.OPTION_SELECT, () => {
>       const optionSelectUiHandler = game.scene.ui.getHandler() as OptionSelectUiHandler;
>       optionSelectUiHandler.processInput(Button.ACTION);
>       game.endPhase();
>     });
> ```
> 
> Feel free to just disable it and mark it with `// TODO: fix this later somehow`. The test isn't even that important imo.

I did fix this by adding SelectBiomePhase to the Phase Interceptor, but this breaks the reload test for some reason:
image

**Comment by RedstonewolfX** [comment]
I have no idea why this test in particular would stall out

**Comment by DayKev** [comment]
It's because you added the map item, so now it's waiting for the player to select which biome to go to, but the test wasn't designed to handle that. The code from my latest comment *might* fix that (I'm not sure if I was testing the right commits due to the branch mixup).

**Comment by RedstonewolfX** [comment]
> It's because you added the map item, so now it's waiting for the player to select which biome to go to, but the test wasn't designed to handle that. The code from my latest comment _might_ fix that (I'm not sure if I was testing the right commits due to the branch mixup).

Oh that's extremely helpful to know

**Comment by RedstonewolfX** [comment]
Moved to a new branch to resolve branch issue

**Pull request closed without merging**
