### PR TITLE
[Enhancement][UI] `Passive` ability will be displayed even if it is locked or disabled

### PR DESCRIPTION
**Pull request by KimJeongSun**
## What are the changes the user will see?

In the Pokémon info window of the starter select UI, the name of the `Passive` ability will be displayed even if it is locked or disabled.

## Why am I making these changes?

I find it inconvenient as it currently is. Don't you all agree?

## What are the changes from a developer perspective?

- The `Passive` text will be greyed out when it is either disabled or locked. (alpha value is 0.5)
- The `Passive` UI for Pokémon that don't have a `Passive` (e.g., Pikachu) will be made invisible.
- Add new Icons for disabled and locked passive.

### Screenshots/Videos

- before

https://github.com/user-attachments/assets/71083170-e7a0-4729-baaf-cfd5eb9f3828

- after

https://github.com/user-attachments/assets/c5bf7348-af16-43dd-8713-51bc059f47d9

- after ( in legacy UI )

https://github.com/user-attachments/assets/8d9831c6-a343-4911-a7b3-3fd7cc8e06c8

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by frutescens — COMMENTED** [review]
Has the artist been credited on the README.md yet?

**Review by Tempo-anon — APPROVED** [review]
Looks good to me. Does this work for the longest ability names in German? Also, what does walker or some of the playerbase feel about how it looks?

**Review by DayKev — APPROVED** [review]
I like it. 👍

**Review by f-fsantos — APPROVED** [review]

**Comment by KimJeongSun** [comment]
> Has the artist been credited on the README.md yet?

I think I need to add them to README, (and then tiny my name)

**Comment by KimJeongSun** [comment]
> Looks good to me. Does this work for the longest ability names in German? Also, what does walker or some of the playerbase feel about how it looks?

of course! when I change fontsize for instruction, I also resize passive label and text too ( on each language ), so there is enough space for adding icons! don't worry!

**Pull request merged**
