### PR TITLE
[Localization] [Fix] Restoring inverted rival dialogues in all dialogue-misc.json locales

### PR DESCRIPTION
**Pull request by Adri1**
## What are the changes the user will see?
Ivy and Finn dialogue were inverted, so they are corrected

## Why am I making these changes?
Because Ivy and Finn dialogue are inverted in all dialogue-misc.json
## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?

### CODE REVIEW

**Review by DayKev — APPROVED** [review]

**Comment by Tempo-anon** [comment]
How long has this been a thing?

**Comment by CodeTappert** [comment]
How sure are you for the german dialogue? What are you basing this on? 
(i dont actually know if its correct)

**Comment by Adri1** [comment]
@Tempo-anon Probably since the last locales revamp with all the Git Localize stuff

**Comment by Adri1** [comment]
@CodeTappert Avatar mimics in dialogues, and the use of "?!" that are Ivy's in every language

**Review by CodeTappert — APPROVED** [review]

**Pull request merged**
