### PR TITLE
zh_CN translation Update pokemon-info-container.ts  [Localization]

### PR DESCRIPTION
**Pull request by 40chyan**

### CODE REVIEW

**Comment by 40chyan** [comment]
@Tempo-anon I speak Chinese so basicly I think these terms are correct. But just in case, all translation of terms based on https://wiki.52poke.com/ , which is simply Chinese version of Bulbapedia.

**Comment by SnowCharmQ** [comment]
@40chyan Typo again in your PR title, you can fix it.

**Comment by 40chyan** [comment]
@SnowCharmQ Yes, haven't fixed this since you said yesterday, sorry for that.

**Review by Tempo-anon — APPROVED** [review]
I'll take snowcharm's word that these terms are accepted

**Pull request merged**
