### PR TITLE
implement Cheek Pouch ability

### PR DESCRIPTION
**Pull request by OrangeRed**
Quote from [Cheek_Pouch_(Ability)](https://bulbapedia.bulbagarden.net/wiki/Cheek_Pouch_(Ability))
> Cheek Pouch restores 33% of the Pokémon's maximum HP when it consumes a [Berry](https://bulbapedia.bulbagarden.net/wiki/Berry), after the effect of the Berry is applied.
>
> Cheek Pouch activates even if the Pokémon eats another Pokémon's held Berry via [Bug Bite](https://bulbapedia.bulbagarden.net/wiki/Bug_Bite_(move)), [Pluck](https://bulbapedia.bulbagarden.net/wiki/Pluck_(move)), or [Fling](https://bulbapedia.bulbagarden.net/wiki/Fling_(move)), but only if the Berry is actually eaten for an effect (i.e. the Berry consumption animation plays).
>
>Cheek Pouch will not activate if the Pokémon is under the effect of [Heal Block](https://bulbapedia.bulbagarden.net/wiki/Heal_Block_(move)).

---

- [x] Trigger heal once per Berry Phase
- [x] Trigger heal when berry is forcefully eaten (This part of Pluck, Bug Bite and Stuff Cheeks is not currently implemented)
- [ ] Fail to trigger when affected by the Heal Block (Heal Block not current implemented although that logic should probably exist in the Heal Phase class)

Default
<video src="https://github.com/pagefaultgames/pokerogue/assets/5421700/7473fd9a-6ab6-4e17-9916-c2ec5acd9be3" />

Eating Multiple Berries
<video src="https://github.com/pagefaultgames/pokerogue/assets/5421700/582e0295-4800-454d-8222-52b1d603aad2" />

### CODE REVIEW

**Comment by OrangeRed** [comment]
* Add Cheek Pouch trigger to `EatBerryAttr` which was implemented in PR #232  

https://github.com/pagefaultgames/pokerogue/assets/5421700/98e80e57-2c51-4fcd-99e9-9aa58966f522

https://github.com/pagefaultgames/pokerogue/assets/5421700/8a2f3cc7-8026-4137-a5c9-6c663064fbdf

https://github.com/pagefaultgames/pokerogue/assets/5421700/47d07164-86f5-4443-8356-00edef8d4fc9

I also messed up the rebase hence the double commit...

**Comment by molker** [comment]
Won't this conflict with your PR for harvest since you had to rewrite the berry phase? Would you want to combine them?

**Comment by OrangeRed** [comment]
It will but its probably better if you merge the other one and I pull / fix the most recent changes from main.

**Comment by OrangeRed** [comment]
I reverted the last commit since it's been added via #1260

**Comment by OrangeRed** [comment]
I see that there is [this PR](https://github.com/pagefaultgames/pokerogue/pull/1153) that is attempting to implement Heal Block. 

Should I wait for that one to be merged before this one or should the author of that PR handle the changes from this PR?

**Review by molker — APPROVED** [review]

**Comment by jatinkohli** [comment]
For what it's worth, I have only implemented blocking moves with heal block and cheek pouch would not need to be changed since eating healing berries in the first place needs to be blocked

**Pull request merged**
