### PR TITLE
[Move] Fix type immunities granted by abilities only applying to attacks

### LINKED ISSUE #278: Sap Sipper does not block Spore
Confirmed this behaviour shouldn't occur, Sap sipper should activate on grass type status moves.
Unconfirmed if this occurs with other status moves.

### PR DESCRIPTION
**Pull request by zacharied**
Revival of #240.

## What are the changes?
Type immunity abilities (such as Levitate and Sap Sipper) apply to non-field status moves, not just attacks.

## Why am I doing these changes?
Fixes #278. The current behavior of these abilities is incorrect.

## What did change?
In `TypeImmunityAbAttr.applyPreDefend()`, instead of just blocking attacks, block any move that does not target the field. Also remove an incorrect check there for `StatusMoveTypeImmunityAttr`, since that attribute applies to types of Pokemon, not types of Moves.

Add tests for Sap Sipper.

## How to test the changes?
The provided unit tests should be enough to verify the functionality. If you want to test it on the current build, consider these overrides:

```ts
export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.BIDOOF;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.SPORE];
export const OPP_ABILITY_OVERRIDE: Abilities = Abilities.SAP_SIPPER;
```

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by Tempo-anon — APPROVED** [review]

**Comment by Tempo-anon** [comment]
Can you double check examples like rain dance vs storm drain should still work and charge vs volt absorb should still work?

**Comment by zacharied** [comment]
> Can you double check examples like rain dance vs storm drain should still work and charge vs volt absorb should still work?

Confirmed, we're all good.

**Comment by flx-sta** [comment]
@zacharied 
https://discord.com/channels/1125469663833370665/1250632973909229629 Please have a look at this

**Comment by zacharied** [comment]
Oh yeah we're not good at all. I'm taking a look.

**Comment by zacharied** [comment]
@flx-sta @Tempo-anon See #2168.

**Pull request merged**
