### PR TITLE
[BUG] Fixes bug with Metronome freezing the game

### PR DESCRIPTION
**Pull request by schmidtc1**
Duplicate PR for Beta

## What are the changes?

#2790
Metronome calling a ChargeAttr move (e.g. Beak Blast) will freeze the game.

## Why am I doing these changes?

Fixes a bug that freezes the game.

## What did change?

I implemented a check to see if the user has the move in their moveset, if not create a dummy PokemonMove for the case of Metronome and pass it into pushMovePhase.

### Screenshots/Videos

Before fix (game freezes from getMove)

https://github.com/pagefaultgames/pokerogue/assets/62030095/05761910-0c3d-4c66-8d1a-0ac40c5c226e

After fix 

https://github.com/pagefaultgames/pokerogue/assets/62030095/34db36ab-a938-4110-9664-d9e39ca102b0

## How to test the changes?

Give your pokemon Metronome and manipulate the moveId variable in RandomMoveAttr to always use Beak Blast 
``` const moveId = moveIds[585];```
Use Metronome with Beak Blast, see that game continues properly and Beak Blast goes off.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by flx-sta** [comment]
what happened?

**Comment by schmidtc1** [comment]
> what happened?

this was a PR into Beta before I knew to open a new branch > cherry pick changes into it > PR to Beta. I had merged beta into my original branch and broke some things in my PR here: https://github.com/pagefaultgames/pokerogue/pull/2819

**Comment by flx-sta** [comment]
@schmidtc1 always good to close with comments for documentation purposes

**Comment by schmidtc1** [comment]
> @schmidtc1 always good to close with comments for documentation purposes

I'll keep in mind for the future

**Pull request closed without merging**
