### PR TITLE
Make 31IVs show up as Gold

### PR DESCRIPTION
**Pull request by HighMans**
## What are the changes?
Make 31IVs show up as gold to better emphasize they're 31IVs. 

## Why am I doing these changes?
Makes things a bit easier to decern when looking for 31IVs since the graph makes 29IVs/30IVs hard to discriminate.

## What did change?
Added a condition to check if IVs are 31 and to make the number itself gold, otherwise leave it be. My only gripe is I'm not the biggest fan of the gold, it doesn't seem to pop out that much. Maybe a better color can be used?

#### Before on Starter Select Screen:
https://github.com/pagefaultgames/pokerogue/assets/42877729/b4bc1401-ab66-4269-aa66-e543eee8409c

#### After on Starter Select Screen:
https://github.com/pagefaultgames/pokerogue/assets/42877729/37208921-1efe-46ff-8217-14298c9241df

#### Before on Capture Screen:
BeforeCapture

#### After on Capture Screen:
AfterCapture

## How to test the changes?
Just pull and take a look with a save that has 31IVs. For the capturing test, I modified the battle-scene.ts file in the addEnemyPokemon function and set the IVs to 31. (There is no overide for it currently...)

## Checklist
- [X] Have I checked that there is no overlap with another PR?
- [X] Have I made sure the PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by molker** [comment]
I like the idea, add it to the starter select ui as well and comment above the if statement to give a brief description of what its doing

**Comment by HighMans** [comment]
I'll add the comments, as for the starter select screen -- that's what the top two videos are. I just wrote the wrong names -- unless I'm missing something.

**Comment by TempsRay** [comment]
Would it be possible to change the color from gold to rainbowish? I personally think that looks better but overall this looks like a good addition

**Comment by HighMans** [comment]
> Would it be possible to change the color from gold to rainbowish? I personally think that looks better but overall this looks like a good addition

Do you know if that's a color that's used already in the game?

**Comment by TempsRay** [comment]
> > Would it be possible to change the color from gold to rainbowish? I personally think that looks better but overall this looks like a good addition
> 
> Do you know if that's a color that's used already in the game?

https://github.com/pagefaultgames/pokerogue/pull/1457 should have some examples of rainbow coloring that I like but if that's not feasible then having 31 IVs show up as gold is still better than white.

**Comment by HighMans** [comment]
> > > Would it be possible to change the color from gold to rainbowish? I personally think that looks better but overall this looks like a good addition
> > 
> > 
> > Do you know if that's a color that's used already in the game?
> 
> #1457 should have some examples of rainbow coloring that I like but if that's not feasible then having 31 IVs show up as gold is still better than white.

It looks like the text object used for the IVs is BBCode while the rainbow text is using's phaser's text. Don't know enough about the UI to switch things from BBCode over to phaser's text.

**Review by TempsRay — APPROVED** [review]

**Pull request merged**
