### PR TITLE
[Music/BGM] New music added for the "Slum" biome, composed by Andr06

### PR DESCRIPTION
**Pull request by Dakurei**
## What are the changes?
New music added for the "Slum" biome, composed by Andr06 (cc @Andr06)

## What did change?
- Replacing the old BGM `public/audio/bgm/slum.mp3`
- Adding a reference to the composer in the README.md (_My VS Code has also removed unnecessary spaces at the end of lines, apparently_)
- Replacement of the BGM title in the localization files with the title chosen by the composer

### Screenshots/Videos
https://github.com/user-attachments/assets/6a755d75-8769-4e7e-9abb-0a3875f4140c

## How to test the changes?
- Launch a classic game with the override to start in the "Slum" biome, and pass the wave 5 trainer battle to trigger the music for this biome (_Or you can simply listen to the file_)

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by CodeTappert — APPROVED** [review]

**Review by Madmadness65 — COMMENTED** [review]
Seeing as the loop point for the Slum in `arena.ts` wasn't altered in this PR, and I can't test the PR myself atm, I'm going to assume that it doesn't loop properly right now. If someone can confirm for me if it does currently, I'll approve it. Otherwise, I should be able to test it myself tomorrow.

**Comment by flx-sta** [comment]
@Dakurei if the name is always gonna be the same (since it's a standalone chosen name) you might just remove the keys (except from `en`) since they all fall back to that one.

Or what do you think?

**Comment by Dakurei** [comment]
@Madmadness65 I had done a search on the file name, but I hadn't spotted where the loops declarations were. I had only found the ones for the fight music, it seemed to work (as the video suggests) because the loop was close to the beginning, since it must be 0.
I can now modify this, thx 👍

@flx-sta For consistency's sake, it's totally absurd to delete an entry with the exception of a language.

**Comment by Dakurei** [comment]
Video of the PR updated in accordance with the latest modification 👌

**Pull request merged**
