### PR TITLE
[Bug] [Beta2] Fix flyout freeze

### PR DESCRIPTION
**Pull request by chansyu**
## What are the changes?
Don't allow the UI flyouts to lock out users when `class UI method showText()` is called

## Why am I doing these changes?

The game is unplayable.
https://discord.com/channels/1125469663833370665/1273029028210671748/1273128441012686858
https://discord.com/channels/1125469663833370665/1273029028210671748/1273130314465546261

## What did change?

Remove problematic if statement and made appropriate refactors

### Screenshots/Videos

Tutorial 

[tutorial.webm](https://github.com/user-attachments/assets/d6a9d93c-fc4f-48e7-bf55-891e83046f4d)

Arena Trap

[arena-trap.webm](https://github.com/user-attachments/assets/4984651c-df50-4c3c-9040-bcfe69d41a0d)

Ingrain

[ingrain.webm](https://github.com/user-attachments/assets/2c93ac66-c7da-4588-ad22-10f77fef14a3)

Unfuse Pokemon

[unsplice.webm](https://github.com/user-attachments/assets/b01c2c73-c6de-4785-96b9-8aa70d385268)

Release Pokemon

[release.webm](https://github.com/user-attachments/assets/9265ce4b-6b0c-4e02-a596-c3fbc305e6de)

Replace an existing move

[forget-move.webm](https://github.com/user-attachments/assets/168c9b32-58c0-4eb6-bfad-adbf8f8503b3)

## How to test the changes?

Use the UI to do stuff
Especially test the refactors of specific contexts that call `showText()`
1. Fuse/Unfuse Pokemon
2. Learn new moves
3. Arena Trap abilities
4. Arena Tag moves/abilities
5. Release Pokemon

## Checklist
- [X] **I'm using `beta` as my base branch**
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I considered writing automated tests for the issue?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by frutescens** [comment]
Video of some tutorials

https://github.com/user-attachments/assets/88b6098a-3375-4bb0-a1ac-32e57140eac2

Final Boss dialogue also works.

**Review by frutescens — APPROVED** [review]

**Comment by ben-lear** [comment]
why are these locations even calling `showText()` with empty values anyway? `clearText()` is already an existing function

**Review by innerthunder — APPROVED** [review]

**Comment by flx-sta** [comment]
I'm very confused what is even going on in this PR.
Bens messages seems rather interesting going forward.

Why is `showText()` overwritten in inherited classes with different arguments allowing different types...

We should also make sure to consider writing tests to make sure this isn't happening again

**Review by torranx — APPROVED** [review]
same question with @ben-lear but approving this nevertheless. looking forward to a refactor

**Comment by chansyu** [comment]
I tried to refactor the code to avoid accepting `null` as an argument for string.
Definitely would like to do a refactor. The `showText("")` is hard to understand and is different from `clearText("")`. 

> Why is showText() overwritten in inherited classes with different arguments allowing different types?
I only see overridden methods that (may/may not) accept null arguments.

Tests seems like a good idea.

**Review by flx-sta — APPROVED** [review]
Approving for the sake of progress.

**Review by ben-lear — APPROVED** [review]

**Comment by ben-lear** [comment]
@frutescens tested if clearText would work as replacement, but it does not. Approving this, but an issue should be opened to refactor these calls down the line

**Comment by frutescens** [comment]
Video of clearText() as a replacement

https://github.com/user-attachments/assets/08e090f2-7124-4458-babe-183139b77e91

**Pull request merged**
