### PR TITLE
[QoL] Added Skip Egg Hatching Animation option in settings.

### PR DESCRIPTION
**Pull request by Arxalc**
## What are the changes?

* Added a settings option to skip egg hatching animation.
## Why am I doing these changes?

#1471 is focusing on UI. Until that's finished, I wanted to have this option. Hopefully these two can merge in the future.

🌈 **Math Time** 🌟
I am playing at 5x game speed, have 65 eggs to hatch, and am constantly mashing A to skip animations. It takes me ~2 minutes and 12 seconds to get through them all -> ~2 seconds/egg.
If you're aiming for the specific legendary in Legendary Up! You will, on average, hatch 246 eggs before getting it. (see wiki for gacha probabilities).
Meaning **_to get the specific legendary in Legendary Up! you will spend an average of 8 minutes and 12 seconds mashing buttons to skip through animations._** (I'm in pain.)

## What did change?

* Added new setting
* When hatching eggs, the animations will not be played.
### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/63990624/f510434d-0131-435b-93bf-26bba35ac98e

## How to test the changes?

Set immediate egg hatch = true in overrides.ts, then get some eggs.
Couldn't figure out how to give yourself eggs in the overrides file so I modified part of game-data.ts to do. These changes WILL be reverted in the final cut.
## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Arxalc** [comment]
Please double check the code! I'm not fully knowledgeable on what some original parts did before isolating them for this.
I wanted some eyes first before I remove comments and such.

**Comment by Hibikill** [comment]
I'm really hoping this gets implemented soon, having to hatch 30+ normal eggs is really boring ￣へ￣

**Comment by RNGezeus** [comment]
Can it limit itself to a certain rarity of eggs? Im fine skipping my commons but wanna see other ones without micromanaging settings every time

**Comment by Arxalc** [comment]
> Can it limit itself to certain rarity of eggs? Im fine skipping my commons but wanna see other ones without micromanaging settings every time

I've thought about adding additional filtering like only showing animations for new pokemon, new egg moves, or better IV's. Different rarities can work too.
I'd like this changes to be acceptable first before moving on.

**Comment by torranx** [comment]
ok so i think youre missing one key part of this: 
_players want to have a summary screen of all the eggs hatched after skipping them_

**Comment by ShinyZoroark** [comment]
To be completely honest, as a player, I would love this simple addition as a band-aid until we get a full summary screen or whatever. I genuinely don't like hatching eggs anymore because it takes so long to open them and this fixes it entirely.

**Comment by Arxalc** [comment]
* Changed so that new pokemon will always play the animation
* Updated Settings to include egg tier filtering
* Move some code around... hopefully shouldn't result in laggy UI or data wonkiness. Need to test what it's like hatching a large amount of eggs at once.

**So in this case, animations will be skipped for egg tiers Great and lower.**
image

https://github.com/pagefaultgames/pokerogue/assets/63990624/6bf71580-3a4b-470b-8622-73301e074bf6

**Pull request closed without merging**
