### PR TITLE
Spectral Thief Partial Implementation + Marking Electro Shot as Partial (Pre-Damage Stat Change Phase Needed for Both Moves)

### PR DESCRIPTION
**Pull request by SunshineFuture753**
Implements Spectral Thief as much as possible; all that is left is recalculating damage after stats are stolen. This will require examining the stat change phases, figuring out how to make them occur before damage is calculated if necessary (which is the case for Spectral Thief). This PR relies on https://github.com/pagefaultgames/pokerogue/pull/1038 to fix PRE_APPLY, which Spectral Thief utilizes. Electro Shot is also now marked as Partial, given how it has the same issue of not recalculating stats after a mid-turn boost, specifically when used in Rain.

### CODE REVIEW

**Comment by Brandon-Rodgers** [comment]
Spectral Thief against Normal type when combined with PR #1038

https://github.com/pagefaultgames/pokerogue/assets/9848614/09795bea-e214-408d-a02c-d73830af881e

**Comment by SunshineFuture753** [comment]
Spectral Thief when the foe has no stat boosts, as well as when the foe has stat boosts and the user has Simple. (Note that Psychic Fangs and Brick Break are no longer marked as Partial because of PR https://github.com/pagefaultgames/pokerogue/pull/1038.) 

https://github.com/pagefaultgames/pokerogue/assets/160639673/8066ceaf-4f70-4c3b-951b-261c70058c96

Spectral Thief ignoring Clear Body and lowering the user's stats when the user has Contrary. (Same disclaimer as above.)

https://github.com/pagefaultgames/pokerogue/assets/160639673/06eb0fae-717b-4ca1-a95f-95669baed7d4

Sources for Spectral Thief's mechanics:
https://bulbapedia.bulbagarden.net/wiki/Spectral_Thief_(move)
https://replay.pokemonshowdown.com/gen9customgame-2124993173 (Fails on Normal types)
https://replay.pokemonshowdown.com/gen9customgame-2124980181 (Simple)
https://replay.pokemonshowdown.com/gen9customgame-2124994266 (Contrary)

**Comment by ArchSinccubus** [comment]
Tested the following conditions on Spectral Thief:

1. Tested functionality with already existing stat changes, when using a buff move on the same turn, when you already have some stat boosts of the same type, and corner case for +6 in your stat already
https://drive.google.com/file/d/1N4dcahMfW4jQdaTB2ya-AMfzwqTiuoj2/view?usp=drive_link

2. Tested functionality against Normal Type (Stats were not stolen)
https://drive.google.com/file/d/1gblhpROSxOwVSedMShmPgMwWLZ33ljJw/view?usp=drive_link

3. Tested functionality with user having Contrary (Stats were reduced)
https://drive.google.com/file/d/1yNrQUd5xRCAQtbQ0rNJurqdx-uKR6Hpv/view?usp=drive_link

4. Tested functionality with user having Simple (Stats were doubled)
https://drive.google.com/file/d/1K_tHQmPGxS0yMq3ixxCb7xaHfmDEQq-S/view?usp=drive_link

5. Tested functionality with opponent having Clear Body (Stats were stolen all the same)
https://drive.google.com/file/d/1N4dcahMfW4jQdaTB2ya-AMfzwqTiuoj2/view?usp=drive_link

6. Tested functionality with double battles (Both stealing from the same mon twice and stealing from both of them individually)
https://drive.google.com/file/d/1HXvFWgAM9rSgCaAr5ICMv9MCCIfsZAFQ/view?usp=drive_link

**Comment by jaimefd** [comment]
Hello, I accidentally started working on Spectral Thief without seeing this pull request, and I really appreciate all the work and tests done here, I would love to help by sharing what I learned. I found one way to fix the issue where the boosted stat isn't applied on the hit you do that same turn.

You can do user.scene.overridePhase instead of user.scene.unshiftPhase for the StatChangePhase, to make sure the stat boost phase executes at that moment, without waiting for the MoveEffectPhase to end.

However that won't be enough, you also need to change the logic in StatChangePhase so that the stat changes are applied without having to wait for their animation to show (which is done by moving outside all of the logic inside of the end() function in the start method except for the handleTutorial line).

My explanation may not be the best so you can also see the changes in the PR I just did before I found this one (https://github.com/pagefaultgames/pokerogue/pull/1365)

**Comment by flx-sta** [comment]
No action within more than a month. 
Considered stale.

Feel free to re-open it when you are still working on it/want to work on it again

**Pull request closed without merging**
