### PR TITLE
Localized the statname in the X Item description

### PR DESCRIPTION
**Pull request by CodeTappert**
## What are the changes?

The X Items now correctly have localized stat names

## Why am I doing these changes?

They were english

## What did change?

See screenshots

### Screenshots/Videos

Before:
image
After:
image

## How to test the changes?

Set your game to german (its also noticable for dire hit in english) and find an X-Item in the shop. 

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by CodeTappert** [comment]
french by sangara42

**Comment by CodeTappert** [comment]
Changed french by Lugiadrien (they both agree)

**Comment by josericardo-fo** [comment]
This fixes #1003

**Review by josericardo-fo — APPROVED** [review]
LGTM

**Review by Tempo-anon — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]

**Pull request merged**
