### PR TITLE
[QoL][DEV] add PokemonMoveset type

### PR DESCRIPTION
**Pull request by flx-sta**
## What are the changes?

I've replaced all the `Array<Moves>` types with a new `PokemonMoveset` type which has a tuple value of 
```ts
[Moves?, Moves?, Moves?, Moves?]
```

## Why am I doing these changes?

It informs the dev about using too many array indexes. The compiler will complain if more than 4 moves are used

## What did change?

I've replaced all the `Array<Moves>` types with a new `PokemonMoveset` type/tuple;
```ts
type PokemonMoveset = [Moves?, Moves?, Moves?, Moves?];
```

## How to test the changes?

Honestly...
See if tests & build still runs.
I don't see anything else changing as this has no influence of the output js file.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- ~~Are the changes visual?~~
  
  
image
image

### CODE REVIEW

**Review by torranx — APPROVED** [review]
code lgtm - did not test

**Comment by flx-sta** [comment]
> code lgtm - did not test

did you at least start it and see if it runs? :D

**Comment by torranx** [comment]
> > code lgtm - did not test
> 
> did you at least start it and see if it runs? :D

not really, thats why i specified the **code** and _did not test_

**Comment by OrangeRed** [comment]
Doesn't G-Max Eterantus get 8 moves? Are you sure this type will work correctly with that?

**Comment by flx-sta** [comment]
> Doesn't G-Max Eterantus get 8 moves? Are you sure this type will work correctly with that?

It’s 4 separate abilities in 2 different states, isn’t it ? Otherwise the ability detail view would be wrong too. The compiler didn’t complain and I’ve replaced all the `Array<Moves>` and `Moves[]` I found

**Comment by flx-sta** [comment]
Reopen if still relevant later m

**Pull request closed without merging**
