### PR TITLE
[Localization] Modified script spelling at the tutorial (by korean)

### PR DESCRIPTION
**Pull request by sodaMelon**
[Localization] Modified script spelling at the tutorial (by korean)\
Hi. I'm also playing games now, but I fixed it myself because it bothered me so much.
If you need more Korean helper, call me. 😉🎶I'm free these days

## What are the changes?
the tutorial script, you know, the intro of the game.
It was translated into Korean, but there was an error in spelling, so I corrected it.

## Why am I doing these changes?
This spelling is a mistake that Korean people often make.
If you correct this wrong word, it will seem like a more delicate game.

## What did change?
fix some words *at src/locales/ko/tutorial.ts*

건내주기 -> 건네주기 

* when you feel confused, check this korean grammer reference: https://www.home-learn.co.kr/newsroom/news/A/1989

(like in english : trensfer -> transfer)
in english *at src/locales/en/tutorial.ts*
```
 "selectItem": `After every battle, you are given a choice of 3 random items.\nYou may only pick one.
    $These range from consumables, to Pokémon held items, to passive permanent items.
    $Most non-consumable item effects will stack in various ways.
    $Some items will only show up if they can be used, such as evolution items.
    $You can also transfer held items between Pokémon using the transfer option.
    $The transfer option will appear in the bottom right once you have obtained a held item.
    $You may purchase consumable items with money, and a larger variety will be available the further you get.
    $Be sure to buy these before you pick your random item, as it will progress to the next battle once you do.`,

```

### Screenshots/Videos

FIX

## How to test the changes?
It's a fixed translation, so no tests are needed.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Tempo-anon** [comment]
@MrWaterT and @returntoice need your opinions since you've done some Korean localization

**Comment by returntoice** [comment]
> @MrWaterT and @returntoice need your opinions since you've done some Korean localization

The original spelling is a typo. Nice correction

**Review by returntoice — APPROVED** [review]

**Comment by sodaMelon** [comment]
> > @MrWaterT and @returntoice need your opinions since you've done some Korean localization
> 
> The original spelling is a typo. Nice correction

thanks. do you have any plan to trainer dialouge? 혹시 트레이너 대화도 번역 예정에 있으세요? 
Discord에서 @Tempo-anon 님한테 물어봤는데, 할거면 스레드 세워서 하면 된다고 하셔서요!!

**Comment by sodaMelon** [comment]
just do mistake;;;; i will open this pull request

**Comment by returntoice** [comment]
> > > @MrWaterT and @returntoice need your opinions since you've done some Korean localization
> > 
> > 
> > The original spelling is a typo. Nice correction
> 
> thanks. do you have any plan to trainer dialouge? 혹시 트레이너 대화도 번역 예정에 있으세요? Discord에서 @Tempo-anon 님한테 물어봤는데, 할거면 스레드 세워서 하면 된다고 하셔서요!!

안 그래도 여기 계시는 다른 분들께 여쭤보던 참이었습니다. 아직 시작은 안 했는데 양이 많다 보니 나눠서 하면 좋지 않을까 싶었어요. 혹시 어느 디스코드 채널인가요? 지금 포케로그 위키 채널 디스코드(https://discord.gg/xkrPZz2p)에 저랑 다른 한 분이 계십니다. 이 채널에 여기 collaborator 분들도 몇 분 계시고요

**Review by Tempo-anon — APPROVED** [review]

**Pull request merged**
