### PR TITLE
fix import eslint module not working in new flat eslint config

### PR DESCRIPTION
**Pull request by meepen**
## What are the changes?

Fixes eslint rules not working for the eslint-plugin-import module

## Why am I doing these changes?

To fix eslint in preparation of cleanup of circular dependencies

## What did change?

Fixes the lines that conflict with the rules that now work, and fixes the eslint config

## How to test the changes?

You can pull only the eslint config and package changes to see the eslint rules working on the broken files that were updated

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

### CODE REVIEW

**Review by brain-frog — DISMISSED** [review]

**Comment by flx-sta** [comment]
@meepen do you think you can also get it to work with eslint v9?

Cause we are going to update to that soon following #3160.
I've checked the `eslint-plugin-import` github and it seems they haven't caught up with eslint 9 yet so I was wondering if you might know more about this

**Comment by DayKev** [comment]
@flx-sta is this PR still relevant?

**Comment by flx-sta** [comment]
Not unless it’s updated for eslint 9

**Comment by Tempo-anon** [comment]
Looks like this is not updated for eslint 9 and has a lot of conflicting files. Will close out this PR for now.

**Pull request closed without merging**
