### PR TITLE
[Enhancement][UI] Merging Achievements and Vouchers into a single Page

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes?
Achievements and Vouchers now share the same page.
Vouchers is removed from the menu as well. 

## Why am I doing these changes?
Space on the menu is getting cramped and expensive.

## What did change?
ui/menu-ui-handler.ts: Removed Vouchers from the menu
ui/ui.ts: Removed voucher-ui-handler.ts as an import / class / mode 
ui/vouchers-ui-handler.ts: Deleted.
ui/achvs-ui-handler.ts: Voucher-specific functions moved to here.

Used summary-ui-handler.ts as a reference for the pages + starter-select-ui-handler.ts as a reference for buttons. 

### Screenshots/Videos
https://github.com/user-attachments/assets/e309a91d-1dc7-4a58-898b-404264b78ac7

Responsive Button Positioning
https://github.com/user-attachments/assets/da37d56e-6357-465d-b767-884fbdf8a917

## How to test the changes?
Go to Menu --> Achievements 
Press Space/Button.ACTION to swap between pages

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by torranx** [comment]
Is the space bar the ideal key here? I'm just considering the fact that we use "R" and "F" when traversing game settings tabs

**Comment by frutescens** [comment]
I don't mind changing the key to 'R' or 'F', but I think the action button, at the moment, is fine because the page display will only go back-and-forth from vouchers to achievements, and vice-versa. If we add more pages in the future, I think then there should be some consideration of having 'R' and 'F' directional buttons.

**Comment by frutescens** [comment]
Note: I should clear-up localizations too.

**Comment by f-fsantos** [comment]
@frutescens Can you show how this is being handled in mobile?

**Comment by frutescens** [comment]
Noticed a bug while recording this: 
https://github.com/user-attachments/assets/bde6c942-ce15-4ebf-a892-aaea2cb45707

**Comment by frutescens** [comment]
Note: the key "menuUiHandler:VOUCHERS" was only used once in menu-ui-handler.ts
Its disappearance did not affect code behavior

**Comment by frutescens** [comment]
Ah, I know what happened. I changed something but I forgot to revert it.

**Comment by frutescens** [comment]
@DayKev 

Uploading Screen Recording 2024-08-22 at 8.38.51 PM.mov…

**Review by DayKev — APPROVED** [review]

**Pull request merged**
