### PR TITLE
#vote to #feature-vote

### PR DESCRIPTION
**Pull request by karl-police**
ok that's the change

now I am seeking the UI function like explanation, yep

help

thanks

do not ask for if UI supports controller, that doesn't help me, cuz if it doesn't support controller basically if you'd draw one of those mindmaps, I'd draw thousands of arrows that point back to --> Aslong I don't understand the UI functions, how one gonna make UI work right

I mentally died going through them, maybe if I give it ago another time, maybe I can figure out, but for now, no.

Hmmmmmm

Check out other great posts:

https://github.com/pagefaultgames/pokerogue/issues/1075

Channel is not named vote anymore or never was. I was seeking for vote but I didn't find vote, so feature-vote

image

### CODE REVIEW

**Comment by karl-police** [comment]
If @Madmadness65 sees and puts label here without opening this Discord channel

image


I will lose and fail to believe the existance of everything.

**Comment by IceFire03** [comment]
What are you asking for? You can see controlled mappings in /src/configs, which are mapped in /src/inputs-controller.ts to translate any input into a Button. These Button presses are then used to navigate around the UI. It's not very clear to me what you want help with.

**Review by IceFire03 — APPROVED** [review]
This part of the PR makes sense, though

**Comment by karl-police** [comment]
> What are you asking for? You can see controller mappings in /src/configs, which are mapped in /src/inputs-controller.ts to translate any input into a Button. These Button presses are then used to navigate around the UI. It's not very clear to me what you want help with.

I seek explanations, just like yours. 👍 

Though how do I test them without a controller 🤔

**Comment by IceFire03** [comment]
It would probably be difficult, and I wouldn't recommend it, but you could definitely simulate the keystrokes, i.e. using [reWASD](https://www.rewasd.com/releases/release-5.2.0) or any other software

**Comment by karl-police** [comment]
Controller can't even hover over the Modifier icons, how do they view the Modifiers descriptions, or can they hover over?

**Comment by IceFire03** [comment]
I'm pretty sure you can't see item descriptions right now on controller.

**Comment by karl-police** [comment]
> I'm pretty sure you can't see item descriptions right now on controller.

3x (1)

**Review by Madmadness65 — APPROVED** [review]

**Pull request merged**
