### PR TITLE
Implement Comatose

### PR DESCRIPTION
**Pull request by ReneGV**
Implement comatose ability following [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Comatose_(Ability)).

- Pokemon is inmune to non volatile status effects.
- Pokemon cant use REST
- Pokemon can use Snore
- Pokemon is inmune to drowzy effect
- Pokemon gets double damage from HEX and WAKE UP SLAP

### CODE REVIEW

**Comment by bennybroseph** [comment]
This is a *very* complicated ability. Have you tested with Purify? Beat Up? Mold Breaker? Skill Swap, Role Play, Entrainment, Doodle? I could go on, but there's still a lot of checks that need to at least have been considered.

**Comment by ReneGV** [comment]
Adding video to verify:
- User can use sleep talk & snore
- User can not rest
https://github.com/pagefaultgames/pokerogue/assets/31145813/4121f74f-d00d-4ae9-9bb2-a9ce9d9ba28e

**Comment by ReneGV** [comment]
@bennybroseph 
Tested with Purify & Beat up
> Mold Breaker? Skill Swap, Role Play, Entrainment, Doodle?
I am quite sure those ones are already covered by       
```ts
      .attr(UncopiableAbilityAbAttr)
      .attr(UnswappableAbilityAbAttr)
      .attr(UnsuppressableAbilityAbAttr)
```

**Comment by ReneGV** [comment]
Ability supression / swapping does not work

https://github.com/pagefaultgames/pokerogue/assets/31145813/839eb365-331b-45f3-9527-c57abd284e81

Mold breaker nuzzle does not cause any status

https://github.com/pagefaultgames/pokerogue/assets/31145813/54900bda-db32-4128-8c9d-b816aa1c8358

**Comment by bennybroseph** [comment]
In the future, please provide a checklist when an ability has this many interactions between moves/abilities. Bulbapedia lists 5 paragraphs worth of info about how this should behave. The description of this Pull Request was severely lacking. 

i.e.
- [x] Checklist item Done
- [ ] Checklist item Incomplete

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
