### PR TITLE
Added permadeath gamemode modifier

### PR DESCRIPTION
**Pull request by EnslavedTuna**
- Add enable/disable modifier to starter UI, before confirming party
- Modifiers get saved/loaded
- Permadeath:

    - revives don't show up in shop/rewards
    - every 10th wave does not heal dead pokemon
    - added achievement for winning classic with permadeath enabled

### CODE REVIEW

**Comment by EnslavedTuna** [comment]
No worries, If you choose another route I'm happy to help in other ways!

**Comment by EnslavedTuna** [comment]
Perhaps in the future when there are more "Official" modes, there could be an argument for a "Custom" mode, which then allows you to select modifiers such as permadeath, monotype, etc but also parts from the other official modes (infinite/vs 200 waves, trainers/no trainers.

That way the official modes won't be cluttered/oversaturated with options/modifiers. But there is still a way to do customized runs for those that'd like

**Comment by Flashfyre** [comment]
I think I might implement this, but I will need to make some changes first, such as actually removing the party member on faint. I probably won't do it right away, but I'll try to get it in soon.

**Comment by PaulBeslin** [comment]
Nuzlocke Mode created in #457

**Comment by Madmadness65** [comment]
Superseded by #457

**Pull request closed without merging**
