### PR TITLE
Revert "[Localization] Add localization hard-coded message in move, pokemon."

### PR DESCRIPTION
**Pull request by KimJeongSun**
Reverts pagefaultgames/pokerogue#3639

because of request related with translation system updates

### CODE REVIEW

**Comment by CodeTappert** [comment]
Please fix the conflicts

**Comment by KimJeongSun** [comment]
> Please fix the conflicts

Conflict fixed! ( to reverted version )

**Comment by flx-sta** [comment]
It's fine. We don't have to revert it.
The translations made it into the `json` files just fine!

**Comment by KimJeongSun** [comment]
🙇 감사합니다 선생님!!

**Pull request closed without merging**
