### PR TITLE
[Localization] Correction of a typo in a french dialogue

### PR DESCRIPTION
**Pull request by HiHi-Daruma**
## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by Adri1 — CHANGES_REQUESTED** [review]
Thanks for your correction 👌
But do not forget to also correct it on **line 4852**, you only corrected the line given for when you play as the male avatar

**Comment by HiHi-Daruma** [comment]
Oh sorry I didn't notice, I will update it once back home 😉

**Comment by Adri1** [comment]
> Oh sorry I didn't notice, I will update it once back home 😉

No problem!

**Comment by HiHi-Daruma** [comment]
It's fixed :+1:

**Review by Adri1 — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]

**Pull request merged**
