### PR TITLE
Rework - Inputs management to include all gamepad mapping V2

### PR DESCRIPTION
**Pull request by Greenlamp2**
original PR:
https://github.com/pagefaultgames/pokerogue/pull/390

Plugins feature has been removed since it does not work correctly on prod.
It has been converted into an object with a reference to the battle-scene.

### CODE REVIEW

**Comment by Greenlamp2** [comment]
it should not break like yesterday, but if it does, you still can press the revert button 🥇

**Comment by Greenlamp2** [comment]
Some food for later: one benefit of this code, it's later, we could add an option to let the user set custom mapping IG

**Comment by molker** [comment]
Once again working locally for me, only thing I noticed: 
_(I have an 8bitdo controller so it might not map the same as an xbox controller so keep that in mind)_

- all the cycle buttons seem to be on the shoulders other than cycle nature which for me is on the "X" button. Is that intentional or just because my controller is 3rd party

**Comment by Greenlamp2** [comment]
> Once again working locally for me, only thing I noticed: _(I have an 8bitdo controller so it might not map the same as an xbox controller so keep that in mind)_
> 
> * all the cycle buttons seem to be on the shoulders other than cycle nature which for me is on the "X" button. Is that intentional or just because my controller is 3rd party

Thank you for your review.
Indead it's the intentional behaviour.

here are what were the input(right now on prod):
IMG_9607

and here's the mapping of this PR:
IMG_9608

**Comment by molker** [comment]
gotcha I missed cycle form, that works

**Comment by Greenlamp2** [comment]
adapated the code to integrate changes from:
https://github.com/pagefaultgames/pokerogue/pull/474
and solve the issue:
https://github.com/pagefaultgames/pokerogue/issues/487

**Review by Flashfyre — APPROVED** [review]

**Pull request merged**
