### PR TITLE
[Draft] Add Flyout Menus to Battle Stats UI

### PR DESCRIPTION
**Pull request by bennybroseph**
Adds a small flyout menu in the battle UI. The original idea was to add enemy movesets here, but there could be other things here as well.

TODO:

- ~~Support Legacy UI~~
- ~~Support Boss UI~~
- ~~Add something to the small flyout~~
- ~~Draft and add a second larger flyout~~ 
  - ~~Current idea is to show Weather/Terrain/Tailwind/Trick Room/etc.~~
  - ~~This would flyout from top to bottom or vice versa so that it is wider and taller~~
- ~~Track move usage to determine if a move has been seen~~
- Track initial Weather/Terrain/Tag duration

https://github.com/pagefaultgames/pokerogue/assets/13838608/9308b324-cb04-4ee1-b68b-5b5873a5541a

image

image

### CODE REVIEW

**Comment by karl-police** [comment]
What is the Legacy UI?

**Comment by karl-police** [comment]
> What is the Legacy UI?

this guy hates me

**Comment by bennybroseph** [comment]
image

**Comment by karl-police** [comment]
I showed this to someone that plays the game, and it brought up a question. Whether this will be there by default when pressing C or SHIFT.

**Comment by bennybroseph** [comment]
It does, this is all things you can see in S/V

**Comment by bennybroseph** [comment]
image

**Comment by bennybroseph** [comment]
image

image

**Comment by bennybroseph** [comment]
image

image

**Comment by bennybroseph** [comment]
image

**Pull request closed without merging**
