### PR TITLE
Add Plasma Fists Effect

### PR DESCRIPTION
**Pull request by Sporecoree**
- Created `ChangeAllMovesOfOneTypeTag` which is an arena tag that changes any move of one type into another.
- Added the secondary effect of Plasma Fists

Known Bugs
- `ChangeAllMovesOfOneTypeTag` only works as intended with Plasma Fists. This is because I don't know how to convert a type into it's respective ID. Thus regardless of whatever new type is called it always converts Normal-type moves into Electric-type.
- Normal-type moves converted to Electric-type don't trigger abilities that interact with Electric-type moves like Volt Absorb. I'm pretty sure this is because the method that checks to see whether Volt Absorb nullfiies a move checks the type associated with the move, and not what the type variable is set to. Ground immunity works just fine though.

### CODE REVIEW

**Comment by Xavion3** [comment]
This looks like it'll affect struggle which plasma fists isn't supposed to, and is it possible to make this slightly more generic so it can also work with Ion Deluge?

also just straight up going like Type.ELECTRIC should probably give you the Id. You can ask in the discord too for help with that.

**Comment by Sporecoree** [comment]
Can you point out where struggle is involved? As far as I can tell, Struggle deals typeless damage and shouldn't get affected.

**Comment by Xavion3** [comment]
Struggle is technically a normal move here, that just always deals x1 damage, so this would still turn it to electric yeah? Which one the interaction with abilities like volt absorb work is impactful.

Also has this been tested for if it correctly interacts with Pixilated and the like?

**Review by Madmadness65 — CHANGES_REQUESTED** [review]
This implementation of Plasma Fists is currently not working as intended. Once it's rebased with the main branch, it'll need testing again.

**Pull request closed without merging**
