### PR TITLE
[Sprite] Fix exp back epic Bombirdier

### PR DESCRIPTION
**Pull request by chaosgrimmon**
## What are the changes the user will see?
Bombirdier's epic-tier back sprite will now correctly appear.

## Why am I making these changes?
Reported [here](https://discord.com/channels/1125469663833370665/1274883292897738774/1276007519197724756).

## What are the changes from a developer perspective?
Deleted the now-unused spritesheet and animation frame data.
In its place, added the epic palette to the variant map. Also adjusted the `_masterlist` so it knows it's a map instead of a spritesheet.

#### Before
image
#### After
image
image

## How to test the changes?
Start a run with an epic Bombirdier, either via starter selection or the starter override.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
~~- [ ] Have I considered writing automated tests for the issue?~~
~~- [ ] If I have text, did I add placeholders for them in locales?~~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by frutescens — APPROVED** [review]
Looks good. 
image

**Review by flx-sta — COMMENTED** [review]
Idk what happened but it looks like the animation is broken for me.


https://github.com/user-attachments/assets/6ee503f6-410d-4fa9-a2ce-92ede6f9acad

**Comment by frutescens** [comment]
The animation was working fine for me.

**Comment by chaosgrimmon** [comment]
> Idk what happened but it looks like the animation is broken for me.

Is it possible that you're not using the Mixed Animations display setting?

**Comment by frutescens** [comment]
This took a while to get to, but here's video proof of it working!

https://github.com/user-attachments/assets/dc9a003e-fc8f-4115-8426-531214f3abfb

**Comment by flx-sta** [comment]
> > Idk what happened but it looks like the animation is broken for me.
> 
> Is it possible that you're not using the Mixed Animations display setting?

Could be. But I mean the sprite looks correct so approved

**Review by flx-sta — APPROVED** [review]

**Comment by flx-sta** [comment]
https://github.com/user-attachments/assets/47bdd5d1-00f5-4507-9419-69372677a28b

🚀

**Review by DayKev — APPROVED** [review]

**Pull request merged**
