### PR TITLE
Make unnerve less effective

### PR DESCRIPTION
**Pull request by Xavion3**
As suggested on discord. Currently 50%, but that can be easily changed. Doesn't have to be merged, but it was super easy so just threw this together.

### CODE REVIEW

**Comment by Flashfyre** [comment]
Should this be per-berry and maybe lower the chance? Not a request, just asking your opinion.

**Comment by Xavion3** [comment]
I can make it per berry, but I feel like that's worse to display and more likely to generate bug reports. 50% is probably fine, it's already going to be annoying with it's inconsistency and we can easily change it later if we want.

**Comment by Natsumi-chanFE** [comment]
Noooooooooooooooooooo no no no no no. Absolutely not. This change will render Endless all but unplayable

**Comment by bennybroseph** [comment]
Could this be applied exclusively to specific stuff instead:

- Final Rival Battle (Maybe)
- Final Floor in Classic
- Multiple of 50 in Endless (Maybe)
- Multiple of 250 in Endless

I feel like something like that is more reasonable. It's already annoying to knock out random wild Pokemon that pose no threat. At the very least I would hold off until the endure tokens are fixed.

**Comment by TempsRay** [comment]
I am not sure about this nerf. Unnerve was pretty useless in the mainline games so seeing it have a bit of a niche here was pretty nice. What angle is this supposedly aiming towards? 

In classic mode for the most part very few Pokemon hold more than a few berries so it works relatively fine. In fact, the only significant usages of this in a classic run will be on floors 145 and 195 and I don't think they are that impactful the ability needs to be changed to work on a coinflip and more luck based.

Unnerve is pretty good in early-mid game of endless mode since almost all opponents are holding a bucketload of berries and it lets you actually defeat opponents without them healing up to full and maxing out all their stats. Even then, unnerve is something nice to have since you can still muscle through opponents with sheer damage or just run away. Late game endless even has unnerve becoming mostly useless when the only forms of damage are specifically scaling damage and other abilities like sturdy become more important.

**Comment by Xavion3** [comment]
Yeah, this was a quick thing thrown together after Sam put forth the idea. I see the logic behind it myself, we've been nerfing basically everything which impairs item usage to have a chance to activate instead of being 100% due to the modified item mechanics and unnerve was one of the only things left unhit. The reasoning that it does just negate berries as a mechanic is true.

The prevailing opinion on the discord appears to be people dislike this because they dislike berries as a mechanic how they are at the moment, so dislike the idea of nerfing unnerve.

**Comment by jaimefd** [comment]
> Noooooooooooooooooooo no no no no no. Absolutely not. This change will render Endless all but unplayable

Not trying to start some long discussion here, but I believe a single Ability carrying a whole gamemode isn't really healthy. Some nerf would make it still pretty useful but not necessary, which is good for variety.

I'd make the nerf less impactful though, maybe allow only bosses to bypass it, and only 1 berry per turn.

**Comment by bennybroseph** [comment]
Closing this due to inactivity. Feel free to make a new request if interest is reignited

**Pull request closed without merging**
