### PR TITLE
Update battle.ts (Italian)

### PR DESCRIPTION
**Pull request by NicusPulcis**
## What are the changes?
Everything left in the file about battle has been localized
## Why am I doing these changes?
Because some stuff wasn't localized yet
## What did change?
All of the sentences involving battle stuff have been translated to italian as well
## How to test the changes?
Get in a battle in italian pokerogue
## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by Tempo-anon — APPROVED** [review]

**Comment by NicusPulcis** [comment]
@Tempo-anon hey man just wondering, what's missing for my PR to be merged?

**Comment by NicusPulcis** [comment]
Because i saw you approved the changes soooo it should be merged soon right?

**Comment by NicusPulcis** [comment]
@Tempo-anon nvm just found out about the pause for merging until monday : )

**Comment by Tempo-anon** [comment]
Can you please fix the merge conflicts and reopen or make a new PR with the changes you wanted to submit?

**Comment by NicusPulcis** [comment]
@Tempo-anon sure! i'll get working on a new PR soon : ) dw about this one, it probably has lots of issues due to the fact that it was for the beta branch and perhaps some stuff is missing, i'll make a brand new pr

**Pull request closed without merging**
