### PR TITLE
Cleanup game-stats-ui-handler (from PR #1095)

### PR DESCRIPTION
**Pull request by Dakurei**
Cleanup code of PR #1095 

  - Modification of the interface to manage labels dynamically (without this, the language change was not reflected until the page was completely refreshed)
  > Apply what has been suggested on Discord
image

### CODE REVIEW

**Review by Xavion3 — APPROVED** [review]
Code looks ok, but haven't tested myself.

**Comment by Dakurei** [comment]
> Code looks ok, but haven't tested myself.

I've tested it myself, of course, but if anyone else wants to try it too, it's certainly helpful 👍

https://github.com/pagefaultgames/pokerogue/assets/8146474/5f0d79d3-4138-4b63-8485-6f06c0d476f0

**Comment by CodeTappert** [comment]
Test (with german locailzation): (see https://github.com/dakurei-forks/pokerogue/pull/1 pleaes merge it into this :D)
- image
- image
- image

English:
- image
- image
-
image



Works fine as expected

**Comment by Dakurei** [comment]
Added a method I took from one of my personal projects and converted into Typescript to display sums of money in combat and in statistics in a more pleasant way (doesn't replace the old method, it's a complement)

> Before
image
image
image
image


> After
image
image
image
image

**Review by Xavion3 — APPROVED** [review]

**Review by XGSleepWalker — APPROVED** [review]

**Pull request merged**
