### PR TITLE
[Bug][Beta] Double vouchers fix

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes the user will see?
Hopefully, users will not get double golden vouchers.  

## Why am I making these changes?
This bug is blocking beta. 

## What are the changes from a developer perspective?
PR #1940 :  This fixed the issue of 1st Classic Clear voucher ids from being undefined. However, recent changes from #3618 led to this problem resurfacing, meaning that user accounts be considered to have two 1st Classic Clear vouchers - one with an actual id, the other with an undefined id. When title phase validated the vouchers, it would validate the newly created 'undefined' 1st Classic Clear id, which held the same information as the one as the actual id, and give the account another voucher.

This was fixed by moving initAchievements() above initVouchers() since initVouchers() depends on initAchievements(). Then, a conditional was added to the 1st classic clear achievement to prevent future validations of the achievement / associated voucher. This doesn't interfere with 1st classic clears. However, although this prevents vouchers from generating an 'undefined' 1st classic clear voucher again, those who were present during the accidental beta merge from last week may already have a valid 'undefined' one and still receive a second golden voucher.  

## How to test the changes?
Check the contents of vouchers -> console.log()
Check if a new user is able to clear classic and receive the achievement/voucher. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)

### CODE REVIEW

**Comment by flx-sta** [comment]
@frutescens I'm a bit confused what that `ordinals` code is doing inside this. Or is that intended?

**Comment by DayKev** [comment]
He probably forgot to switch to `beta` before making the changes.

**Comment by flx-sta** [comment]
> He probably forgot to switch to `beta` before making the changes.

image

**Comment by frutescens** [comment]
Whoops! Sorry, I didn't realize I was another branch when I was making this PR and I had to run out immediately afterwards.

**Review by torranx — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]

**Review by flx-sta — APPROVED** [review]

**Pull request merged**
