### PR TITLE
[Localization] Correct and Apply update to Korean

### PR DESCRIPTION
**Pull request by MrWaterT**
## What are the changes?
Remove un-translated text.
Reduce wrong-translated text.

## Why am I doing these changes?
Apply Korean along to newely updates(#1245, #1554, #1585, #1566, 7c9e5e9).
Modify my previous Text(#737)

## What did change?
No Description for new Translate.

6 cycle texts In `starter-select-ui-handler.ts` corrected.
`V` was '형태 전환'. I thought 'variant' means something about like form change.
Now V is '다른색상' (another color).

`R` was '색상 전환'. It meant 'cycle color'.
This becomes '이로치화' (make it shiny).

'이로치화' hardly have space
'암수 전환', '특성 전환', '성격 전환' are not bad when there aren't space
'폼 체인지', '다른 색상' need space, but we can read well without space
In result removing all space and aligning them makes them more readible.

## what did change (Korean)  << Added

다른 색의 이로치를 얻어본 적이 없어서 Variant를 형태라고 임의번역했는데,
알고보니 여러 유형의 이로치를 얻었을 때 그 색상을 전환하는 기능이라 '다른 색상' 으로 변경했고,
'색상'이라는 키워드가 겹치기 때문에 기존의 '색상 전환'을 '이로치화(化)'로 따라 변경했습니다.
'이로치 화'를 쓰는 것보다 띄어쓰기를 아예 제거하는 쪽이 낫다고 판단해 지금의 결과가 되었습니다.

### Screenshots/Videos
image

image

## How to test the changes?
Repeating each referenced PRs.
Cycle texts in Starter select UI.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by Tempo-anon — DISMISSED** [review]
Gonna wait on one of the other Korean speakers to approve this before merging

**Comment by goldilocks25** [comment]
'이로치화' 보단 공식 단어로 쓰이는 '특별한 색' 은 어떤가요

**Comment by returntoice** [comment]
저도 '이로치화'보다는 다른 표현이 낫지 않나 싶습니다. 위 @goldilocks25님 제안처럼 R은 "특별한색"으로 하고, V를 "색상전환"으로 하는 것은 어떨까요?

**Comment by Tempo-anon** [comment]
I'll trust whatever you make your localizations to make the game sound the best and most understandable. There's also a merge conflict that needs to be fixed.

**Comment by MrWaterT** [comment]
> '이로치화' 보단 공식 단어로 쓰이는 '특별한 색' 은 어떤가요



> 저도 '이로치화'보다는 다른 표현이 낫지 않나 싶습니다. 위 @goldilocks25님 제안처럼 R은 "특별한색"으로 하고, V를 "색상전환"으로 하는 것은 어떨까요?
> 
> To @Tempo-anon The official Korean name for shiny Pokemon is "색이 다른 포켓몬" (color-different pokemon), which differs slightly from the English name. This term is a translation from the Japanese "色違い" (called "irochigai"). However, because the term "색이 다른 포켓몬" is quite long, it is commonly referred to as "이로치 포켓몬" (irochi pokemon) in everyday use. In Japanese, "iro" means color, and "chigai" means different. This is shortened to "irochi" in Korea and it might be akin to "colordiff" if it is a case for English. but since this is not an official term, it would be better to use different terminology. (Actually, "이로치화" literally means "make it irochi", not "make it shiny".)
> 
> My suggestion is to call R "특별한색"(special color) and V "색상전환"(rotate color).

이럴수가.. '색이 다른 포켓몬' 만 생각하다가 '특별한 색'을 완전히 까먹고 말았습니다.
바로 반영해 수정했습니다.
띄어쓰기 역시 이로치화를 위해 뺐던 것이므로 복구시켰습니다.

image

I thought official shiny is only `색이 다른 (포켓몬)`'(pokemon) which color is different: adjective'
but there is `특별한 색`'special color: noun'.
(`이로치`is unofficial name from いろちがい)

There is no need to remove spcaes anymore, it is restored.

**Review by returntoice — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]

**Pull request merged**
