### PR TITLE
[Localization] Improve Simplified Chinese Localization Content ( achv.ts )

### PR DESCRIPTION
**Pull request by snnh**
## What are the changes?

This PR mainly focuses on improving the simplified Chinese localization content of the application.

## Why am I doing these changes?

1.Added Missing Simplified Chinese Translations
2.Optimized Localization Content

## What did change?

achv.ts

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by Tempo-anon — APPROVED** [review]

**Comment by 40chyan** [comment]
@Tempo-anon this translation of achievement name is rough. We might create a new one later
翻译的有点草率，加个联系方式和我们剩下翻译的人一起讨论一下。 @snnh

**Comment by snnh** [comment]
> @Tempo-anon this translation of achievement name is rough. We might create a new one later 翻译的有点草率，加个联系方式和我们剩下翻译的人一起讨论一下。 @snnh

什么方式？tg可以吗

**Comment by 40chyan** [comment]
> > @Tempo-anon this translation of achievement name is rough. We might create a new one later 翻译的有点草率，加个联系方式和我们剩下翻译的人一起讨论一下。 @snnh
> 
> 什么方式？tg可以吗

QQ或者dc吧

**Comment by snnh** [comment]
> > > @Tempo-anon this translation of achievement name is rough. We might create a new one later 翻译的有点草率，加个联系方式和我们剩下翻译的人一起讨论一下。 @snnh
> > 
> > 
> > 什么方式？tg可以吗
> 
> QQ或者dc吧

dc:snnn0578

**Pull request merged**
