### PR TITLE
Recoil Translation DE

### PR DESCRIPTION
**Pull request by karl-police**
An example sentence.

> Glumanda wurde durch Steinhaupt vor Rückstoß geschützt!

But you could also do

> Steinhaupt von Glumanda schützte es vor Rückstoß!

Unsure if this is a string from the original game, I'll have to view the other game files later.

### CODE REVIEW

**Comment by bennybroseph** [comment]
I don't know why I didn't consider this until now, but can you do a test in Showdown? That is nearly 100% accurate to verbage in the official games. I'd take Showdown text over anything else even if it's wrong.

**Comment by CodeTappert** [comment]
So i just tested it in the newest Gen IX Games. 

There just doenst appear any message.

So no "wurde vom Rückstoß getroffen" but also no "Glumanda wurde durch Steinhaupt vor Rückstoß geschützt!".

**Comment by karl-police** [comment]
> Showdown

I can't find any text easily in their Repository.

**Comment by karl-police** [comment]
> So i just tested it in the newest Gen IX Games.
> 
> There just doenst appear any message.
> 
> So no "wurde vom Rückstoß getroffen" but also no "Glumanda wurde durch Steinhaupt vor Rückstoß geschützt!".

Pokemon Ultra Sun has

> [VAR PKNICK(0000)] is damaged by the recoil!

> [VAR PKNICK(0000)] erleidet Schaden durch Rückstoß!

**Comment by CodeTappert** [comment]
> > So i just tested it in the newest Gen IX Games.
> > There just doenst appear any message.
> > So no "wurde vom Rückstoß getroffen" but also no "Glumanda wurde durch Steinhaupt vor Rückstoß geschützt!".
> 
> Pokemon Ultra Sun has
> 
> > [VAR PKNICK(0000)] is damaged by the recoil!
> 
> > [VAR PKNICK(0000)] erleidet Schaden durch Rückstoß!

Should i test with BDSP/SWSH maybe?

Maybe they still have the text that S/V doent have

**Comment by bennybroseph** [comment]
> > Showdown
> 
> I can't find any text that is alike that one in their Repository. The word I used to translate "recoil" is the equavilient of German Pokemon games.
> 
> I still need to check the Pokemon game for occurances of any Strings alike from that one.

[I mean this](https://pokemonshowdown.com/)

**Comment by karl-police** [comment]
> > > Showdown
> > 
> > 
> > I can't find any text that is alike that one in their Repository. The word I used to translate "recoil" is the equavilient of German Pokemon games.
> > I still need to check the Pokemon game for occurances of any Strings alike from that one.
> 
> [I mean this](https://pokemonshowdown.com/)

A third-party. And I don't think so, didn't find references in the Repository, if there are then it's split up hardcoded somewhere and yes.

The website itself. Idk where the strings are, couldn't find a single word with Developer Tools search in all files. Either they're encrypted or they're not there.

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
