### PR TITLE
[QoL] remove varianttiers.ts enum

### PR DESCRIPTION
**Pull request by peng06**
## What are the changes the user will see?

none

## Why am I making these changes?

there are files called both varianttiers.ts and varianttier.ts as enum and both do the same thing

no

more friends to work with 1 file over 2, and the 'standard' variable used by varianttier is easier to search in the code

## What are the changes from a developer perspective?

removes varianttiers.ts and rewrote all instances that use it to instead utilise the varianttier.ts file

### Screenshots/Videos

no change

## How to test the changes?

hatch eggs with shiny pokemon

yes

no

no

## Checklist
- [✔ ] **I'm using `beta` as my base branch**
- [ ✔] There is no overlap with another PR?
- [ ✔] The PR is self-contained and cannot be split into smaller PRs?
- [ ✔] Have I provided a clear explanation of the changes?
- [ ✔] Have I considered writing automated tests for the issue?
- [ ✔] If I have text, did I add make it translatable and added a key in the English language?
- [ ✔] Have I tested the changes (manually)?
    - [ ✔] Are all unit tests still passing? (`npm run test`)
- [ x] Are the changes visual?
  - [x ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by flx-sta** [comment]
Please resolve the conflicts

**Comment by chaosgrimmon** [comment]
Could you explain why you chose `Standard` over `Common`?

**Comment by flx-sta** [comment]
> Could you explain why you chose `Standard` over `Common`?

Strictly technical speaking the plural file called it `COMMON` while the singular file calls it `STANDARD`. So the naming was there already. Don’t think that was a decision of the author

**Comment by DayKev** [comment]
Okay I guess you just can't use GitHub's interface to do things ever, apparently.

**Comment by DayKev** [comment]
Should it be changed back to `COMMON` or do we care?

**Comment by chaosgrimmon** [comment]
> Could you explain why you chose `Standard` over `Common`?

penguin's the one that's dug through the usages, I was hoping they'd weigh in, yeah.

**Comment by peng06** [comment]
> > Could you explain why you chose `Standard` over `Common`?
> 
> 
> 
> penguin's the one that's dug through the usages, I was hoping they'd weigh in, yeah.

uh idk "standard" shiny made it sound more like it was the base shiny from msg, rather than a new rarity of shiny, also its a lot easier to search if anyone needs to work with variant tier codes, as common brings up a ton of stuff, and epic/rare also brings up egg stuff. doesnt rly matter common or standard bc the player likely wont see it i think

**Review by frutescens — DISMISSED** [review]

**Review by Tempo-anon — DISMISSED** [review]
lol we really had two different varient-tier enum files

**Review by DayKev — APPROVED** [review]

**Review by frutescens — APPROVED** [review]

**Review by xsn34kzx — APPROVED** [review]

**Review by ben-lear — APPROVED** [review]

**Pull request merged**
