### PR TITLE
Update egg.ts [Localization(it)]

### PR DESCRIPTION
**Pull request by NicusPulcis**
## What are the changes?
Egg translations have been reworked.

## Why am I doing these changes?
So that italian users who want to hatch eggs can undestand better what's going on.

### Screenshots/Videos
Screenshot 2024-06-16 12 24 50

## How to test the changes?
Open the egg gachas in pokerogue after setting the game on italian.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by bennybroseph** [comment]
Do you have a source on these translations? This should come from official sources, not a translation of English.

**Comment by CodeTappert** [comment]
Please use https://abcboy101.github.io/poke-corpus for the offical translations of the egg hatch things

**Comment by NicusPulcis** [comment]
I will update the PR as soon as i can

**Review by Tempo-anon — APPROVED** [review]
Approved by the wiki/tl team

**Pull request merged**
