### PR TITLE
Heal by leftovers if hp is max_hp - 1

### PR DESCRIPTION
**Pull request by hayuna**
## What are the changes?
Leftovers is not healing if pokemon has almost full hp

## Why am I doing these changes?
Fix healing functionality

## How to test the changes?
Have Leftovers on a Pokemon
Have 441/442 HP, or possibly any HP with -1 of total

## example
this.hp = 441
this.getMaxHP() = 442

if result of calculation is less than 1 => heal
### Before change
Math.round((this.hp / this.getMaxHp()) * 100) / 100;
Math.round((441 / 442) * 100) / 100 => 1
### After change
Math.floor((this.hp / this.getMaxHp()) * 100) / 100;
Math.floor((441 / 442) * 100) / 100 => 0.9977

```javascript
import { describe, expect, test } from "vitest"

function getHpRatio(currentHp, maxHp) {
    const ratio = currentHp / maxHp;
    const multiplier = Math.pow(10, maxHp.toString().length)
    return Math.round(ratio * multiplier) / multiplier;
}

describe('getHpRatio', () => {
    test('should return 0 if currentHp is 0', () => {
        const ratio = getHpRatio(0, 433)
        expect(ratio).toBe(0)
    })

    test('should return 1 if currentHp is maxHp', () => {
        const ratio = getHpRatio(433, 433)
        expect(ratio).toBe(1)
    })

    test('should return number between 0 and 1', () => {
        const ratio = getHpRatio(1, 9)
        expect(ratio).toBeGreaterThan(0)
    })

    test('should return number between 0 and 1', () => {
        const ratio = getHpRatio(8, 9)
        expect(ratio).toBeGreaterThan(0)
    })
    test('should return number between 0 and 1', () => {
        const ratio = getHpRatio(1, 99)
        expect(ratio).toBeGreaterThan(0)
    })

    test('should return number between 0 and 1', () => {
        const ratio = getHpRatio(98, 99)
        expect(ratio).toBeGreaterThan(0)
    })

    test('should return number between 0 and 1', () => {
        const ratio = getHpRatio(432, 433)
        expect(ratio).toBeGreaterThan(0)
    })

    test('should return number between 0 and 1', () => {
        const ratio = getHpRatio(1, 433)
        expect(ratio).toBeGreaterThan(0)
    })


    test('should return number between 0 and 1', () => {
        const ratio = getHpRatio(1, 10000)
        expect(ratio).toBeGreaterThan(0)
    })

    test('should return number between 0 and 1', () => {
        const ratio = getHpRatio(9999, 10000)
        expect(ratio).toBeGreaterThan(0)
    })
})
```

Screenshot 2024-06-07 at 18 55 17

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by hayuna** [comment]
Connected with https://github.com/pagefaultgames/pokerogue/issues/1875

**Comment by bennybroseph** [comment]
Uh, what if you have low HP and it returns 0% though

**Comment by bennybroseph** [comment]
@hayuna

**Comment by flx-sta** [comment]
https://discord.com/channels/1125469663833370665/1247574461780070420

**Comment by RABIGA7OR** [comment]
Why are you making this so complicated? The code already allows one to make precise calculations.

In my opinion you just need to change 1 line of code to fix this.

File: phases.ts line 4641
```
const fullHp = pokemon.getHpRatio() >= 1;
```

to

```
const fullHp = pokemon.getHpRatio(true) >= 1;
```

**Comment by layharu0** [comment]
in my opinion need to change this line

File: field/pokemon.ts line 784

`: Math.round((this.hp / this.getMaxHp()) * 100) / 100;`

to

`: Math.floor((this.hp / this.getMaxHp()) * 100) / 100;`

`Pokemon.getHpRatio()` was already used many times like `this.getHpRatio() < 1`

even if it is not needed to be precise(=getHpRatio(false)), we needs to distinguish between 99.5% and 100%

**Comment by hayuna** [comment]
> in my opinion need to change just this line
> 
> File: field/pokemon.ts line 784
> 
> `: Math.round((this.hp / this.getMaxHp()) * 100) / 100;`
> 
> to
> 
> `: Math.floor((this.hp / this.getMaxHp()) * 100) / 100;`
> 
> `Pokemon.getHpRatio()` was already used many times like `this.getHpRatio() < 1`
> 
> even if it is not needed to be precise(=getHpRatio(false)), we needs to distinguish between 99.5% and 100%

That was the initial commit, but we found out that its returning 0%

**Comment by layharu0** [comment]
how do you test it? can i see your test video or capture?

**Comment by minyukim** [comment]
What about adding `hasFullHp()` to Pokemon class and use it when we need to check if it has full HP?
```ts
hasFullHp(): boolean {
    return this.hp === this.getMaxHp();
  }
```
I believe it would be better if we change
`pokemon.getHpRatio() >= 1` to `pokemon.hasFullHp()`
`pokemon.getHpRatio() < 1` to `!pokemon.hasFullHp()`

**Comment by torranx** [comment]
would be nice if you can provide unit tests

**Comment by Tempo-anon** [comment]
Closing this as it looks like the issue was resolved.

**Pull request closed without merging**
