### PR TITLE
[Improvement] Add dev mode to simplify the test process

### PR DESCRIPTION
**Pull request by SnowCharmQ**
## What are the changes?

Add a dev mode in the main menu to skip the process of selecting new starter Pokémon when the environment variable is set `VITE_DEV_MODE=1`.

## Why am I doing these changes?

When I only need to test a battle and set the overridden variables, it is really troublesome to start by selecting the starter Pokémon, especially when I have to reset the whole game if I change the overridden variables. This PR aims to simplify the process of testing battles by skipping the starter Pokémon selection. When VITE_DEV_MODE=0 is set in the production environment, it will not affect the regular game.

## What did change?

- In _phases.ts_ TitlePhase, update the menu text for the new game and add a new method `toDev` to skip the starter Pokémon selection.
- For the environment variables, add a new item `VITE_DEV_MODE`.

### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/82224175/926c6421-b473-4802-8128-512d94e4b9e1

## How to test the changes?

Simply updating the environment variable `VITE_DEV_MODE` to test the dev mode, and start a new game by setting the overridden variables.

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by ben-lear** [comment]
Some unit tests to show this skips the starter phase properly when enabled and doesn’t when disabled might be pretty nice.

**Comment by SnowCharmQ** [comment]
> Some unit tests to show this skips the starter phase properly when enabled and doesn’t when disabled might be pretty nice.

Hi! Do you have any suggestions about how to add some unit tests? I have no idea to test whether the starter phase can be skipped properly since it is only controlled by the environment variable.

**Comment by DayKev** [comment]
Instead of always bypassing starter select, it should add a new "Classic (Dev)" mode below standard classic mode that skips starter select (sometimes we're testing things that need to go through starter select after all, possibly the starter select UI itself).

**Comment by flx-sta** [comment]
Please address the comment and resolve the conflicts

**Comment by flx-sta** [comment]
@SnowCharmQ  closed for being stale (no updates for over a month)

----

Feel free to create a new PR or ask us to re-open this one.

**Pull request closed without merging**
