### PR TITLE
[QoL] Make IV-Scanner less annoying, by giving it a toggle and the ability to scan stuff at any time by clicking on the icon

### PR DESCRIPTION
**Pull request by karl-police**
**Edit:** scroll down, I fixed some stuff

I was trying to figure out how to do this for like way too long. I am not happy with the end result.

The freaking code base has a bunch of lines but **lack comments above them**, that explain what is what. So, when I was trying to figure out what the hell ``Mode.MESSAGE`` and the rest is for, I had a mental breakdown.

And the result, is buggy. Except the Toggle button, that one works... So I expect someone to like tell me how to fix, yes?? :) :) :)

&nbsp;

Anyways, let me explain the change.

FIRST, I tried to push back **CommandPhase** dynamically. But that thing would break, here's my freak out post about it: https://github.com/pagefaultgames/pokerogue/issues/1062

So, then I decided to do this more stupid. But eventually, it's not really that bad actually.

&nbsp;

Currently, nobody will freaking choose the IV-Scanner if they've chosen it once, pretty sure. That freaking thing prompts a player if you want to scan a Pokemon every encounter, everytime.

So, I added a Toggle.

You **click** on the Modifier. And yes, I tried to listen to the SOLID Principle and OOP. There's a ``onClick`` method that gets now called onto all the Modifiers in that Modifiers bar, but it doesn't do anything unless you assign it something.

This should even function on mobile.

Eitherways.

&nbsp;

This UI Container will open. It opens like that, because I copy pasted the other existing code and I think the offset is alright too.

The Toggle button is amazing and it toggles stuff.

&nbsp;

&nbsp;

**Then!**, the other option is that you can scan anything anywhere. Ofc only if it's a wild encounter and bla bla bla.

You simply click on it.

Draw back is, you'll be stuck with this box until the end of the turn.

This is where I need help with. And yep. Okay thanks.

### CODE REVIEW

**Comment by bennybroseph** [comment]
This has to work for controller players as well. Is there a way to activate this on controller?

**Comment by karl-police** [comment]
> This has to work for controller players as well. Is there a way to activate this on controller?

Is controller able to select the UI stuff?

**Comment by karl-police** [comment]
controller can't hover to display modification description either, can they? 🤔 


at that point I'd just put a IV-Scanner button inside the Pokeball Menu.

once UI functions have docs or something like that, yep

**Comment by j-diefenbach** [comment]
Just putting it out here that I worked on a base stat estimate display for fun, like the stat changes display shown with 'C'. It might be better to use that kind of a system and be able to toggle the display at any time ( if that's what you're going for) rather than relying on mouse click. Since there was some talk about changing at and using it as a QOL update for the IV scanner.
Ofcourse there are issues with the method such as using another button and having to set that up for controllers and touchpad but that would be better than mouse input. Additionally you could have it set to automatically display at the start of a battle.
For reference I had something like this but I imagine you could modify it slightly.
image

**Comment by karl-police** [comment]
Making this more compact
image

**Comment by karl-police** [comment]
Alright so far I figured out how to get rid of the conflicting box without breaking it

image

**Comment by karl-police** [comment]
I think I got it now by using ``.then()`` since promptIvs is a Promise

**Comment by karl-police** [comment]
@bennybroseph now the UI looks like this

image

And I fixed this

image

**Comment by karl-police** [comment]
hmm
image

**Comment by karl-police** [comment]
Now, is fully functional.

Well, someone will probably not like that it's under the Ball now 🤔

**Comment by CodeTappert** [comment]
It should definitly not be under "ball". 

Either change ball to "items" or "bag" and then have several slides like in the real games or place it somewhere else

**Comment by karl-police** [comment]
> It should definitly not be under "ball".
> 
> Either change ball to "items" or "bag" and then have several slides like in the real games or place it somewhere else

What slides.

**Comment by CodeTappert** [comment]
> > It should definitly not be under "ball".
> > Either change ball to "items" or "bag" and then have several slides like in the real games or place it somewhere else
> 
> What slides.

Well. My english is not perfect so lets try me to explain.

If you open your bag in the original games then you have "subbags" for balls, healing, TM, berries etc.

That is what i mean by it.

**Comment by karl-police** [comment]
> > > It should definitly not be under "ball".
> > > Either change ball to "items" or "bag" and then have several slides like in the real games or place it somewhere else
> > 
> > 
> > What slides.
> 
> Well. My english is not perfect so lets try me to explain.
> 
> If you open your bag in the original games then you have "subbags" for balls, healing, TM, berries etc.
> 
> That is what i mean by it.

Question is, would anyone get annoyed by that, for having to do 1 extra click to access Ball?

**Comment by CodeTappert** [comment]
Probably yes.

But i think having the scanner there is at least as annoying as having a extra click.

Having the toogle in a existing menu like the shop overlay like this other PR has would be better imo

**Comment by CodeTappert** [comment]
> > Probably yes.
> > But i think having the scanner there is at least as annoying as having a extra click.
> > Having the toogle in a existing menu like the shop overlay like this other PR has would be better imo
> 
> Btw. this is not only a Toggle. It opens a Menu, to toggle the IV-Scanner, but also to directly scan pokemons.
> 
> Having that button, in the area where all Pokemons are defeated, uhhh gives you nothing to scan.

I get that. And i agree. 
But there isnt really a place for this. 
Maybe just wait until the discord is open again and then ask for opinions/feedback

**Comment by karl-police** [comment]
> > > Probably yes.
> > > But i think having the scanner there is at least as annoying as having a extra click.
> > > Having the toogle in a existing menu like the shop overlay like this other PR has would be better imo
> > 
> > 
> > Btw. this is not only a Toggle. It opens a Menu, to toggle the IV-Scanner, but also to directly scan pokemons.
> > Having that button, in the area where all Pokemons are defeated, uhhh gives you nothing to scan.
> 
> I get that. And i agree. But there isnt really a place for this. Maybe just wait until the discord is open again and then ask for opinions/feedback

Maybe. Right now I am trying to explore more about these UI things. Pokeball UI is a mess, it's not using a Options menu, so adding that there was not really ideal.

What I'd do, is a menu, that you open by pressing a button. And if people like Ball to Bags thing, then it can be bound there at any time.

This little menu would be great, not to only configure modifiers, but for any future feature. A good place to put stuff at.

**Comment by karl-police** [comment]
Now it will play the animation when force scanning as well.

image

**Comment by j-diefenbach** [comment]
> I get that. And i agree. But there isnt really a place for this. Maybe just wait until the discord is open again and then ask for opinions/feedback

Yeah i agree this is something that can wait for a better overhaul. Especially adding it to the balls screen seems out of place. If we had some sort of bag system set up that would be the perfect place for it but otherwise I wouldn't put it somewhere it doesn't go. Especially relying on hovering over the item or a bunch of extra settings for what is meant to be a QOL change seems counterintuitive.

**Comment by Kelvez** [comment]
There is a discussion about the IV scanner on the Discord. We have asuggestion for the overhaul of the IV scanner.

We were thinking about a new icon for the IV scanner located next to the pokeball icon that says either a pokemon has already by captured or not : 
image
Here on the image.

The idea is, when you have the IV scanner you have no pop up but the icon appears when the pokemon has better statistics. The icon could be green when the pokemon has a better stat, yellow if the pokemon has a max stat that you do not have and grey or even not appears if it has lower stat.

And to see more in details and have the pop up you could toggle a button. So with this, people don't have the annoying popup and can easily see, just next to the pokeball that says if the pokemon has new ability, if the pokemon is interesting to catch or not. And if interested toggle the button.

It is just our suggestion but I think this would be really appreciated by all because I think it will be a LOT LESS annoying to take the IV scanner to catch interesting pokemons.

Tell me what you think about this suggestion and thank you for trying to overhaul the IV scanner 🙏

**Comment by flx-sta** [comment]
ℹ️ PR considered stale. No actions in the last 30 days.

-----

❗ Feel free to ping me/comment if you want to re-open it

**Pull request closed without merging**
