### PR TITLE
[Bug] Added `failIfSingleBattle` condtion to Doubles-only moves

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes the user will see?
Helping Hand and other NearAlly moves should show a failure message.

## Why am I making these changes?
I don't know either.
Note to self: Link bug report too

## What are the changes from a developer perspective?
The declarations of Helping Hand and other doubles-only moves (I don't know, it's late) now has the failIfSingleCondtional

### Screenshots/Videos

https://github.com/user-attachments/assets/e25450de-04ea-41b8-af95-a5a4fa6d4e53

## How to test the changes?
Force a Pokemon to use Helping Hand in Single battle. Failure message should appear. 

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by innerthunder — COMMENTED** [review]
Should this apply to other `NEAR_ALLY` moves?

**Comment by frutescens** [comment]
@innerthunder I went through this list on Bulbapedia and added failIfSingleBattle conditions to them. 
image

**Review by Tempo-anon — APPROVED** [review]
It was such a simple fix for a long reported bug :goomed:

**Comment by innerthunder** [comment]
> @innerthunder I went through this list on Bulbapedia and added failIfSingleBattle conditions to them. image

This isn't the correct list to use. Looking at Bulba's page on [Follow Me](https://bulbapedia.bulbagarden.net/wiki/Follow_Me_(move)):

> Follow Me has no effect on moves which hit multiple Pokémon in a battle. **While it can be used in Single Battles**, it has no effect.

On the other hand, [Coaching](https://bulbapedia.bulbagarden.net/wiki/Coaching_(move)), another `NEAR_ALLY` targeting move, does fail:

> If used in a Single Battle or when no ally is present, Coaching will fail.

**Review by Tempo-anon — APPROVED** [review]

**Pull request merged**
