### PR TITLE
[Sprite] Fix Courtney eye whites

### PR DESCRIPTION
**Pull request by chaosgrimmon**
## What are the changes the user will see?
Magma Admin Courtney's sprite now has white sclera, as well as a few other optimisations.

## Why am I making these changes?
Reported [here](https://discord.com/channels/1125469663833370665/1277005388692066414).

Replaced transparent sclera regions with opaque white pixels.
Erased a white pixel at the top edge of the sprite.
Replaced several near-black palette entries with the standard 0x101010.
Converted the sprite to PNG-8 indexed bit depth.

## What are the changes from a developer perspective?
No mechanical changes. Replaced one .png with another.

#### Before
image
#### After
image

## How to test the changes?
As far as I know, the optimal way to produce fresh legitimate results is to set STARTING_WAVE_OVERRIDE to 66 and hope for the best.

My results were achieved using this way, though naturally a PokeRogue SaVe should have the file ending `.prsv`.
[sessionData_Courtney.txt](https://github.com/user-attachments/files/16808266/sessionData_Courtney.txt)

Alternatively, renaming the files in `\images\trainers` can allow a more common encounter like a rival or a youngster to use Courtney's sprite .png and animation .json.

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
~~- [ ] Have I considered writing automated tests for the issue?~~
~~- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?~~
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

## Links:

- https://www.deviantart.com/icejkai/art/Team-Magma-Grunts-Trainer-Sprites-536151006
- https://www.deviantart.com/icejkai/art/Magma-Admin-Courtney-Trainer-Sprite-544510574

### CODE REVIEW

**Review by DayKev — APPROVED** [review]

**Review by flx-sta — APPROVED** [review]
yup. that's less scary

**Comment by CodeTappert** [comment]
Are we even allowed to do that? Since that Sprite is from a external artist(Devianart)

**Comment by chaosgrimmon** [comment]
image

> Are we even allowed to do that? Since that Sprite is from a external artist(Devianart)

Are we allowed to edit their sprite? Given that the goal of this PR is mostly to make it match our technical and aesthetic goals, like it's not like I'm not doing this as a snub or slight, yeah?
Are we allowed to use the sprite in general? Their stated wishes in general don't seem opposed, but dude, you're the one that found this sprite in the first place. 

image

**Comment by flx-sta** [comment]
Can you put the links to those originals please?

**Review by Tempo-anon — APPROVED** [review]
You can also test this by just changing the classic fixed battles so only Courtney spawns on wave 1 or 2

**Comment by CodeTappert** [comment]
> image
> 
> > Are we even allowed to do that? Since that Sprite is from a external artist(Devianart)
> 
> Are we allowed to edit their sprite? Given that the goal of this PR is mostly to make it match our technical and aesthetic goals, like it's not like I'm not doing this as a snub or slight, yeah? Are we allowed to use the sprite in general? Their stated wishes in general don't seem opposed, but dude, you're the one that found this sprite in the first place.
> 
> image

Yeah this is what i saw so i was sure we are allowed to use it. But i wasnt sure about changing. But well i guess its fine.

**Pull request merged**
