### PR TITLE
Implement Poison Puppeteer

### PR DESCRIPTION
**Pull request by arColm**
Added new ability attribute `ConfusionOnStatusEffectAbAttr` which is applied when a move applies a status effect successfully.

### CODE REVIEW

**Review by bennybroseph — CHANGES_REQUESTED** [review]
Could we get a video of this move working in game? 

Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

**Comment by arColm** [comment]
> Could we get a video of this move working in game?
> 
> Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

Documentation done. This ability only works on Pecharunt, as is stated in bulbapedia. Not sure if we want to keep it that way for this game

- Confusion applied on Poison and Toxic
- Failing to apply Poison/Toxic does not apply confusion
- Confusion lasts correct number of turns
- Toxic Spikes does not proc confusion

https://github.com/pagefaultgames/pokerogue/assets/20668254/86be51ea-10fe-41af-bb28-dec4721eb6cc

**Comment by Xavion3** [comment]
Could you fix the merge conflicts?

**Comment by arColm** [comment]
> Could you fix the merge conflicts?

Done

**Review by TempsRay — COMMENTED** [review]
LGTM. @bennybroseph if you remove your request changes then this can get merged in.

**Comment by Xavion3** [comment]
Github says there are still merge conflicts.

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
