### PR TITLE
[P1 Bug] Prevent crash from missing pokemon sprite

### PR DESCRIPTION
**Pull request by dp0ch**
## What are the changes the user will see?
Fixes a bug where the game would crash if a pokemon sprite didn't load. The user will see the substitute sprite (images/pokemon/sub.png) or the phaser default sprite if that also isn't available.
Applies to potential crashes in
- egg hatch phase
- evolution phase
- form change phase
- GTS encounter
- weird dream encounter
- pokemon summary view

## Why am I making these changes?
Fixes https://github.com/pagefaultgames/pokerogue/issues/2599

## What are the changes from a developer perspective?
Catch errors from `Phaser.Sprite.play()` which throws if sprite isn't available. Prints error to console.

### Screenshots/Videos
https://github.com/user-attachments/assets/8793f500-1406-43cf-a9a8-5be2b42e1548

https://github.com/user-attachments/assets/b82fbb8e-2206-4609-b5e6-2ed100c28346

https://github.com/user-attachments/assets/df90e2c7-dc90-479e-b088-585a36ed5dc4

https://github.com/user-attachments/assets/4f17b1ab-0c0e-48b6-b383-296d557d5810

https://github.com/user-attachments/assets/a7e8b994-00b3-4632-8f8c-1e136d45028e

https://github.com/user-attachments/assets/9d458c65-5f7c-4309-8dd8-f4b1952be4d7

https://github.com/user-attachments/assets/85de428c-5b62-4df4-bfec-e436a5e51a6c

## How to test the changes?
- Remove/rename relevant sprite
- Clear cache to force cache miss

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by Tempo-anon — DISMISSED** [review]
Looks good to me. This just wraps all the `sprite.play`'s in a try-catch

**Comment by MokaStitcher** [comment]
I imagine there could be issues with the sprites in MysteryEncounterIntro too? Can you have a quick look and let me know if you think we need to do the same thing there?
Although I wouldn't recommend touching that file right now since I changed a fair bit of the sprite code there in PR #4827. So maybe that should be a separate PR once it gets merged

**Comment by PigeonBar** [comment]
Mystery Encounter Intro should be fine:

https://github.com/user-attachments/assets/c7448d35-f82b-4262-929d-61eae1aef7a5

**Comment by PigeonBar** [comment]
Could you please also add fixes for QuietFormChangePhase:

https://github.com/pagefaultgames/pokerogue/blob/162eea500dcfaa5e39b06481339a60ebfb2d0c78/src/phases/quiet-form-change-phase.ts#L46
https://github.com/pagefaultgames/pokerogue/blob/162eea500dcfaa5e39b06481339a60ebfb2d0c78/src/phases/quiet-form-change-phase.ts#L84

as well as `setFrameRate()` (which gets called when slowing down a Pokemon's animation when it gets put to sleep):

https://github.com/pagefaultgames/pokerogue/blob/162eea500dcfaa5e39b06481339a60ebfb2d0c78/src/field/pokemon.ts#L3704-L3708

**Comment by DayKev** [comment]
Instead of adding a `try/catch` for every single `sprite.play()` in the codebase, maybe it would be simpler to extend Phaser's `Sprite` class and its `play()` method and put the `try/catch` in there. Then find/replace every instance of `Phaser.GameObjects.Sprite` with our new `Sprite` class.

```ts
export class Sprite extends Phaser.GameObjects.Sprite {
  public override play(key: string | Phaser.Animations.Animation | Phaser.Types.Animations.PlayAnimationConfig, ignoreIfPlaying?: boolean): this {
    try {
      return super.play(key, ignoreIfPlaying);
    } catch (err: unknown) {
      console.error(`Failed to play animation for ${key.toString()}:`, err);
      return this;
    }
  }
}
```

**Comment by DayKev** [comment]
> Could you please also add fixes for QuietFormChangePhase:
> 
> https://github.com/pagefaultgames/pokerogue/blob/162eea500dcfaa5e39b06481339a60ebfb2d0c78/src/phases/quiet-form-change-phase.ts#L46
> 
> 
> https://github.com/pagefaultgames/pokerogue/blob/162eea500dcfaa5e39b06481339a60ebfb2d0c78/src/phases/quiet-form-change-phase.ts#L84
> 
> as well as `setFrameRate()` (which gets called when slowing down a Pokemon's animation when it gets put to sleep):
> 
> https://github.com/pagefaultgames/pokerogue/blob/162eea500dcfaa5e39b06481339a60ebfb2d0c78/src/field/pokemon.ts#L3704-L3708

Applied the suggested changes.

**Review by DayKev — APPROVED** [review]

**Review by MokaStitcher — APPROVED** [review]

**Review by CodeTappert — APPROVED** [review]

**Pull request merged**
