### PR TITLE
Add new Double Battles

### PR DESCRIPTION
**Pull request by CodeTappert**
New Sprites by Brumirage whose Sprites we already use. (Source: https://play.pokemonshowdown.com/sprites/trainers/credits/)

This will stay as a draft until we merge https://github.com/pagefaultgames/pokerogue/pull/1254

since i dont want to do the dialogue twice.

I will add more doubles when they make sense. 

Currently:
Added Volo/Cynthia and Leon/Hop and 

- Koga & Janine
- Geeta & Nemona
- Opal & Bede
- Kieran & Carmine
- Lance (Champ) & Clair
- Hau & Kukui
- Diantha & Korrina (They meeet each others several times in the anime)
- - Sinnoh Gym Leader 1/Sinnoh Steel Gym Leader (they are father and son)

With those 4 all champs have a potential partner

Also Trainers now use
- main: 1,2,3 of their pool
- Partner -1,-2,-3 (from behind) of their pool
If they dont have enough they will get a random

### CODE REVIEW

**Comment by CodeTappert** [comment]
Probably:
- Koga & Janine
- Geeta & Nemona

**Comment by bennybroseph** [comment]
I really like these duo double battles btw

**Comment by CodeTappert** [comment]
Also TODO: Add Solo Dialogue for all the new trainer Types i added. They currently arent spawnable but who knows...

**Comment by CodeTappert** [comment]
So i added the new trainers, dialogue for them, localized the dialogue and of course also for their doubles.

This is ready for a review

**Comment by CodeTappert** [comment]
Could a native english speaker please control the english dialogue? I am not one so there may be errors

**Comment by CodeTappert** [comment]
After doing 133 Trainer Battles in a row just now (and fixing some dialogue while doing so). I a, positive that this is ready for review

**Comment by Adri1** [comment]
I opened a PR to your branch with French translations

**Comment by CodeTappert** [comment]
> I opened a PR to your branch with French translations

Look at this trainer classes. I think you got the wrong one https://bulbapedia.bulbagarden.net/wiki/Volo

**Comment by Adri1** [comment]
> > I opened a PR to your branch with French translations
> 
> Look at this trainer classes. I think you got the wrong one https://bulbapedia.bulbagarden.net/wiki/Volo

"Percupio" is the right transaltion French of "Volo", unless you are talking about something else, I can't see right now

**Comment by CodeTappert** [comment]
> > > I opened a PR to your branch with French translations
> > 
> > 
> > Look at this trainer classes. I think you got the wrong one https://bulbapedia.bulbagarden.net/wiki/Volo
> 
> "Percupio" is the right French transaltion of "Volo", unless you are talking about something else I can't see right now

Trainer Class -> 

You did 

```
"pkm_tamer": "Dompteur",
  "pkm_tamer_female": "Dompteuse",
```


But it should be
```

"pkm_tamer": "Expert en Pokémon",
  "pkm_tamer_female": "<female version>",
```

(i need to change the english version as well...)

The correct english class is Pokémon Wielder not Pokemon Tamer like i assumed

**Comment by Adri1** [comment]
> The correct english class is Pokémon Wielder not Pokemon Tamer like i assumed

Ah yes I was baited precisely because "Tamer" is the name of a class that exisits since Red and Blue

**Comment by Adri1** [comment]
> > > The correct english class is Pokémon Wielder not Pokemon Tamer like i assumed
> > 
> > 
> > Ah yes I was baited precisely because "Tamer" is the name of a class that exisits since Red and Blue
> 
> I just changed the english name and the key. Please change the key also in french (or just first merge my branch into yours)

All good, French version edited

**Comment by Adri1** [comment]
I created a new PR, somehow it seems I accidentally deleted Red and Blue duos in French trainers.ts
Sorry for the inconvenience

**Comment by bennybroseph** [comment]
Man, you gotta stop making these so long for no reason. please split this up. small typo's in these can cause entire lines of dialogue to not work or a crash to happen when these get encountered and i don't have time to nit-pick these changes.

**Comment by CodeTappert** [comment]
> Man, you gotta stop making these so long for no reason. please split this up. small typo's in these can cause entire lines of dialogue to not work or a crash to happen when these get encountered and i don't have time to nit-pick these changes. i really really want to add these but this is just too much

Well this is on hold anyways...

I will make a seperate PR for the bug fixes in it

**Comment by CodeTappert** [comment]
The bugfix PR: https://github.com/pagefaultgames/pokerogue/pull/1582

**Comment by CodeTappert** [comment]
Draft because i dont know if this is wanted at all, if it will be still changed. And not even when the decision about this will be made

**Comment by CodeTappert** [comment]
image

I will let this as a draft since i dont want to redo that later. And we can change the team generation still

**Pull request closed without merging**
