### PR TITLE
[Bugfix #3930] Moves That a Pokemon Knows and are not in their List of Learnable TMs Display as "Not Able" Rather than Learned

### PR DESCRIPTION
**Pull request by njahja**
## What are the changes the user will see?
If a Pokemon knows a move that is not in their list of compatible TMs, the text that is displayed will now say "Learned" rather than "Not Able"

## Why am I making these changes?
This is a bug fix for [#3930](https://github.com/pagefaultgames/pokerogue/issues/3930)

## What are the changes from a developer perspective?
Just changing the order in the switch case block in the `party-ui-handler.ts` file for TMs.

### Screenshots/Videos
When trying to learn move Dragon Dance via TM:
Screenshot 2024-08-30 225559

If Bulbasaur has the move Dragon Dance, text will show as "Learned"
Screenshot 2024-08-30 230126
Screenshot 2024-08-30 225631

If Bulbasaur does not have Dragon Dance, text will show as "Not Able"
Screenshot 2024-08-30 225833
Screenshot 2024-08-30 225821

## How to test the changes?

- tested with overrides to the starting pokemon to have Dragon Dance and the item reward to include the Dragon Dance TM
- tested with just override for item reward to include Dragon Dance and see how it interacts with a Pokemon that is incompatible with the Dragon Dance TM

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by Tempo-anon — APPROVED** [review]

**Review by DayKev — DISMISSED** [review]

**Review by innerthunder — APPROVED** [review]
The fact this code uses `switch(true)` is cursed but this seems fine

**Comment by Tempo-anon** [comment]
> The fact this code uses `switch(true)` is cursed but this seems fine

lmao you're right. This really should be an if/elif/else

**Comment by DayKev** [comment]
> The fact this code uses `switch(true)` is cursed but this seems fine

Oh my god I wasn't even paying attention to that, what the fuck???

**Review by innerthunder — CHANGES_REQUESTED** [review]
Actually, can you just change this `switch` statement to an `if / else if / else`? This is bothering me too much lol

**Review by innerthunder — APPROVED** [review]

**Review by Tempo-anon — APPROVED** [review]

**Pull request merged**
