### PR TITLE
[Test] Prevent tests from running if overrides are different from the default values

### PR DESCRIPTION
**Pull request by OrangeRed**
## What are the changes?
Mock default values for Overrides module

## Why am I doing these changes?
Too many people complain about failing tests when having custom overrides

## What did change?
the test setup file

### Screenshots/Videos
```
 ✓ src/test/settingMenu/rebinding_setting.test.ts (33)
 ✓ src/test/sprites/pokemonSprite.test.ts (15) 542ms
 ✓ src/test/moves/tackle.test.ts (2) 1584ms
 ✓ src/test/battle/battle-order.test.ts (5) 4437ms
 ✓ src/test/abilities/zen_mode.test.ts (3) 2899ms
 ✓ src/test/battle/special_battle.test.ts (9) 9748ms
 ✓ src/test/abilities/intimidate.test.ts (10) 13666ms
 ✓ src/test/battle/battle.test.ts (20) 15942ms
 ✓ src/test/ui/starter-select.test.ts (9) 2930ms
 ✓ src/test/achievements/achievement.test.ts (20) 453ms
 ✓ src/test/inputs/inputs.test.ts (11) 6650ms
 ✓ src/test/items/toxic_orb.test.ts (1) 1062ms
 ✓ src/test/moves/growth.test.ts (1) 1427ms
 ✓ src/test/moves/tail_whip.test.ts (1) 1372ms
 ✓ src/test/abilities/moxie.test.ts (1) 3888ms
 ↓ src/test/battle/error-handling.test.ts (1) [skipped]
 ✓ src/test/utils/misc.test.ts (5) 1747ms
 ✓ src/test/phases/phases.test.ts (3) 5562ms
 ✓ src/utils.test.ts (6)
 ✓ src/test/abilities/intrepid_sword.test.ts (1) 683ms
 ✓ src/test/lokalisation/french.test.ts (2) 1204ms
 ✓ src/test/eggs/egg.test.ts (2)
 ✓ src/test/imports.test.ts (2)
```

## How to test the changes?
npm run test:silent

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
~~- [ ] Are the changes visual?~~
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Greenlamp2** [comment]
it's not needed since we use this options:
https://github.com/pagefaultgames/pokerogue/blob/f57798fd1d7210282895a02c2be0dd85fe181f70/vitest.config.js#L18

**Comment by OrangeRed** [comment]
> it's not needed since we use this options:

The issue isn't them being reset its that if someone edits the base `src/overrides.ts` those changes will propagate into the start of the tests without getting reset

**Comment by Greenlamp2** [comment]
> > it's not needed since we use this options:
> 
> The issue isn't them being reset its that if someone edits the base `src/overrides.ts` those changes will propagate into the start of the tests without getting reset to default values

i see, indeed, beforeAll make much sense then, but i think i'd prefer an error message and faill tests to say to disable their override instead of this, to be sure they don't push their override for example.

let me discuss it with other dev to see what they think is the best, if they got the same opinions than you, i'll merge it

**Comment by Greenlamp2** [comment]
IMG_9777
Do you think you could check the latest ?

**Comment by OrangeRed** [comment]
@brain-frog When should the error be displayed? 

This PR mostly addresses bullet point one by hard reset all overrides to their default values. Any new overrides that get added will simply be passed through.

For the second bullet point did you mean that this pass through isn't desirable and that it should be tested against before the tests start?

**Comment by OrangeRed** [comment]
@Greenlamp2 @brain-frog Can you guys give me your thoughts on this again.

The issue I has having is that in `src/overrides.ts` when importing an enum inside a file that imports i18n the resulting module import initializes i18n which drastically slows down the pre tests.

**Review by flx-sta — APPROVED** [review]
Code review

**Review by flx-sta — APPROVED** [review]

**Pull request merged**
