### PR TITLE
Resolve TODO on Sky Drop "Add 2nd Turn Message"

### PR DESCRIPTION
**Pull request by brandonarude**
Currently, moves using the ChargeAttr only show custom messages on the first turn. To address the TODO for the second turn message ("The {Target} was freed from Sky Drop!"), I extended the ChargeAttr class into SkyDropChargeAttr and added a flag that would trigger the message on the second turn of the move.

By extending the class in this way, it also opens the door to implementing the other functions of this move that are found in the mainline games.

### CODE REVIEW

**Comment by TempsRay** [comment]
While you're here in sky drop, do you mind implementing the part where it fails against 200+kg opponents?

**Comment by brandonarude** [comment]
I'll certainly try!  This is my first time contributing to an open source project, and I'm still getting my head around the codebase.

**Comment by brandonarude** [comment]
Alright, added the check for weight, and tested on a Ho-oh (199kg) and Crustle (200kg). As expected, it worked on the former and failed on the latter.

**Review by bennybroseph — CHANGES_REQUESTED** [review]
Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

**Comment by brandonarude** [comment]
Alright, I think I got the JSDocs added properly! Let me know if any further changes are needed!

**Comment by bennybroseph** [comment]
Lastly, can we get a video of this being tested? Need a normal interaction and one with a pokemon that is too heavy

**Comment by brandonarude** [comment]
Yep! Here's the success:

[Skydrop Success-1.webm](https://github.com/pagefaultgames/pokerogue/assets/38122826/3116318a-8f69-497a-91b2-af8493a355dc)


And here's the failure:

[Skydrop Failure-1.webm](https://github.com/pagefaultgames/pokerogue/assets/38122826/e79ca27d-bb13-4ae5-80b6-064099da05c1)

**Comment by bennybroseph** [comment]
Seeing multiple issues unfortunately. Sky Drop works similar to Fly/Dive/Dig except for both Pokemon. Ho-oh should have it's sprite hidden and anything that targets it misses just like Fly/etc. Ho-oh should also be immune to the damage from Sky Drop since it's flying type. They should still get hit by gust, thunder, thousand arrows, etc. 

Please read up on the following and let me know which interactions still have to be considered.

[source](https://bulbapedia.bulbagarden.net/wiki/Sky_Drop_(move))

**Comment by Tempo-anon** [comment]
Sky drop is actually much more complex to fully implement. Closing this for now due to inactivity and issues

**Comment by brandonarude** [comment]
Yep! Sorry about the inactivity. Makes sense to close this, bit off a bit more than I could chew!

**Pull request closed without merging**
