### PR TITLE
[Feature]Highlight usable pokemon in green during a challenge

### PR DESCRIPTION
**Pull request by marcodola**
## What are the changes?

During a challenge it's quite difficult to understand if the pokemon you're facing will be usable with the current constraints
## Why am I doing these changes?

Often the user it's not able to understand if a wild pokemon it's going to be playable in the challenge, they have to check on the Internet if it's the proper gen or it will evolve in an usable type
## What did change?

I added a method that use the same logic of the starter pokemons screen, checking the species of the pokemon an the ones of its evolutions/forms 
### Screenshots/Videos

This is an example in how the change looks like
pokerouge_color

## How to test the changes?

I tested it by playing the game both with and without challenge facing some pokemon.
## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Jancojicanoder** [comment]
All of them are green if they're eventually usable or just the immediate usable ones?

**Comment by marcodola** [comment]
@Jancojicanoder the code use the same logic of the starter screen: if the mon of one its evolutions/forms is ok it's highlighted in green

**Review by CodeTappert — CHANGES_REQUESTED** [review]
Looks good. 

Could you still provide a video showing it with a pokemon that gets only legal when it would be evolved? Just so we can be sure.

For example a magikarp in a flying only challenge.

**Comment by marcodola** [comment]
@CodeTappert  I recorded a game in which I started a water challenge and encountered a Bidoof, since it's evolution (Bibarel) is nomal/water the name is highlighted 

https://github.com/user-attachments/assets/25ce3113-e244-4522-883f-8facef4b82b2

**Review by 40chyan — APPROVED** [review]

**Review by CodeTappert — APPROVED** [review]

**Comment by frutescens** [comment]
Would you happen to be still working on this?

**Comment by marcodola** [comment]
Hi @frutescens,
No, I'm not currently working on this. If you have any requests I may try to implement them

**Comment by frutescens** [comment]
I think that this would be a really great idea. Could you try to match the colors used in TextStyle.SUMMARY_GREEN? In addition, how does this look in the Legacy UI Mode?

**Comment by marcodola** [comment]
@frutescens sure, it might take a little bit (I'm doing this on my spare time).

**Comment by frutescens** [comment]
All good. Take your time + ping me when you feel its ready.

**Comment by marcodola** [comment]
@frutescens I got a couple of hours to spare and I changed the color of the name and added an option in the settings to enable the feature.
This is how it looks like with the default UI Mode:
default name
And this is with the legact mode;
legacy name
The option can be found there
settings option

**Comment by flx-sta** [comment]
@marcodola are you still working on this?
Cause the commits seem broken

**Comment by marcodola** [comment]
Hi @frutescens, no I'm not working on it.
Sorry but GitHub this
Screenshot_2024-09-13-20-46-18-400_com android chrome
Can you help me? I'm new to GitHub

**Pull request closed without merging**
