### PR TITLE
[P2][Move] Fix Substitute blocking field effects

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes the user will see?
This fixes a bug where several field effects, including Tailwind, Trick Room, screens, and hazards, would erroneously be blocked by Substitute, displaying an incorrect "no effect" message and/or cancelling the effect completely

## Why am I making these changes?
Cleaning up my own messes

## What are the changes from a developer perspective?
- `data/move`: `Move#hitsSubstitute` now returns false if the Move targets a side of the field (i.e. `this.moveTarget` is `USER_SIDE`, `TARGET_SIDE`, or `BOTH_SIDES`).
- `test/moves/substitute.test`: 3 new unit tests on the effectiveness of moves targeting different sides of the field.

## How to test the changes?
`npm run test substitute`

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Snailman11** [comment]
Link to Discord's Bug Report (9/28 Tailwind "has no effect on brambleghast" used behind substitute)
https://discord.com/channels/1125469663833370665/1289796155172982785

**Comment by torranx** [comment]
> data/move: Move#hitsSubstitute now returns false if the Move targets a side of the field (i.e. this.moveTarget is USER_SIDE, TARGET_SIDE, or BOTH_SIDES).

are the specified enums used for status moves only?

**Comment by DayKev** [comment]
> > data/move: Move#hitsSubstitute now returns false if the Move targets a side of the field (i.e. this.moveTarget is USER_SIDE, TARGET_SIDE, or BOTH_SIDES).
> 
> are the specified enums used for status moves only?

That enum is used for all moves.

**Comment by innerthunder** [comment]
> > data/move: Move#hitsSubstitute now returns false if the Move targets a side of the field (i.e. this.moveTarget is USER_SIDE, TARGET_SIDE, or BOTH_SIDES).
> 
> are the specified enums used for status moves only?

The affected `MoveTarget` enums (`USER_SIDE`, `TARGET_SIDE`, and `BOTH_SIDES`) are currently only used for status moves. There are some attacks that apply arena tags to the field (e.g. Glitzy Glow or Stone Axe), but those use default attack targeting (`NEAR_OTHER` iirc). Wish and Imprison also add arena tags but are internally considered self-targeted (`USER`)

**Comment by DayKev** [comment]
Wait some of the enum members are only for status moves? Really? Is that correct behavior though?

**Comment by torranx** [comment]
> The affected `MoveTarget` enums (`USER_SIDE`, `TARGET_SIDE`, and `BOTH_SIDES`) are currently only used for status moves. There are some attacks that apply arena tags to the field (e.g. Glitzy Glow or Stone Axe), but those use default attack targeting (`NEAR_OTHER` iirc). Wish and Imprison also add arena tags but are internally considered self-targeted (`USER`)

wouldnt it be better to specify for status moves too then?

**Comment by innerthunder** [comment]
> wouldnt it be better to specify for status moves too then?

I don't see much of a point. No attack (including the N/P ones) targets the field in this way.

**Review by DayKev — APPROVED** [review]

**Pull request merged**
