### PR TITLE
Added the type icon localization

### PR DESCRIPTION
**Pull request by CodeTappert**
This was part of PR #918 

But is now on his own.

It working on fight screen:
- image

It working on summary:
image

It working Starter Select 
image

Am i missing a place where it should be?

### CODE REVIEW

**Comment by Adri1** [comment]
Can you switch the French types_fr.png by this one? I forgot to translate one type and my correction on the original PR did not got the time to be considered

types_fr

**Comment by Adri1** [comment]
Some files in this PR have modifications that are supposed to come with new or updated locale files, it is possible to add them?

**Comment by CodeTappert** [comment]
> Some files in this PR have modifications that are supposed to come with new or updated locale files, it is possible to add them from the original PR?

What do you mean?

**Comment by Adri1** [comment]
For example in src/ui/summary-ui-handler.ts in line 691, it's supposed to get the translation of "Type"
image
And the fact it's missing can be seen in your own screenshot

**Comment by CodeTappert** [comment]
> For example in src/ui/summary-ui-handler.ts in line 691, it's supposed to get the translation of "Type" image And the fact it's missing can be seen in your own screenshot

I didnt mean to change this in this pr. So i reverted it.

The labels should be seperate. To not blow this up

**Comment by CodeTappert** [comment]
I still need to check (tommorow) if it is correctly shown in the attack overview screen (when you repalce an attack for example)

**Comment by CodeTappert** [comment]
image


It works without needing a change. 

So this is ready/can be reviewed/merged

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
