### PR TITLE
[QoL] Keyboard Shortcut to Toggle IVs during Starter Select 

### PR DESCRIPTION
**Pull request by frutescens**
## What are the changes?
The user can now use the Shift or C key to view a starter's IV without having to do so through the starter's menu options. The IV view automatically turns off after the cursor moves to a new Pokemon/generation/etc. 

## Why am I doing these changes?
Right now, players have to go to a starter's menu options and toggle a specific option to see their starter's IVs. Oftentimes, the IV view blocks the starter's moves and other details so the player has to go to the menu options again to turn off the IVs. I feel like this is a minor drag on the player's experience. By adding a shortcut to view a starter's IVs, players can enjoy the game experience more. In addition, because IVs are more accessible with this shortcut, limited space in the UI can be allocated for other things.

## What did change?
modified:   src/locales/en/starter-select-ui-handler.ts
modified:   src/ui-inputs.ts
modified:   src/ui/starter-select-ui-handler.ts

src/locales/en/starter-select-ui-handler.ts was modified to include the English text for the option. 
src/ui-inputs.ts and src/ui/starter-select-ui-handler.ts was modified to allow functionality with Buttons.STATS on Mode.Starter_Select

## How to test the changes?
I believe you can just run the application and test it as is. It does not have multi-language support though. 

## Checklist
- [ x] There is no overlap with another PR?
- [ x] The PR is self-contained and cannot be split into smaller PRs?
- [ x] Have I provided a clear explanation of the changes?
- [ x] Have I tested the changes (manually)?
    - [ x] Are all unit tests still passing? (`npm run test`)
- [ x] Are the changes visual?
  - [ x] Have I provided screenshots/videos of the changes?

Video Attached on Discord: https://discord.com/channels/1125469663833370665/1176874654015684739/1245614853876486185 
Apologies, video is too big for Github.

### CODE REVIEW

**Comment by flx-sta** [comment]
I think it should work with hold instead of toggle. Also it should work the other way around when IV is the default (toggled through the menu)

**Comment by frutescens** [comment]
Would love to work on this more! I'll just like some guidance on button placement for touchscreens, etc.

**Comment by flx-sta** [comment]
Any info why you closed it ? Something discussed on discord ?

**Comment by frutescens** [comment]
Oh, I need to re-create this - I made a mistake with my remote repository and decided to start my branches from scratch

**Pull request closed without merging**
