### PR TITLE
Allow to explicitly ignore faint phase when damaging

### PR DESCRIPTION
**Pull request by francktrouillez**
## Related issues
- https://github.com/pagefaultgames/pokerogue/issues/680
- https://github.com/pagefaultgames/pokerogue/issues/358

## Related PRs
- https://github.com/pagefaultgames/pokerogue/pull/783

## What are the changes?

This PR aims at fixing the order of messages when a pokemon faints because of a non-neutral effective physical/special move or because of a physical/special move that hit critically.

> [!NOTE]
> This **PR only aims at fixing the order of the messages**. The messages themselves are not changed (I know we are for instance missing the multi hit counter when the pokemon faints, etc.).

## Why am I doing these changes?
I am doing these changes because I want to get rid of this wrong order for the messages. That's not crucial to play, just been bugging me since I started playing the game.

## What did change?

Before, the messages were displayed in the following order:
- The pokemon faints
- The move is critical
- The move is effective

Now, the messages are displayed in the following order:
- The move is critical
- The move is effective
- The pokemon faints

### Videos
(I didn't make videos for all the cases, but I can if needed)

Before:
- With a super effective move that crits
  https://github.com/pagefaultgames/pokerogue/assets/57403591/00529147-f0df-41b4-bc24-a688d1e3e870

After:
- With a super effective move that crits
  https://github.com/pagefaultgames/pokerogue/assets/57403591/9c3a245a-5b10-4d9f-8cb0-ec74ceeb6229
- With a status effect
  https://github.com/pagefaultgames/pokerogue/assets/57403591/423222af-1e8c-48bc-8ad9-cc9060e76f64

## How to test the changes?
I've only tested the changes manually.

I've been using the [`src/overrides.ts`](https://github.com/pagefaultgames/pokerogue/blob/6952fe065b44c0c6371f0a575b8cf5fb8e97dbe3/src/overrides.ts) file to test the changes:

```typescript
/**
* SPECIES OVERRIDE
* will only apply to the first starter in your party or each enemy pokemon
* default is 0 to not override
* @example SPECIES_OVERRIDE = Species.BULBASAUR;
*/
export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.BULBASAUR;
export const ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const PASSIVE_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.FLOWER_TRICK, Moves.TOXIC, Moves.PROTECT]  ;
export const SHINY_OVERRIDE: boolean = false;
export const VARIANT_OVERRIDE: Variant = 0;

/**
* OPPONENT / ENEMY OVERRIDES
*/

export const OPP_SPECIES_OVERRIDE: Species | integer = Species.SQUIRTLE;
export const OPP_ABILITY_OVERRIDE: Abilities = Abilities.NONE;
export const OPP_PASSIVE_ABILITY_OVERRIDE = Abilities.NONE;
export const OPP_MOVESET_OVERRIDE: Array<Moves> = [];
export const OPP_SHINY_OVERRIDE: boolean = false;
export const OPP_VARIANT_OVERRIDE: Variant = 0;
```

I've tested the following cases:
- A pokemon faints because of a non-neutral effective physical/special move
- A pokemon faints because of a physical/special move that hit critically
- A pokemon faints because of a status effect
- A pokemon faints in a double battle because of a non-neutral effective physical/special move
- A pokemon faints in a double battle because of a physical/special move that hit critically
- A pokemon faints in a double battle because of a status effect

I believe that the changes should be isolated enough to ensure that nothing breaks and that this doesn't introduce any new bug. I'm open to any feedback on how to improve the testing process.

### CODE REVIEW

**Comment by bennybroseph** [comment]
How does this change differ/improve #783? I appreciate the time that this took as this explanation alone took a considerable amount of time, but overlapping work is something we'd like to avoid.

**Comment by francktrouillez** [comment]
@bennybroseph 
Thanks for the quick answer!

Compared to #783 , this PR doesn't aim at solving both the order of messages and the multi-hit issue when the pokemon faints.
**It only aims at solving the order of messages when a non-neutral effective physical/special move and/or critical hit make a pokemon faints**. I prefer to make smaller and self-contained PRs.
Because of that, I believe I can ensure the flow to remain the same for other sources of damages that can make the pokemon faints (such as status effect etc.)

Implementation-wise, this means I'm leaving untouched the flow for `Pokemon#damage` and `Pokemon#damageAndUpdate` when the source of damages is not coming from a physical/special move.

What do you think?

**Comment by bennybroseph** [comment]
> I prefer to make smaller and self-contained PRs.

I absolutely agree with this in general, but _especially_ due to the amount of PR that we get and the limited amount of people we have available to review/test them.

I'm going to give this a check when I get a chance and report back.

**Comment by bennybroseph** [comment]
Currently noticing a knock-on where Muti-Lens boosted items don't display the effectiveness text at all after fainting. Is this something that can be resolved?

**Comment by Greenlamp2** [comment]
Waw, if everyone could write their PR like yours, it would be easier for everyone !

@francktrouillez you can reproduce what @bennybroseph was saying with this overrides.ts:

```ts
export const STARTING_WAVE_OVERRIDE: integer = 101;
export const STARTING_LEVEL_OVERRIDE: integer = 50;

export const STARTER_SPECIES_OVERRIDE: Species | integer = Species.BULBASAUR;
export const MOVESET_OVERRIDE: Array<Moves> = [Moves.VINE_WHIP, Moves.TOXIC, Moves.PROTECT];

export const OPP_SPECIES_OVERRIDE: Species | integer = Species.SQUIRTLE;

export const STARTING_HELD_ITEMS_OVERRIDE: Array<ModifierOverride> = [{
    name: "MULTI_LENS",
    count: 5
}];
```

**Review by Greenlamp2 — APPROVED** [review]

**Pull request merged**
