### PR TITLE
[QoL] Improved Nature selection + Persistent selection of various values

### PR DESCRIPTION
**Pull request by prime-dialga**
## What are the changes?
The nature selection has been improved and various selectable values (nature, forms, shiny variants, abilities, gender) will be stored as preferences.

## Why am I doing these changes?
When having a large number of natures, it can be daunting to cycle through all of them.
And it is very easy to skip the desired nature which would force one to restart the whole process.

In addition, storing all those selectable values would make it easier to restart a failed run with the same pokemon without the need to reselect everything.

## What did change?
Natures have now a menu to select them from, with a sub menu for easy sorting.
Stats without any natures aren't shown in the menu.

All selections are stored locally in a new key in local storage on a per user basis.
Those selections aren't encrypted to allow for easier addon access, however the data is validated on read to ensure only selectable options are loaded.

Please note that the "cycling" button for the natures wasn't removed as:
- It is easier to cycle through 2-4 natures than it is to navigate the menu.
- Some users might be used to the old system and prefer it over the new addition.

manage-nature-1
manage-nature-3
manage-nature-4

## How to test the changes?
Most save files should have some nature variants, which would allow access to the menu. It will only appear if natures can be changed = more than 1 nature has been obtained for the pokemon.

However, as some of the forms and variants can be hard to obtain: here a savefile with forcefully unlocked values. (Warning: as normally unobtainable variants, abilities, genders and passives have been forcefully unlocked this can cause unexpected behaviours in certain instances; especially with any starter which has a pre-evolution)
[data_Guest.zip](https://github.com/user-attachments/files/15745573/data_Guest.zip)
- forms can be best tested with Unown
- gender with any starter
- abilities with lotad (3), any starter (2), and most of the newer legendaries e.g. Koraidon (1)
- shiny with Koraidon (as not all pokemon have 3 shiny variants implemented)
- nature with any pokemon

## Checklist
- [ ] There is no overlap with another PR?
    There is: #1400 as that PR also implemented persistance for natures and abilities
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Adri1** [comment]
I submitted a PR to your branch with some corrections to the French version

**Comment by Tempo-anon** [comment]
I really like the idea but I don't know if I'm a fan of the current menu structure that makes you select the +nature first. I think I'd prefer it if Manage nature just opened up a menu selection that was all the natures in it

**Comment by prime-dialga** [comment]
That was also my first approach, but then people suggested to split it into sub-menus as the list can get rather long...
manage-nature-2

I'll keep it with sub menus for now, until there are at least some more opinions; or it's worded stronger than just "I'd prefer".

**Comment by prime-dialga** [comment]
Submenus have been removed as requested.
The menu will now appear as shown in the image posted yesterday.

**Review by Tempo-anon — APPROVED** [review]

**Pull request merged**
