### PR TITLE
[Bug] blocking inputs while release pokemon

### PR DESCRIPTION
**Pull request by ysh4296**
## What are the changes?

- now inputs are blocked while showing text animation

## Why am I doing these changes?

#2201

- the problem was
    - Inputs are not blocked while the text animation ("Do you really want to release ${pokemon.name}?") is displayed.
    - unblocked input could change `this.cursor` and it potentially altering releasing pokemon
    - also it could release lead pokemon, it causing soft lock

## What did change?

add a private variable `blockInput` and used it for blocking inputs while text animation

## How to test the changes?

- manually

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [ ] Are the changes visual?
  - [ ] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Snailman11** [comment]
Does this fix (All Pokemon become invisible when capturing then switching with your only pokemon that was not fainted.)?
https://github.com/pagefaultgames/pokerogue/issues/762

**Comment by DayKev** [comment]
Seems to work.
I wonder if it shouldn't be possible to release Pokémon at all during a battle...

**Review by DayKev — APPROVED** [review]

**Comment by ysh4296** [comment]
Hello, I have checked the mentioned issues, Discord, etc.
Unfortunately, my PR does not resolve the mentioned issue.
My PR solves the game freezing (#2201)  issue that can occur when the lead Pokémon is released 
by fixing the UI cursor during the release action.

-----Original Message-----

**Comment by ysh4296** [comment]
@DayKev 
i agree it's reasonable to block to release pokemon at during battle since it has no gains.
but im not sure when is the appropriate timing for releasing pokemon.
so i make this pr just to  block game freeze issue

**Review by innerthunder — APPROVED** [review]

**Review by torranx — APPROVED** [review]

**Pull request merged**
