### PR TITLE
Magic coat and magic bounce.

### PR DESCRIPTION
**Pull request by Reldnahc**
I tested most moves unless they add identical attributes to another move. correctly targets both sides when the used move does.

### CODE REVIEW

**Comment by Reldnahc** [comment]
Relies on this PR for arena traps to properly work.

https://github.com/pagefaultgames/pokerogue/pull/447

**Comment by Reldnahc** [comment]
I think the latest commit does the detection of magic bounce more properly.

**Review by bennybroseph — CHANGES_REQUESTED** [review]
Needs TSDoc documentation on all new classes and functions and code comments where applicable.

**Comment by bennybroseph** [comment]
Closing this due to inactivity. Feel free to make a new request if interest is reignited

**Pull request closed without merging**
