### PR TITLE
Repel Implementation - Trainer battle chance

### PR DESCRIPTION
**Pull request by FedericoRossiIT**
Added repels for increased trainer battle chance

I had to delete the previous fork so also the previous pull request.
In the previous pull request I prevented double battles, now I changed the implementation thanks to a comment in the previous pull request saying something along the lines of 'Adding repels preventing double battle would be bloat (it will make lures and repels go in conflict)'.

ps. Still need these translations: de, es, fr, pt_BR, zh_CN

### CODE REVIEW

**Comment by LeCehlou** [comment]
French locale
 "TrainerBattleChanceBoosterModifierType": {
      description: "Double les chances de rencontrer un dresseur pendant {{battleCount}} combats",
    },

 "REPEL": { name: "Repousse" },
    "SUPER_REPEL": { name: "Super Repousse" },
    "MAX_REPEL": { name: "Repousse Max" },

**Comment by LeCehlou** [comment]
I'm not yet familiar with the pokerogue code, but I don't think you prevent the items to show in endless where there is non trainer battles.

**Comment by FedericoRossiIT** [comment]
I've added fr and de locales as given.

> I'm not yet familiar with the pokerogue code, but I don't think you prevent the items to show in endless where there is non trainer battles.

There was already a check that if in the game config the property `hasTrainers` is false it will give a wild encounter: `if (!this.gameMode.hasTrainers)`

**Comment by LeCehlou** [comment]
> I've added fr and de locales as given.
> 
> > I'm not yet familiar with the pokerogue code, but I don't think you prevent the items to show in endless where there is non trainer battles.
> 
> There was already a check that if in the game config the property `hasTrainers` is false it will give a wild encounter: `if (!this.gameMode.hasTrainers)`

Perfect !

**Comment by Tempo-anon** [comment]
Closing because of inactivity and merge conflicts and whether or not repels are needed

**Pull request closed without merging**
