### PR TITLE
Feature fullscreen mode

### PR DESCRIPTION
**Pull request by rationality6**
I want to create a fullscreen, but although the fullscreen works, it malfunctions afterward. I'm not familiar with this area, could you review and provide some guidance?

### CODE REVIEW

**Comment by rationality6** [comment]
Bottom right corner? Or outside of the Phaser canvas DOM?

**Comment by Flashfyre** [comment]
Well the canvas is meant to take up the entire screen in most cases, so it might be weird. Usually full screen is in the top right but that's in use by enemy items. Not sure where to put it that makes sense honestly. Could just make it a keybind but then it needs to be communicated.

**Comment by rationality6** [comment]
I think keybind is good

**Comment by Flashfyre** [comment]
F4 is often used for fullscreen as well. For the eventual mobile support we do still need a button though.

**Comment by rationality6** [comment]
I'll follow your direction

**Comment by Flashfyre** [comment]
I think it's unusual, yes. The button is almost always at the top right.

**Pull request closed without merging**
