### PR TITLE
Implements Synchronize

### PR DESCRIPTION
**Pull request by shayebeadling**
If another Pokemon burns, paralyzes, poisons, or badly poisons this Pokemon, that Pokemon receives the same non-volatile status condition.

This may require some extensive testing of edge-cases as there are quite a few niche ways to set status that may interact strangely with this.

### CODE REVIEW

**Review by bennybroseph — CHANGES_REQUESTED** [review]
Looking to get JSDoc documentation as shown here: [Code Comment FAQ](https://discord.com/channels/1125469663833370665/1239957703820836975)

**Comment by DustinLin** [comment]
Tested basic burn, paralyze, toxic, (no sleep, etc)

https://github.com/pagefaultgames/pokerogue/assets/39450497/27e97c57-1f2e-412b-a16f-a0c54b9e46ae

**Comment by DustinLin** [comment]
toxic spikes interaction works as intended (toxic spikes doesn't proc synchronize), static ability interaction works as intended, Lum berry interaction works as intended (synchronize procs before berry cure)

**Comment by flx-sta** [comment]
No action within more than a month. 
Considered stale.

Feel free to re-open it when you are still working on it/want to work on it again

**Pull request closed without merging**
