### PR TITLE
[Feature] Updated Champion teams

### PR DESCRIPTION
**Pull request by Tempo-anon**
## What are the changes?
* Updated champion teams.

## Why am I doing these changes?
* Experimenting with alternate forms of Pokemon on opponents
* Tweaking difficulty of champions
* Moving some legendary in champion teams so as to not clash with evil team legendary
* I tried to give each champion a gimmick Pokemon as well as a high BST legendary
* When possible, I tried to allow variety and rng for generating Pokemon in similar roles
* Keep each champion at only 5 Pokemon set in stone so the last Pokemon is random
* Tried to make each champion unique and not have too much overlap with other named trainers

### Red
* G-max Pikachu to keep his iconic Pikachu while giving it a stronger form
* Mega [Charizard, Venusaur, Blastoise] allows for some rng variety while keeping it thematic and giving Red some more power
* Snorlax is iconic and very powerful
* [Espeon, Umbreon, Sylveon] allows for more rng and type variety
* ~~[Ho-Oh, Lugia] there aren't really any high BST legends that are canonical to him but these are gen 2 legendary birds that debut'd in the same generation you would fight him~~ Lugia fits better on Red as he seems the more careful defensive type. There's also less type overlap since Blue will always have Alakazam
### Blue
* Mega Pigeot since Pigeot is his canon ace
*  [Gyarados, Arcanine, Exeggutor] allows for some type variety and was his original fire/water/grass core
* ~~[Ninetales, Magnezone, Cloyster] was his fire/electric/water core in yellow~~ [Rhyperior, Magnezone] are both Pokemon he has used and gives him some more type coverage and a more tanky Pokemon
* Alakazam is probably his strongest gen 1 pokemon
* ~~[Ho-Oh, Lugia] since Mewtwo fits more with Giovanni~~ By process of elimination he gets Ho-Oh which does seem to fit his reckless more aggressive nature
### Lance
* ~~Mega Aerodactyl to give him a mega~~ Aerodactyl I like the idea of only 1 mega on a team
* Dragonite since it's his signature
* Kingdra for some gen1-2 representation and he used it in LGPE
* Alola Exeggutor for gen 1 representation and he also used it in LGPE
* ~~Yveltal fits the most with him out of any other champion since he is a Flying type trainer :^)~~ [Mega Latios, Mega Latias] gives Lance a mega, legendary, and some team variety
### Steven
* Mega Metagross is his canon ace
* Skarmory part of his canon team
* Aggron also part of his canon team
* [Armaldo, Cradily] part of his canon team and has some variety
* Dialga fits his steel typing
### Wallace
* Mega Swampert since he uses a Swampert in BW2, it's gen 3 representation, and is the only water mega no other trainers use
* Milotic is his signature
* ~~Whiscash is part of his team~~ Replaced with Drizzle Pelipper to better showcase gen 3 and also give Wallace's team rain synergy
* Ludicolo also part of his team
* Palkia to contrast with Steven and also match his typing
### Cynthia
* Mega Garchomp is obviously her signature
* Spiritomb
* Lucario
* Togekiss are all really iconic Pokemon in her team. I removed Milotic to keep her team at the standard 5 count for champions
* Giratina is her signature in Pokemon Masters and does fit her thematically
### Alder
* Volcarona is his canon ace
* ~~[Bouffalant, Conkeldurr] both part of his team~~ [Bouffalant, Braviary] since Marshall already uses Conkeldurr
* [Accelgor, Escavalier] offers some variety
* ~~Genesect a strong bug type that makes up for Alder not having a gimmick~~ Keldeo After some discussion it was decided that Keldeo makes sense for Alder since it's located near his house and also improves his team for type coverage
* ~~[Reshiram, Zekrom] There's not that many high bst legends that would fit him. The two tao dragons are gen5 and have high BST~~ Zekrom because he already has a fire type
### Iris
* ~~Mega Aggron since nobody else is using it~~ Archeops since it's a native gen 5 mon that's unique and powerful while Steven already uses Aggron
* Haxorus is her signature
* Druddigon for gen 5 dragon representation
* ~~Lapras~~ Gmax Lapras for being quite memorable in her team and a more unique pokemon
* ~~[Reshiram, Zekrom] fitting for her type and generation~~ Reshiram by process of elimination
### Diantha
* Mega Gardevoir is her ace
* Hawlucha
* Gourgeist
* Goodra are all part of her in-game team
* Xerneas is a cover legendary and fits her theme
### Hau
* Alola Raichu is one of his signature Pokemon
* Noivern
* [Decidueye, Incineroar, Primarina] Starter
* [Tapu Koko, Tapu Bulu, Tapu Fini, Tapu Lele] he used a Tapu in one of the spin-offs and he also doesn't have a gimmick Pokemon
* [Solgaleo, Lunala] for cover legendary
### Leon
* G-max Charizard is his ace and represents G-max
* Dragapult
* Aegislash both strong Pokemon he used
* ~~[Rillabloom, Inteleon] a starter whose type does not overlap with Charizard~~ [Rillabloom, Inteleon, Cinderace] fine he can have all 3
* [Zacian, Zamazenta] cover legendary
### Geeta
* Glimmora <------ Guaranteed lead
* Kingambit her canon Pokemon
* [Espathra, Veluza] put these together since they're both psychic
* [Avalugg, HAvalugg] to allow for more variety
* Miraidon is quite strong and fits her aesthetic well
### Nemona
* Lycanroc
* Pawmot both Pokemon she always has
* ~~[Dusknoir, Milotic, Ribombee] one of her flex Pokemon~~ [Orthworm, Dudunsparce] are the other two Pokemon she uses in the base games. I felt these fit better since they're both from gen 9
* [Meowscarada, Skeledirge, Quaquaval] a starter
* Koraidon is strong and fits her aesthetic
### Kieran
* ~~G-max Grimmsnarl since he uses it and gives him a form change mon~~ After some discussion it was decided that instead of a mega/g-max Kieran should just have both legendaries
* ~~Porygon-z~~ [Grimmsnarl, Incineroar, Porygon-Z] are all different Pokemon Kieran uses
* ~~Politoed~~ [Politoed, Poliwrath] Kieran uses both and this allows for some more team variety
* Hydrapple is his other signature
* ~~[Ogerpon, Terapagos] ironic since he doesn't get either of them in-game but they are legendaries and are related to him~~ Ogerpon + Terapagos

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by jaimefd** [comment]
Would it be possible to give some champions mons some boss bars? It feels strange that your rival has them way earlier and you don't really get to fight any other trainers with boss pokemon. It would fit champions even more since round 190 is boss round after all, only multiple of 10 wave without boss pokemon

**Comment by Tempo-anon** [comment]
> Would it be possible to give some champions mons some boss bars? It feels strange that your rival has them way earlier and you don't really get to fight any other trainers with boss pokemon. It would fit champions even more since round 190 is boss round after all, only multiple of 10 wave without boss pokemon

Yep, definitely possible. Through hardcoding you can also set their abilities and even Pokeball types.

**Comment by Fontbane** [comment]
Some of this I mentioned on the Discord:

- Once GMax Pikachu gets buffed (unless it's been buffed already?) Red probably won't need a mega as well, in which case Lance could get Mega Charizard X like he had in LGPE.
- Not sure if it's a good idea for 2 champions to share a pair of legendaries. Makes them less distinct. Red could use Ho-Oh and Blue could use Lugia.
- Blue's Yellow core could cause some type overlap. Not sure how much of an issue that would be. Can also use Machamp, which he's had pretty consistently since HGSS.
- Yveltal fits Lysandre much more than Lance imo, down to the fluffy thing on its neck. Lance can get Zygarde instead since it matches his (in-lore) dragon type specialty.
- Give Alder Braviary over Conkeldurr. It fits him, and Conkeldurr would also overlap with Marshal. Alder's team in PWT is Volc, Braviary and 4 mons representing the E4, so it seems Braviary is somewhat important to him. Or just keep both tbh.
- Alder could have Reshiram and Iris could have Zekrom, since Iris is originally fought in White.
- Leon should be able to have Cinderace like the other two starters. It's odd to exclude it.
- I'd suggest looking at some of Kieran's Teal Mask mons (no, I don't mean Furret), since they're more singles oriented. He could use more of his Blueberry mons in the eventual Doubles Classic mode. I suggest having a [] slot with some of them at least. Also, you could forego gmax Grimmsnarl and instead just give him Ogerpon in addition to Terapagos as it's a sub legendary.

**Comment by CodeTappert** [comment]
My Idea:
Red: Nothing to add
Blue: Why not [Vaporeon,Jolteon,Flareon] since he had this in Pokémon Yellow.
Still Blue: Maybe give him [Arcticuno, Zapdos, Moltres] so he doesnt overlap with Red?
Lance: Nothing to add
Steven: I would really rather see him have Groudon then Dialga to keep it Hoenn themend. But yeah i think type themend makes more sense
Wallace: Rather Kyogre over Palkia but well. Fits better to Stevens Dialga that is true.
Cynthia: Milotic is kind of iconic for her too. Honestly vibe wise i would rather remove Girantina but keep Milotic. But probably that doenst make sense balance wise.
Alder: Give him Zekrom. No Chance for Reshiram (prevent overlap with iris)
Iris: Give her Reshiram. No Chance for Zekrom (prevent overlap with alder)
Diantha: Nothing to add
Hau: Nothing to add
Leon: Can he have also the fire evo in the game? I mean sure would be an overlap but still...
Geeta: Nothing to add
Nemona: Nothing to add
Kieran: Probably would swap Grimmsnarl out and give him both ogerperon and terapagos instead.

**Comment by CodeTappert** [comment]
> > Would it be possible to give some champions mons some boss bars? It feels strange that your rival has them way earlier and you don't really get to fight any other trainers with boss pokemon. It would fit champions even more since round 190 is boss round after all, only multiple of 10 wave without boss pokemon
> 
> Yep, definitely possible. Through hardcoding you can also set their abilities and even Pokeball types.

Please no. This is just a annoying mechanic in trainer battles (in my opinion). Rather make them have stronger pokemon

**Comment by Tempo-anon** [comment]
You guys are cooking! I've heard your feedback. I like the idea of splitting the legendaries. 

## Red/Blue
* Red/Blue should probably get different GS birds, not sure who gets which though since both of them have potential for type overlaps (fire and psychic) on both of their teams.
* I also considered Machamp, a gen 1 Eevee core, and the gen 1 elemental birds core for Blue but the problem is that his team really is quite tight and has the potential for a lot of overlap
## Lance
* I can see both Zygarde and Yveltal for him. The main reason I chose Yveltal for now was I thought it'd make more sense if I split up the paired cover legendaries among the champions. I definitely do see Yveltal fitting aesthetically more with Lysandre though (and it is the other Pokemon he uses in Masters)
## Alder/Iris
* Conkeldurr is quite a common pokemon. I can change that slot to be [Bouffalant, Braviary]
* I like the idea of giving them each a different tao dragon. Alder with Zekrom has more type variety since he already has a fire signature, but it seems Iris is originally white exclusive?
## Leon
* Okay fine he can have Cinderace
## Kieran
* Seems like a common thread to suggest removing g-max snarl and giving him both Terapagos and Ogerpon. That could work
* Terapagos, Ogerpon, Hydrapple seem to be locked in so then he has 2 flex spots
* His other used Pokemon include Shiftry, Yanmega, Probopass, Poliwrath, Poliwhirl, Gliscor, Dragonite, Grimmsnarl, Porygon-Z, and Incineroar. Out of these I can see Poliwrath and Poliwhirl probably being able to share the same role. I guess the other two slots can be [Poliwrath, Poliwhirl] and then some combination of [Shiftry, Yanmega, Probopass, Gliscor, Dragonite, Grimmsnarl, Porygon-Z]

**Comment by CodeTappert** [comment]
> You guys are cooking! I've heard your feedback. I like the idea of splitting the legendaries. 
> 
> ## Red/Blue
> * Red/Blue should probably get different GS birds, not sure who gets which though since both of them have potential for type overlaps (fire and psychic) on both of their teams.
> * I also considered Machamp, a gen 1 Eevee core, and the gen 1 elemental birds core for Blue but the problem is that his team really is quite tight and has the potential for a lot of overlap
> ## Lance
> * I can see both Zygarde and Yveltal for him. The main reason I chose Yveltal for now was I thought it'd make more sense if I split up the paired cover legendaries among the champions. I definitely do see Yveltal fitting aesthetically more with Lysandre though (and it is the other Pokemon he uses in Masters)
> ## Alder/Iris
> * Conkeldurr is quite a common pokemon. I can change that slot to be [Bouffalant, Braviary]
> * I like the idea of giving them each a different tao dragon. Alder with Zekrom has more type variety since he already has a fire signature, but it seems Iris is originally white exclusive?
> ## Leon
> * Okay fine he can have Cinderace
> ## Kieran
> * Seems like a common thread to suggest removing g-max snarl and giving him both Terapagos and Ogerpon. That could work
> * Terapagos, Ogerpon, Hydrapple seem to be locked in so then he has 2 flex spots
> * His other used Pokemon include Shiftry, Yanmega, Probopass, Poliwrath, Poliwhirl, Gliscor, Dragonite, Grimmsnarl, Porygon-Z, and Incineroar. Out of these I can see Poliwrath and Poliwhirl probably being able to share the same role. I guess the other two slots can be [Poliwrath, Poliwhirl] and then some combination of [Shiftry, Yanmega, Probopass, Gliscor, Dragonite, Grimmsnarl, Porygon-Z]

Red: Ho-Oh (he is kinda Ash and Ash saw Ho-Oh in the First anime episode)
Blue: Lugia.

**Comment by RNGezeus** [comment]
I'll apologize in advance for the text dump. The moment I read Lance as flying brain started cooking too hard.

- **Red**

I'm in general against going outside generations they appeared so I'm not feeling the Sylveon but it does provide difference , introduce fairy into earlier gens and has good connection.

On the legendary I wonder I see 2 main options, first is Ho-oh given the anime connection was was mentioned before, The other is Mewtwo for a couple of reasons, 1st: Just for Gen 1 legendary represenation. We could use the 3 birds or Mewtwo somewhere here.
2nd: If we were to use connections beyond the games then I'd refer to  the pokemon Adventures Manga where Mewtwo seeks out red to team up.
3rd: There was nothing stronger than Mewtwo at gen 1, it fits the theme of what may be one of the most legendary champions.


- **Blue**

On the basic mon side, no comment. It's great.

On the legendary this is really hard. I can't see close relation to anything here. Give 2 out of 3 legendary birds? Birds can also belong with Red now that i'm on this track. But it this connection is only by vague manga relation and being of same gen.

- **Lance**

There is another option for Mega Aero which he did use later in the games, Mega charizard X.  Its also a pokemon he used as early as gen 2 so early part of his team and an iconic "dragon" of early gen.

Let me start by apologizing for the ranty nature of what's coming up.
Yveltal, I'm really not a fan due to 2 aspects, 
1st: Lance has nothing to do with XY at all in any way so
2nd: This line "since he is a Flying type trainer", which given that emoji may be a small joke which is accurate in gen one given few overlap with flying and lack of dragons in general. But Lance has always been known as a dragon user and the moment they added more of them to the franchise his team really started to show it. Flying was accidently part of his shtick, but thats not the focus here. If he is to have Yveltal then I want it hardcoded to be Tera Dragon.

- **Steven**

Yeah, not too much to say here. This is peak Steven, the stone man. My only gripe is one similar lance in that I don't see a connection to the mon itself, but here at least it does share typing since Steven is a soft steel user.

There is a legendary I can see fitting with both generation, connection and typing, Jirachi: the wishmaker sleeing in a ancient crystal cocoon. The problems with that one though is the lower stats (can be solved with vitamins to convert to legendary BST) and the identical typing to Metagross.

- **Wallace**

Wallace team is obvious rain team, the fact he's not using a drizzle setup is a travesty, obvious choice being Kyogre even if it now would break duo with Steven. But if so then I would rather force ground onto Steven (though that increases his weakness to fire)

- **Cynthia**

Cynthia is Fantastic as is and all my opinions on her are increidble minor. If we had to change something than maybe she could rotate any of the Legendary dragons of gen 4, but this is only meant for variety and inclusion. Her theming and connection with Giratina is fantastic.

I do very slightly wanna swap Lucario for Milotic but that's because there are so many associations I do with Lucario and Milotic reminds me more of the Cynthia experience. Bulky mons you don't get rid of which are made even scarier with rogue sitrus berries. With this said it would make her share a mon with Wallace, and if just one of them have then he is a better candidate.

- **Alder**

Can't really make a comment on alder. Maybe I lean a bit more on him having Zekrom for coverage,or Reshiram for the theme, but its really a tossup in my book. 

An alternate option is to go similar to blue, give him 2/3 of the Forces of nature trio, Or just guarantee Therian landorus and random one of the other ones.

- **Iris**

Mega Aggron - Honestly i feel she could actually make better use of Tera Steel/Rock/Ground aggron instead of mega so it gets reduced weaknesses. maybe both. Aggron is only threatening if you lack in quad attacks (ground/fightning) or special attacks. Both methods are very easy to achieve. Also she wasn't that involved with megas (though neither is she with Tera)
Druddigon - I 'disagree with his inclusion but with the reasoning, its not for dragon representation. He is just there to be canon to the team. The sad part with druddigon is that he isn't really a threat, a remainder of her days as a meager gym leader. Not really champion material.
Reshi/Zek - Similar to Alder, not that much of an opinion. But if he does get a determined one then she should obviously get the other one

- **Diantha**

Looking pretty solid. My primary issue with her currently is the lack of a Mega which was the entire gimmick. A bit sad she lacks any variety if we run her as canon

- **Hau**

I like it, lots of variety here. The Tapu stats and terrain power boose makes up for him not having a mega/giga gimmick 

- **Leon**

One of the reasons Aegislash is scary is the predict game with kings shield which I'm not sure how well game handles. That said if you do swap to type advantage he will revert to shield form if he swaps, so its maybe less of an issue than I'm imagining.

- **Geeta**

Glimmora - This needs to be her lead. She wastes the entire ability in base games by using it as final ace.
Espathra, Veluza - How about punish setup teams, Opportunist Espathra. If we feel like being mean here we only make Espathra availible.

- **Nemona**

Looking good. No comment
  
- **Kieran**

I got no experience with this team, never looked at SV dlc.

**Comment by Tempo-anon** [comment]
After some discussions with others I've made some changes
* Red now gets Lugia
* Blue now gets Ho-oh and instead of using his yellow core he now chooses between Rhyperior and Magnezone
* Alder now gets Zekrom and swaps Genesect for Keldeo and Conkeldurr for Braviary
* Iris now gets Reshiram
* Leon can choose Cinderace
* Changed Nemona's flex spot of [Dusknoir, Milotic, Ribombee] to [Orthworm, Dudunsparce]
* Removed Kieran's G-max Grimmsnarl and gave him both Terapagos and Ogerpon. Has a chance to use Poliwrath instead of Poliwhirl. Instead of Porygon-z he can also use Grimmsnarl or Incineroar

**Comment by Fontbane** [comment]
> After some discussions with others I've made some changes
> 
> * Red now gets Lugia
> * Blue now gets Ho-oh and instead of using his yellow core he now chooses between Rhyperior and Magnezone
> * Alder now gets Zekrom and swaps Genesect for Keldeo and Conkeldurr for Braviary
> * Iris now gets Reshiram
> * Leon can choose Cinderace
> * Changed Nemona's flex spot of [Dusknoir, Milotic, Ribombee] to [Orthworm, Dudunsparce]
> * Removed Kieran's G-max Grimmsnarl and gave him both Terapagos and Ogerpon. Has a chance to use Poliwrath instead of Poliwhirl. Instead of Porygon-z he can also use Grimmsnarl or Incineroar

No Machamp on Blue? It has much more of a presence on his teams than Mag

**Comment by Tempo-anon** [comment]
> There is another option for Mega Aero which he did use later in the games, Mega charizard X. Its also a pokemon he used as early as gen 2 so early part of his team and an iconic "dragon" of early gen.

Mega zard X would be a good choice but I'm a bit iffy because Charizard already shows up in Leon's team and also has a chance to show up for Red. Also due to the way formIndexs are made right now, Red will always use X-zard.

> Let me start by apologizing for the ranty nature of what's coming up.
Yveltal, I'm really not a fan due to 2 aspects,
1st: Lance has nothing to do with XY at all in any way so
2nd: This line "since he is a Flying type trainer", which given that emoji may be a small joke which is accurate in gen one given few overlap with flying and lack of dragons in general. But Lance has always been known as a dragon user and the moment they added more of them to the franchise his team really started to show it. Flying was accidently part of his shtick, but thats not the focus here. If he is to have Yveltal then I want it hardcoded to be Tera Dragon.
Lance's legendary being Yveltal is definitely the biggest point of contention. Lance didn't have a type in common in gen 1 but his gen 2 team was indeed all flying type so it's a little nod to that. Yveltal's placement has always been sort of odd since in the game right now Yveltal is on Iris's team. I don't quite agree with Lance having Zygarde mainly because its power level is way higher than most of the other legendaries. If we actually look at legendary dragons that are unclaimed at this point the only ones left are Regidrago, Necrozma-Ultra, and the Lati@s twins, none of which really fit the role of the 600+ strong Pokemon to match the others.

> No Machamp on Blue? It has much more of a presence on his teams than Mag
Discussed offline but the main reason I decided against it is that Blue is set to spawn with the Kanto E4 which means players will have already seen a Machamp on Bruno already

**Comment by Xavion3** [comment]
Yveltal on Lance still feels weird, and I feel like the evil teams are warping design maybe a bit too much but whatever.

Maybe one of the paradox dogs for Lance? They're only 590 BST, but they're all quite capable legendaries in their own right, feel closer to his original generation, and are all dragon types.

**Comment by Tempo-anon** [comment]
> Yveltal on Lance still feels weird, and I feel like the evil teams are warping design maybe a bit too much but whatever.

This might be a fair concern. Mewtwo just feels like it makes sense on Giovanni over Blue and Kyogre/Groudon makes sense on Archie/Maxie. There can be an argument made for Wallace having Kyogre but the gen 4 cover legends (that Steven currently uses) splits very nicely with Wallace in terms of typing. If anything though, Yveltal on Lance at least makes more sense than having it on Iris now

> Maybe one of the paradox beasts for Lance? They're only 590 BST, but they're all quite capable legendaries in their own right, feel closer to his original generation, and are all dragon types.

The fact that evil boss rematches used paradox Pokemon seemed a little controversial to some players and was even suggested as a reason for keeping them locked out of either the first loop or behind a challenge modifier. Paradox Pokemon for the most part seem to be like a genuine plot twist to players so I'm hesitant on giving it just to champion Lance. The issue is that if we're aiming for a 600+ dragon for Lance the only options are Reshiram, Zekrom, Kyurem, Zygarde, and Necrozma, but the last two are much higher in power level and it seems that players like the idea of each champion having their own legendary (hence why Red/Blue will always have a specific legendary bird)

**Comment by Tempo-anon** [comment]
* Updated Lance to use Mega Latias or Mega Latios instead of Mega Aerodactyl and Yveltal. 
* Updated Geeta to always lead with Glimmora

**Comment by CodeTappert** [comment]
Leads:

Red: Pikachu (like hgss)
Blue: Arcanine/whatever is in the slot (dont value my opinion on this. This is just my favorite pokemon)
Lance: Dragonite (his signature)
Steven: Skarmory (to potentially set up hazards)
Wallace: Something with drizzle or rain dance
Cynthia: Sprittomb (she does in every Game)
Alder: No opinion
Iris: Haxorus
Diantha: No opinion 
Hau: The Starter slot
Leon: Aegislah
Geeta: Kinggambit
Nemona: Pawmot
Kieran: Politoad/Poliwrath

For most of them i went with what "feels" right.

**Comment by Tempo-anon** [comment]
## Team changes
* Wallace: Whiscash -> Pelipper for drizzle synergy and Mega Swampert already is a water/ground
* Iris: Aggron -> Archeops since Steven also uses Aggron while Archeops is a unique strong Pokemon native to gen 5 and used in her canon battle. Her Lapras is now gmax

## Champion leads
Champions now have dedicated Pokemon they lead with instead of using the guaranteed random flex spot
Red: Pikachu 
Blue: Alakazam 
Lance: Aerodactyl
Steven: Skarmory
Wallace: Pelipper
Cynthia: Spiritomb
Alder: Bouffalant/Braviary
Iris: Druddigon
Diantha: Gourgeist
Hau: Alola Raichu
Leon: Rillaboom/Cinderace/Inteleon
Geeta: Glimmora
Nemona: Lycanroc
Kieran: Poliwrath/Politoed

**Review by brain-frog — APPROVED** [review]

**Pull request merged**
