### PR TITLE
impl Priority immunity abilities

### PR DESCRIPTION
**Pull request by LaukkaE**
Re-pr with  Quick feet changes removed as it was implemented already.

### CODE REVIEW

**Comment by Flashfyre** [comment]
Resolve conflicts

**Review by Flashfyre — CHANGES_REQUESTED** [review]
The wording on these implies some are for attack moves and some are for all moves. Are you properly making this distinction?

**Comment by Flashfyre** [comment]
So none of these are actually limited to only attack moves?

**Comment by LaukkaE** [comment]
> So none of these are actually limited to only attack moves?
No, if the move is targeted against the pokemon.
If prankster pokemon uses thunder-wave, it gets blocked, but if it uses recover it doesn't get blocked.

**Review by Flashfyre — APPROVED** [review]

**Pull request merged**
