### PR TITLE
[Bug] Add Giga Impact Opp BG img

### PR DESCRIPTION
**Pull request by geefuoco**
## What are the changes?

Giga impact now works when an opponent pokemon uses it
## Why am I doing these changes?

Fixing a bug #1572 
## What did change?

Added the background image for giga impact opp
### Screenshots/Videos

https://github.com/pagefaultgames/pokerogue/assets/87877876/9b98d513-4f82-4708-bd16-c2f8b921af31

## How to test the changes?

Add Giga Impact as the only available move on opponent pokemon in overrides
## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Tempo-anon** [comment]
Where'd you get that bg image from?

**Comment by bennybroseph** [comment]
looks off-center to me. please adjust it

**Review by bennybroseph — CHANGES_REQUESTED** [review]
looks off-center to me. please adjust it

image

**Comment by geefuoco** [comment]
> looks off-center to me. please adjust it
> 
> image


https://github.com/pagefaultgames/pokerogue/assets/87877876/54a42aa9-adb6-44aa-a68f-64684761890f

**Comment by Tempo-anon** [comment]
Looks better on single target but how does it look in double battles? 🤔

**Review by Tempo-anon — APPROVED** [review]
I agree. I'm personally of the opinion that this is a hotfix as it fixes a gamebreaking crash. If anyone wants to improve the background so it looks nicer they can do so later.

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
