### PR TITLE
[P3] Fix "falsex" type hint for Sheer Cold

### PR DESCRIPTION
**Pull request by innerthunder**
## What are the changes the user will see?
Sheer Cold will no longer show a type hint of "falsex" against Ice-type Pokemon

## Why am I making these changes?
Sheer Cold's code is old as hell but somehow worked with the new type effectiveness code, so I missed it earlier.

## What are the changes from a developer perspective?
`data/move`: Sheer Cold's `IceNoEffectTypeAttr` no longer interprets the type effectiveness multiplier as a boolean, and now sets the type multiplier to 0 instead of `false`.

### Screenshots/Videos

image

## How to test the changes?
1. Use `src/overrides.ts` to give your Pokemon Sheer Cold and set the enemy species to an Ice-type.
2. Start a new game
3. Enable type hints
4. Sheer Cold's type hint should show as "0x" instead of "falsex"

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I considered writing automated tests for the issue?
- [x] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by torranx — APPROVED** [review]
lol how was this not broken

**Review by Tempo-anon — COMMENTED** [review]
What happens when you use sheer cold on an ice type? Does it do 0 damage or does it fail? 

Screencapped off showdown for what happens when you sheer cold an ice type
image

**Review by DayKev — APPROVED** [review]

**Comment by DayKev** [comment]
> What happens when you use sheer cold on an ice type? Does it do 0 damage or does it fail?

It fails, which is handled in Move Phase iirc.

**Comment by innerthunder** [comment]
> What happens when you use sheer cold on an ice type? Does it do 0 damage or does it fail?

Works as expected (ignore the missing Splash anim, that's an unrelated bug with overrides).

https://github.com/user-attachments/assets/372cc3e3-7454-46ca-87da-5621b5ccbe8e

**Pull request merged**
