### PR TITLE
[Bugfix] Fix Curse Message not beeing properly shown when casted by a ghost pokemon

### PR DESCRIPTION
**Pull request by CodeTappert**
## What are the changes the user will see?

They will see the correct curse message and not cursedOnAdd

## Why am I making these changes?

Because someone did it wrong/broke it

## What are the changes from a developer perspective?

I changed the key that is called back

### Screenshots/Videos

Before:

https://github.com/user-attachments/assets/79d5ba69-5231-411c-94c5-f1cab6ad905b

After: 

https://github.com/user-attachments/assets/18fea49b-6b5e-4b20-9a46-ea8a579827fb

## How to test the changes?

Have a ghost pokemon use curse

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I add placeholders for them in locales?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Review by torranx — APPROVED** [review]

**Comment by Snailman11** [comment]
Link to Discord
https://discord.com/channels/1125469663833370665/1274429074558685265

**Comment by f-fsantos** [comment]
Please double check git blame on this and make sure nothing else got broken on the same PR that did this @CodeTappert

**Comment by CodeTappert** [comment]
The PR is https://github.com/pagefaultgames/pokerogue/pull/3498/files

They are all at least in the english file

**Comment by EnochG1** [comment]
#3498 was my work and I made PR https://github.com/pagefaultgames/pokerogue/pull/3631
I thought it should target at main.

@f-fsantos I checked it and found that most of the changes were to battler-tags.ts and I missed move.ts because there was only one change to make.

**Comment by f-fsantos** [comment]
Closed by #3631

**Pull request closed without merging**
