### PR TITLE
Show type of Hidden Power or other variable type moves in battle and summary

### PR DESCRIPTION
**Pull request by jaimefd**
This change makes it so that you can see the type of your Hidden Power, or any other move that can have its type changed (like Revelation Dance, Weather Ball, etc...). It even shows type changes from abilities such as Pixilate or Liquid Voice, as it does the same checks that are done in battle in the same order.

Here's some proof:

https://github.com/pagefaultgames/pokerogue/assets/22176793/823eba04-8334-4436-a051-7e2e9a1ac4ef

It also works with stuff like setting Sunny Day, it updates dynamically, first turn shows Normal then shows Fire next turn:

https://github.com/pagefaultgames/pokerogue/assets/22176793/951f2fe9-9e50-40a7-9d6e-5b017523c703

EDIT: This also fixes abilities that change move immunities/resistances, such as Flash Fire no longer being immune to Liquid Voice+Torch Song, or Tinted Lens actually doubling resisted Hidden Power in damage.

### CODE REVIEW

**Comment by jaimefd** [comment]
Fixed the indenting issues with ESLint.

**Comment by jaimefd** [comment]
> Looks cool but doesn't this exacerbate the issue where type immunities are checked before type changing? (ie liquid voice torch song does not affect flash fire)

That is, indeed, a problem I was not aware of. I guess I'll try to fix that too when I have some time

**Comment by jaimefd** [comment]
> Looks cool but doesn't this exacerbate the issue where type immunities are checked before type changing? (ie liquid voice torch song does not affect flash fire)

Thanks to the new function that checks the new move type, I managed to fix that:
https://github.com/pagefaultgames/pokerogue/assets/22176793/679a7b49-a5cd-44cf-9425-f3f5bfb104e0

Also idk what's wrong with ESLint again, "npm run eslint" isn't even fixing anything else anymore

**Comment by jaimefd** [comment]
Style issues are fixed now

**Comment by jaimefd** [comment]
Rebased to the new main so that I no longer need to change styling in battle-info.ts

**Comment by Tempo-anon** [comment]
Seems like you have some conflicts now. This change should be merged as soon as https://github.com/pagefaultgames/pokerogue/pull/1440 gets merged in though

**Comment by Tempo-anon** [comment]
@jaimefd do you mind fixing merge conflicts? Just today someone reported hidden power type hinting as a bug report

**Comment by flx-sta** [comment]
@Tempo-anon should someone mirror the PR?

**Comment by flx-sta** [comment]
Mirrors and closed
#3417

**Pull request closed without merging**
