### PR TITLE
[Qol?] Added a double dot at the end of every settings label (if it doenst a…

### PR DESCRIPTION
**Pull request by CodeTappert**
…lready have one)

## What are the changes?

The Settings label has a : at the end

## Why am I doing these changes?

Looks nicer imo

## What did change?

See screenshots

### Screenshots/Videos

Before:
image
After: 
image

## How to test the changes?

Open settings in any language

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by CodeTappert** [comment]
Please @brain-frog look at this. Walker said he would send it to you for review anyways

**Comment by hayuna** [comment]
"double dot at the end". I tried to find .. at the end of any word 

its calling "semicolon" 😜

**Comment by CodeTappert** [comment]
> "double dot at the end". I tried to find .. at the end of any word
> 
> its calling "semicolon" 😜

a semicolon is ";" not ":"

**Comment by hayuna** [comment]
"colon" *

**Comment by CodeTappert** [comment]
Consensus is this should be per language. So i close it

**Pull request closed without merging**
