### PR TITLE
[Localization] add remaining Italian localization for trainers

### PR DESCRIPTION
**Pull request by SavGRY**
## What are the changes?
Added localization in the `trainers.ts` file for the remaining names that were not being translated

## Why am I doing these changes?
There were no it translation

### Screenshots/Videos
image  
image

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [ ] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by SavGRY** [comment]
I ran `npm run test`. Some tests regarding the inputs are not passing anymore. I don't think that's related to my PR, so maybe it's relevant to open an issue?

**Comment by CodeTappert** [comment]
Please fix your conflicts

**Comment by CodeTappert** [comment]
I think you just did it A LOT worse

**Comment by SavGRY** [comment]
> I think you just did it A LOT worse

Yep, Also, someone already added this translations, so it's better to close this PR. The changes are already on main, made by another user, so just close this.

**Pull request closed without merging**
