### PR TITLE
[Balance] Remove Dragon Ascent Requirement for Mega Rayquaza

### PR DESCRIPTION
**Pull request by Blitz425**
## What are the changes the user will see?
Rayquaza no longer requires Dragon Ascent to Mega Evolve

## Why am I making these changes?
Normally in mainline Pokemon, Rayquaza does not have a mega stone and instead Mega Evolves through knowing the move Dragon Ascent. However in Pokerogue we do have a Rayquazite, but Rayquaza is still forced to know Dragon Ascent to keep the form change despite requiring two rogue tier items. This limits playstyles and options especially in PokeRogue, as the restriction in mainline is mainly due to Rayquaza being allowed an item slot while the other Megas / Primals are forced into holding their respective stones. That restriction is completely nonexistent in PokeRogue however, since Megas / Primals can hold items other than their Mega Stone here. This was also a requested change in the balance feedback threads. 

## What are the changes from a developer perspective?
Change Rayquaza's Mega Requirements to that of other Mega Evolutions.

### Screenshots/Videos
Rayquaza with no moves
image

Rayquaza Mega Evolving
image

## How to test the changes?
Overrides

## Checklist
- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [ ] Have I considered writing automated tests for the issue?
- [ ] If I have text, did I make it translatable and add a key in the English locale file(s)?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by CodeTappert** [comment]
While i dont agree from a "i want to stay as close to the games"-perspective i agree from a balance one. So i will approve

**Review by CodeTappert — APPROVED** [review]

**Review by flx-sta — APPROVED** [review]
Guess this was previously discussed on discord. Fine with me

**Review by innerthunder — APPROVED** [review]
I've seen too many bug reports on "Why isn't my Rayquaza Mega-Evolved?" for this not to go in ogreSmile

**Comment by damocleas** [comment]
yep

**Pull request merged**
