### PR TITLE
Implement Parental Bond

### PR DESCRIPTION
**Pull request by jaimefd**
Implemented the ability Parental Bond, with a new ExtraHitMoveAbAttr that takes two values, the amount of extra hits and the damage modifier for them (in this case 1 and 0.25).

From my testing it seems to work like original Pokemon, with the exception that I intentionally allowed it to activate with Multi-Hit moves, so that it doesn't become redundant with Multi Lens and so that Maushold makes sense with Parental Bond as passive (otherwise it would be a useless passive). This can be changed easily if needed.

Tested that non-attacking moves don't activate it, misses also stop the second hit, and it procs secondary effects as expected.

### CODE REVIEW

**Comment by bennybroseph** [comment]
How does this look/feel visually with long animations? Can we get a video with an example?

**Review by TempsRay — COMMENTED** [review]
Does this deal with all the edge cases listed on [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Parental_Bond_(Ability))? 
> If a move could hit multiple targets (including allies), such as [Earthquake](https://bulbapedia.bulbagarden.net/wiki/Earthquake_(move)) and [Rock Slide](https://bulbapedia.bulbagarden.net/wiki/Rock_Slide_(move)), it will not strike twice; however, if it can only hit a single Pokémon, such as in a Single Battle or if using a move that can hit multiple targets when only one target is in range, it will strike twice. If a move could hit multiple Pokémon but only hits one due to missing the other Pokémon, it will only strike once.

> If [Present](https://bulbapedia.bulbagarden.net/wiki/Present_(move)) heals the target it will only strike once, but if it damages the target it will strike twice (the second strike will always damage the target). [Fixed-damage moves](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_that_deal_direct_damage) (such as [Seismic Toss](https://bulbapedia.bulbagarden.net/wiki/Seismic_Toss_(move)) and [Dragon Rage](https://bulbapedia.bulbagarden.net/wiki/Dragon_Rage_(move))) deal the full amount of damage for both strikes. The damage dealt by [Psywave](https://bulbapedia.bulbagarden.net/wiki/Psywave_(move)) is generated separately for each strike, and the second strike's damage is not halved. Each strike of [Super Fang](https://bulbapedia.bulbagarden.net/wiki/Super_Fang_(move)) halves the target's HP (effectively quartering it if HP is not changed between strikes). [Counter](https://bulbapedia.bulbagarden.net/wiki/Counter_(move)), [Mirror Coat](https://bulbapedia.bulbagarden.net/wiki/Mirror_Coat_(move)), [Metal Burst](https://bulbapedia.bulbagarden.net/wiki/Metal_Burst_(move)), and [Bide](https://bulbapedia.bulbagarden.net/wiki/Bide_(move)) deal the full amount of damage for both strikes. The first strike of [Assurance](https://bulbapedia.bulbagarden.net/wiki/Assurance_(move)) counts as previously taking damage for the second strike, giving it increased power. [Fury Cutter](https://bulbapedia.bulbagarden.net/wiki/Fury_Cutter_(move)) and [Echoed Voice](https://bulbapedia.bulbagarden.net/wiki/Echoed_Voice_(move)) only consider uses of the move rather than hits, so the second strike's power is not boosted by the first strike. [Grass Pledge](https://bulbapedia.bulbagarden.net/wiki/Grass_Pledge_(move)), [Fire Pledge](https://bulbapedia.bulbagarden.net/wiki/Fire_Pledge_(move)), and [Water Pledge](https://bulbapedia.bulbagarden.net/wiki/Water_Pledge_(move)) strike twice, even when used as a combination move. [Natural Gift](https://bulbapedia.bulbagarden.net/wiki/Natural_Gift_(move)) and [Spit Up](https://bulbapedia.bulbagarden.net/wiki/Spit_Up_(move)) strike twice. [Moves that require recharging](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_that_require_recharging) after use strike twice, but the user only needs to [recharge](https://bulbapedia.bulbagarden.net/wiki/Recharge) for one turn.

> [One-hit knockout moves](https://bulbapedia.bulbagarden.net/wiki/One-hit_knockout_move), [Fling](https://bulbapedia.bulbagarden.net/wiki/Fling_(move)), [Self-Destruct](https://bulbapedia.bulbagarden.net/wiki/Self-Destruct_(move)), [Explosion](https://bulbapedia.bulbagarden.net/wiki/Explosion_(move)), [Final Gambit](https://bulbapedia.bulbagarden.net/wiki/Final_Gambit_(move)), [Uproar](https://bulbapedia.bulbagarden.net/wiki/Uproar_(move)), [Rollout](https://bulbapedia.bulbagarden.net/wiki/Rollout_(move)), and [Ice Ball](https://bulbapedia.bulbagarden.net/wiki/Ice_Ball_(move)) only strike once. (Other [consecutively executed moves](https://bulbapedia.bulbagarden.net/wiki/Category:Consecutively_executed_moves), such as [Outrage](https://bulbapedia.bulbagarden.net/wiki/Outrage_(move)), can strike twice.) [Moves with a charging turn](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_with_a_charging_turn) (such as [Fly](https://bulbapedia.bulbagarden.net/wiki/Fly_(move)) and [Solar Beam](https://bulbapedia.bulbagarden.net/wiki/Solar_Beam_(move))) only strike once, even if the Pokémon becomes fully charged in one turn (such as with a [Power Herb](https://bulbapedia.bulbagarden.net/wiki/Power_Herb)). [Endeavor](https://bulbapedia.bulbagarden.net/wiki/Endeavor_(move)) also only strikes once, even if the user or target's HP is changed after it strikes (such as by [Iron Barbs](https://bulbapedia.bulbagarden.net/wiki/Iron_Barbs_(Ability)) or the [Sitrus Berry](https://bulbapedia.bulbagarden.net/wiki/Sitrus_Berry)). [Confusion](https://bulbapedia.bulbagarden.net/wiki/Confusion_(status_condition)) damage only occurs once.

> [Spirit Shackle](https://bulbapedia.bulbagarden.net/wiki/Spirit_Shackle_(move)) and [Anchor Shot](https://bulbapedia.bulbagarden.net/wiki/Anchor_Shot_(move)) only [trap](https://bulbapedia.bulbagarden.net/wiki/Category:Trapping_moves) the target after the final strike.

**Comment by jaimefd** [comment]
> Does this deal with all the edge cases listed on [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Parental_Bond_(Ability))?
> 
> > If a move could hit multiple targets (including allies), such as [Earthquake](https://bulbapedia.bulbagarden.net/wiki/Earthquake_(move)) and [Rock Slide](https://bulbapedia.bulbagarden.net/wiki/Rock_Slide_(move)), it will not strike twice; however, if it can only hit a single Pokémon, such as in a Single Battle or if using a move that can hit multiple targets when only one target is in range, it will strike twice. If a move could hit multiple Pokémon but only hits one due to missing the other Pokémon, it will only strike once.
> 
> > If [Present](https://bulbapedia.bulbagarden.net/wiki/Present_(move)) heals the target it will only strike once, but if it damages the target it will strike twice (the second strike will always damage the target). [Fixed-damage moves](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_that_deal_direct_damage) (such as [Seismic Toss](https://bulbapedia.bulbagarden.net/wiki/Seismic_Toss_(move)) and [Dragon Rage](https://bulbapedia.bulbagarden.net/wiki/Dragon_Rage_(move))) deal the full amount of damage for both strikes. The damage dealt by [Psywave](https://bulbapedia.bulbagarden.net/wiki/Psywave_(move)) is generated separately for each strike, and the second strike's damage is not halved. Each strike of [Super Fang](https://bulbapedia.bulbagarden.net/wiki/Super_Fang_(move)) halves the target's HP (effectively quartering it if HP is not changed between strikes). [Counter](https://bulbapedia.bulbagarden.net/wiki/Counter_(move)), [Mirror Coat](https://bulbapedia.bulbagarden.net/wiki/Mirror_Coat_(move)), [Metal Burst](https://bulbapedia.bulbagarden.net/wiki/Metal_Burst_(move)), and [Bide](https://bulbapedia.bulbagarden.net/wiki/Bide_(move)) deal the full amount of damage for both strikes. The first strike of [Assurance](https://bulbapedia.bulbagarden.net/wiki/Assurance_(move)) counts as previously taking damage for the second strike, giving it increased power. [Fury Cutter](https://bulbapedia.bulbagarden.net/wiki/Fury_Cutter_(move)) and [Echoed Voice](https://bulbapedia.bulbagarden.net/wiki/Echoed_Voice_(move)) only consider uses of the move rather than hits, so the second strike's power is not boosted by the first strike. [Grass Pledge](https://bulbapedia.bulbagarden.net/wiki/Grass_Pledge_(move)), [Fire Pledge](https://bulbapedia.bulbagarden.net/wiki/Fire_Pledge_(move)), and [Water Pledge](https://bulbapedia.bulbagarden.net/wiki/Water_Pledge_(move)) strike twice, even when used as a combination move. [Natural Gift](https://bulbapedia.bulbagarden.net/wiki/Natural_Gift_(move)) and [Spit Up](https://bulbapedia.bulbagarden.net/wiki/Spit_Up_(move)) strike twice. [Moves that require recharging](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_that_require_recharging) after use strike twice, but the user only needs to [recharge](https://bulbapedia.bulbagarden.net/wiki/Recharge) for one turn.
> 
> > [One-hit knockout moves](https://bulbapedia.bulbagarden.net/wiki/One-hit_knockout_move), [Fling](https://bulbapedia.bulbagarden.net/wiki/Fling_(move)), [Self-Destruct](https://bulbapedia.bulbagarden.net/wiki/Self-Destruct_(move)), [Explosion](https://bulbapedia.bulbagarden.net/wiki/Explosion_(move)), [Final Gambit](https://bulbapedia.bulbagarden.net/wiki/Final_Gambit_(move)), [Uproar](https://bulbapedia.bulbagarden.net/wiki/Uproar_(move)), [Rollout](https://bulbapedia.bulbagarden.net/wiki/Rollout_(move)), and [Ice Ball](https://bulbapedia.bulbagarden.net/wiki/Ice_Ball_(move)) only strike once. (Other [consecutively executed moves](https://bulbapedia.bulbagarden.net/wiki/Category:Consecutively_executed_moves), such as [Outrage](https://bulbapedia.bulbagarden.net/wiki/Outrage_(move)), can strike twice.) [Moves with a charging turn](https://bulbapedia.bulbagarden.net/wiki/Category:Moves_with_a_charging_turn) (such as [Fly](https://bulbapedia.bulbagarden.net/wiki/Fly_(move)) and [Solar Beam](https://bulbapedia.bulbagarden.net/wiki/Solar_Beam_(move))) only strike once, even if the Pokémon becomes fully charged in one turn (such as with a [Power Herb](https://bulbapedia.bulbagarden.net/wiki/Power_Herb)). [Endeavor](https://bulbapedia.bulbagarden.net/wiki/Endeavor_(move)) also only strikes once, even if the user or target's HP is changed after it strikes (such as by [Iron Barbs](https://bulbapedia.bulbagarden.net/wiki/Iron_Barbs_(Ability)) or the [Sitrus Berry](https://bulbapedia.bulbagarden.net/wiki/Sitrus_Berry)). [Confusion](https://bulbapedia.bulbagarden.net/wiki/Confusion_(status_condition)) damage only occurs once.
> 
> > [Spirit Shackle](https://bulbapedia.bulbagarden.net/wiki/Spirit_Shackle_(move)) and [Anchor Shot](https://bulbapedia.bulbagarden.net/wiki/Anchor_Shot_(move)) only [trap](https://bulbapedia.bulbagarden.net/wiki/Category:Trapping_moves) the target after the final strike.

I did not, implement some of them, I'll set the PR as draft until I fix those

**Comment by bennybroseph** [comment]
Closing this due to inactivity. Feel free to make a new request if interest is reignited

**Pull request closed without merging**
