### PR TITLE
[Bug] Fix rare shiny Cleffa using default icon

### PR DESCRIPTION
**Pull request by chaosgrimmon**
## What are the changes?
Adds the rare shiny Cleffa icon to the relevant spritesheet and updates the datafile so that the game knows where it can be found.

[[Bug] Fix rare shiny Cleffa using default icon](https://github.com/chaosgrimmon/pokerogue/commit/c0b5d9aa0cdc232e6906c5379ab43ffa1ac5a2d6)
Rare shiny Cleffa's icon was showing up as the default colouration, or as shiny Lugia's icon when fused.
This fixes that by adding it to the spritesheet pokemon_icons_2v and its .json, where the console log suggested it should belong.

## Why am I doing these changes?
This has been reported *many* times on the Discord. Without the icon being on locatable on that spritesheet, the game defaults to either non-shiny Cleffa, or shiny Lugia, which is the first sprite on that sheet.
image
image
image
image

## What did change?
The icon was added to the first empty spot on the spritesheet. The .json of the same name was altered to indicate the coordinates of the sprite. This addition was placed immediately before the section handling Cleffa's Epic shiny icon. The sections are identical aside from the name and the canvas coordinates of the icon.

### Screenshots/Videos
image
image

## How to test the changes?
Any time where the rare Cleffa icon shows up should demonstrate the change, whether when selecting a starter, looking at savefiles, or switching out a Pokemon

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by bennybroseph** [comment]
> Are all unit tests still passing? (npm run test)
Why aren't these passing?

**Comment by chaosgrimmon** [comment]
Literally just didn't do them for a bog standard sprite update.

Is there a protocol to indicate that tests were not deemed necessary?
Like a "If this breaks things, there are bigger concerns that it highlights and it's not the change itself that's problematic"?

**Comment by chaosgrimmon** [comment]
✓ src/test/achievement.test.ts (1)
 ✓ src/test/pokemon.test.ts (5)
 ✓ src/utils.test.ts (6)
 ✓ src/test/debugImports.test.ts (2)
 ✓ src/test/pokemonSprite.test.ts (15)

 Test Files  5 passed (5)
      Tests  29 passed (29)
   Start at  18:07:37
   Duration  8.03s (transform 5.05s, setup 34.02s, collect 181ms, tests 140ms, environment 1.80s, prepare 1.22s)
   
   Is this a complete pass then?

**Comment by bennybroseph** [comment]
> ✓ src/test/pokemonSprite.test.ts (15)

Yes, can you see why they are important now?

**Comment by chaosgrimmon** [comment]
> why would you not run them
gotta learn how first lol. i don't use npm/js usually

**Comment by bennybroseph** [comment]
fair enough, let's remember for next time

**Review by bennybroseph — APPROVED** [review]

**Pull request merged**
