### PR TITLE
[QoL] Add victory screen after run win

### LINKED ISSUE #621: [Suggestion] Add victory screen after run win
Add a victory screen after you win showing all your Pokémon, elite four win style.

### PR DESCRIPTION
**Pull request by hayuna**
## What are the changes?
After win user will see whole party taken part in game. (Like a hall of fame after elite 4)

## Why am I doing these changes?
Resolves #621 

## What did change?
Add pokemon sprites in the end game screen

### Screenshots/Videos
Small species
346110462-6053a997-7b9b-46ad-bcb4-878480636c24

Bigger species
Screenshot 2024-07-05 at 13 35 40

## How to test the changes?
1. Win the game
2. (speed up solution) - Move to EndCardPhase
```javascript
(4233 line in phases.ts)
this.scene.pushPhase(new EndCardPhase(this.scene));
// this.scene.pushPhase(new PostGameOverPhase(this.scene, endCardPhase));            
```
Using code above, end game screen will be displayed after losing the game

## Checklist
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes (manually)?
    - [x] Are all unit tests still passing? (`npm run test`)
- [x] Are the changes visual?
  - [x] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by ReneGV** [comment]
Do we need a special handling for GMax Pokemon?

**Comment by hayuna** [comment]
Version with Mega and G-Max

Screenshot 2024-07-06 at 01 39 59

**Comment by frutescens** [comment]
One of the artists - koda want to sleep - has drew up some variously-colored hall of fame backgrounds
Would you like to use it? 

(Example below...)
image

**Comment by flx-sta** [comment]
@hayuna please use [github keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) to link the existing issue properly with this PR

**Comment by hayuna** [comment]
> @hayuna please use [github keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) to link the existing issue properly with this PR

Tried, but maybe we are not allowed to use this feature. Development section is not updating

The special keywords in a pull request description are interpreted when the pull request targets the repository's default branch. However, if the PR's base is any other branch, then these keywords are ignored, no links are created and merging the PR has no effect on the issues. If you want to link a pull request to an issue using a keyword, the PR must be on the default branch.

beta is not the default branch, so I guess thats why

**Comment by flx-sta** [comment]
Ooh…. Good to know… ouf

**Comment by hayuna** [comment]
New PR

https://github.com/pagefaultgames/pokerogue/pull/3303

**Pull request closed without merging**
