### PR TITLE
Correct SoulHeart, Moxie, Beast Boost, etc.

### PR DESCRIPTION
**Pull request by Shadowth117**
Correct SoulHeart, Moxie, Beast Boost, Chilling Neigh, Grim Neigh, and As One abilities to activate the same way as their official versions as noted in this issue: https://github.com/pagefaultgames/pokerogue/issues/1210

The conditions were actually reversed from what the games did:
https://bulbapedia.bulbagarden.net/wiki/Soul-Heart_(Ability)
https://bulbapedia.bulbagarden.net/wiki/Beast_Boost_(Ability)

### CODE REVIEW

**Review by TempsRay — APPROVED** [review]
LGTM

**Review by TempsRay — CHANGES_REQUESTED** [review]
Actually on second thought, PostKnockOut might not be the right attr

**Comment by Shadowth117** [comment]
> Actually on second thought, PostKnockOut might not be the right attr
Which would you use instead? Previously Soul Heart was using Post Knockout, but that appears to be wrong for it. It does however seem to be correct for the other abilities, which specifically describe that the pokemon needs to themselves directly knock out an opposing mon.

image

**Review by LaukkaE — CHANGES_REQUESTED** [review]
This will not work. PostKnockOut is called for every pokemon that is alive on the battlefield when fainting occurs. This is what currently happens on your branch.

https://github.com/pagefaultgames/pokerogue/assets/73663099/e7238cb4-7a01-451b-b833-da5fbfae696e

Moxie will get boost even though it is not the pokemon that attacked the fainted pokemon.

**Comment by Shadowth117** [comment]
> This will not work. PostKnockOut is called for every pokemon that is alive on the battlefield when fainting occurs. This is what currently happens on your branch.
> 
>  output.mp4 
> Moxie will get boost even though it is not the pokemon that attacked the fainted pokemon.

Ah, I understand, that makes sense.

**Comment by Shadowth117** [comment]
Okay, I think the new commit should be what we want, after testing it a bit. I ended up adding the attacker to postknockout and splitting it to any and direct variation. The direct variation checks specifically for if the attacker of the knocked out pokemon's killing blow was from them and if it was an attack's direct damage that did them in. The other version is what it was, and makes sense for Soul Heart to keep after comparing things.

I assumed the logic in phases.ts had a pretty necessary order and so the new logic there preserves it. I'd imagine you might be able to condense the if checks some, but for the sake of sanity, I left it as is in case it were to be a big deal.

**Comment by flx-sta** [comment]
No action within more than a month. 
Considered stale.

Feel free to re-open it when you are still working on it/want to work on it again

**Pull request closed without merging**
