### PR TITLE
[Balance] General Item Weight Adjustments

### PR DESCRIPTION
**Pull request by damocleas**
## What are the changes?
Readjusted items throughout the tiers

Master - Vouchers appearing just a bit too often with max luck. Looking at other items for the tier at some other point.
Voucher Premium - 6 -> 5 max

Rogue - Overall weight went down, some adjusted purely for that reason.
Rogue Ball: 24 -> 16
Form Change Items: 18 -> 15
Super Exp Charm: 10 -> 9
Voucher Plus: 5 -> 3 max
Soul Dew: 8 -> 7
Quick Claw: Rogue Tier -> Ultra Tier 

Ultra - Overall weight also went down here, some adjusted purely for that reason.
Ultra Ball: 24 -> 15
Attack Type Booster: 10 -> 9
TM Ultra: 8 -> 11
EXP Share: 12 -> 10
EXP Balance: 4 -> 3 
PP Up: 9 Ultra Tier -> 2 Great Tier

Great and Pokeball - TMs up
TM Great: 2 -> 3
TM Common: 1 -> 2

## Why am I doing these changes?
Pokeballs and TMs are weighed to give you too many pokeballs, and not enough TMs for how many you actually want/need in a run. Other changes with this to account for the numbers or move things around like PP Up to a lower tier or reducing weights of items to keep similar rarity as they were before.

## What did change?

Rogue Ball: 24 -> 16
Form Change Items: 18 -> 15
Super Exp Charm: 10 -> 9
Voucher Plus: 5 -> 3 max
Soul Dew: 8 -> 7
Quick Claw: Rogue Tier -> Ultra Tier
Ultra Ball: 24 -> 15
Attack Type Booster: 10 -> 9
TM Ultra: 8 -> 11
EXP Share: 12 -> 10
EXP Balance: 4 -> 3 
PP Up: 9 Ultra Tier -> 2 Great Tier
TM Great: 2 -> 3
TM Common: 1 -> 2

### Screenshots/Videos
image
image

## How to test the changes?
Merge this Draft/PR with a testing branch and play any mode.

## Checklist
- [X] There is no overlap with another PR?
- [X] The PR is self-contained and cannot be split into smaller PRs?
- [X] Have I provided a clear explanation of the changes?
- [X] Have I tested the changes (manually)?
    - [X] Are all unit tests still passing? (`npm run test`)
- [X] Are the changes visual?
  - [X] Have I provided screenshots/videos of the changes?

### CODE REVIEW

**Comment by Fontbane** [comment]
Mind making a table with all the odds? Would make it easier to get a feel for the new weights. Also, exp balance can go even further down from 3 to 2.

**Comment by damocleas** [comment]
> Mind making a table with all the odds? Would make it easier to get a feel for the new weights. Also, exp balance can go even further down from 3 to 2.

Copied from my phone, this is data from the testers that was given as a rough comparison between previous rates and new rates.
PokeBall / Great
image-4
Ultra
image-5
Rogue
image-6
Master
image-7

**Comment by Fontbane** [comment]
> > Mind making a table with all the odds? Would make it easier to get a feel for the new weights. Also, exp balance can go even further down from 3 to 2.
> 
> Copied from my phone, this is data from the testers that was given as a rough comparison between previous rates and new rates. PokeBall / Great image-4 Ultra image-5 Rogue image-6 Master image-7

What are these numbers out of? 1000?

**Comment by damocleas** [comment]
> What are these numbers out of? 1000? The nerf to ultra and rogue balls seems way bigger than intended.

yes they're out of 1000 simulated waves, the main intent was to make them still the highest in the tiers while also increasing the commonality of TMs in each tier since that's been a big problem
The only thing I can think to do is bring voucher plus counts down more the rest is intentional

**Comment by Fontbane** [comment]
> > What are these numbers out of? 1000? The nerf to ultra and rogue balls seems way bigger than intended.
> 
> yes they're out of 1000 simulated waves, the main intent was to make them still the highest in the tiers while also increasing the commonality of TMs in each tier since that's been a big problem The only thing I can think to do is bring voucher plus counts down more the rest is intentional

Yeah when I was asking for odds I meant like on paper, like the weight defined in the code and the default total weight of that tier. It makes it easier to adjust when we know the overall weights. We should definitely try to keep balls as close to base as possible.

**Review by Madmadness65 — APPROVED** [review]
I'm most iffy on the massive Ultra Ball and Rogue Ball weight drops, but this _should_ be okay. At the very least, increasing TM weights and decreasing voucher weights should be a healthy change.

**Pull request merged**
